### ISSUE TITLE
Issue with access to internet within the docker container

### ISSUE THREAD

**Issue by v-henvaldt** [microsoft/navcontainerhelper#2019] opened 2021-08-05 13:06 UTC
Hi all,

I am faced with an issue related to internet accessibility within the D365 BC container. I receive the following warning during the execution `New-BcContainer` script: `WARNING: DNS resolution not working from within the container.`

![image](https://user-images.githubusercontent.com/78726418/128352629-e1e4f02b-7cf9-4455-8f6d-8bf92ef72909.png)

DNS '8.8.8.8' was added as a parameter to the `New-BcContainer` script and in `daemon.json`
But unfortunately, the D365 BC extension can't perform any web request. I receive an error: `An error occurred while sending the request. The remote name could not be resolved: 'www.google.com'`. Also script `Sign-BCContainerApp` is failing with an error: `Downloading Signing Tools. Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'go.microsoft.com'"` 
Also, ping of any external resources failing.

![image](https://user-images.githubusercontent.com/78726418/128353510-6ef41a87-fdbc-4b4e-9ba4-c9b9afb0d3c2.png)

Below are OS and container versions:

Version: 17.5.22499.28611-US
Style: sandbox
Multitenant: No
Platform: 17.0.22463.28291
Generic Tag: 1.0.1.7
Container OS Version: 10.0.18363.1556 (1909)
Host OS Version: 10.0.18363.1556 (1909)
 
Can you please advise the solution to this issue?

**Comment by NAVspecialist** [comment] 2021-08-06 21:43
Did you use the parameter

-updatehosts

When you created the container ?

**Comment by freddydk** [comment] 2021-08-08 04:39
@NAVspecialist -- updatehosts is only for being able to access the container by name from the host - doesn't resolve this.

**Comment by freddydk** [comment] 2021-08-08 04:41
I am facing the same issue on my machine. When I reboot my machine, then it works for a while and then at some point in time, it stops working. Do you have the same situation?
I will investigate what this is, but I think it is some policy, which disallows my machine to relay DNS requests.

**Comment by freddydk** [comment] 2021-08-08 04:56
I actually thought that this was caused by some policy on MS CorpNet but I just tried something.
If I restart my computer, create a container - then it works.
If I close my computer lid (Sleep) and wake my computer up again - it stops working.

**Comment by freddydk** [comment] 2021-08-09 09:33
On my machine - these commands fixes the issue:

ipconfig /release
ipconfig /renew

When connected to our corporate network, our VPN (GlobalConnect) will ask me to login - when I do this, it stops working again. I don't really need the VPN when connected to our CorpNet, I will retry when I am at home again.

**Comment by freddydk** [comment] 2021-08-09 20:39
At home (non-corpnet) the two commands:
```
ipconfig /release
ipconfig /renew
```
also fixes the issue and the container can reach the internet again.
Here - GlobalConnect doesn't ask me to reconnect and it works even though I am connected to VPN.

Could you guys try out these commands before or after the container is created to see whether this solved the issue on your machine as well?

**Comment by freddydk** [comment] 2021-08-10 17:22
Will close the issue with this workaround.

**Closed by freddydk** 2021-08-10 17:22 UTC
Labels: question, Fix Ready

**Comment by v-henvaldt** [comment] 2021-08-16 07:02
Hi @freddydk, these commands were applied from my side before container creation but this does not help in my case. I still receiving the DNS resolution warning during the container creation, and the error inside the container when I tried to reach external web resources: ``An error occurred while sending the request. The remote name could not be resolved: 'www.google.com' ``

**Comment by freddydk** [comment] 2021-08-16 19:56
You likely have some antivirus or other policies/things, which prevents the container from doing DNS resolutions.
Can you ping 8.8.8.8 inside the container - then you do have internet connection.
You could try to create a transparent network in Docker and use that?
