### ISSUE TITLE
Release pipelines failing with SaaS environments due BcAuthContext

### ISSUE THREAD

**Issue by asaez85** [microsoft/navcontainerhelper#3727] opened 2024-10-16 12:12 UTC
Since this morning, our release pipelines have been failing when deploying to SaaS environments. The issue appears to be related to the Publish-PerTenantExtensionApps function, which was recently modified.
We are using BCContainerHelper version 6.0.26.

2024-10-16T11:46:24.2117258Z ##[section]Starting: Publish to PRE
2024-10-16T11:46:24.2126338Z ==============================================================================
2024-10-16T11:46:24.2126495Z Task         : PowerShell
2024-10-16T11:46:24.2126590Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2024-10-16T11:46:24.2126704Z Version      : 2.245.1
2024-10-16T11:46:24.2126784Z Author       : Microsoft Corporation
2024-10-16T11:46:24.2127578Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2024-10-16T11:46:24.2127710Z ==============================================================================
2024-10-16T11:46:26.1655676Z Generating script.
2024-10-16T11:46:26.3058028Z ========================== Starting Command Output ===========================
2024-10-16T11:46:26.3430541Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\c42c46eb-3db5-45ec-8319-43215f084752.ps1'"
2024-10-16T11:46:26.7391821Z Installing BcContainerHelper
2024-10-16T11:48:26.2312440Z Publishing to tenant
2024-10-16T11:48:26.7360427Z BcContainerHelper version 6.0.26
2024-10-16T11:48:29.3622866Z BC.HelperFunctions emits usage statistics telemetry to Microsoft
2024-10-16T11:48:29.5237858Z Running on Windows, PowerShell 5.1.20348.2652
2024-10-16T11:48:32.6017777Z LatestGenericTagVersion is 1.0.2.50
2024-10-16T11:48:33.8023667Z Publish-PerTenantExtensionApps Telemetry Correlation Id: 63187a89-017c-4e0e-9758-6995a0db55c4
2024-10-16T11:48:33.9056219Z BcAuthContext should be a HashTable created by New-BcAuthContext.
2024-10-16T11:48:33.9056814Z At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.26\HelperFunctions.ps1:882 char:9
2024-10-16T11:48:33.9058505Z +         throw 'BcAuthContext should be a HashTable created by New-BcA ...
2024-10-16T11:48:33.9059542Z +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-10-16T11:48:33.9060487Z     + CategoryInfo          : OperationStopped: (BcAuthContext s...-BcAuthContext.:String) [], RuntimeException
2024-10-16T11:48:33.9062206Z     + FullyQualifiedErrorId : BcAuthContext should be a HashTable created by New-BcAuthContext.
2024-10-16T11:48:33.9062796Z  
2024-10-16T11:48:34.0678695Z ##[error]PowerShell exited with code '1'.
2024-10-16T11:48:34.1192899Z ##[section]Finishing: Publish to PRE

**Comment by freddydk** [comment] 2024-10-16 12:24
OK, you need to revert to 6.0.25 until I issue a fix.

**Comment by freddydk** [comment] 2024-10-16 13:22
The problem is that a prior fix caused the function to no longer support ClientId/ClientSecret parameters - and in 6.0.26 only supports bcAuthContext parameter. You can get around this by calling:

```
$bcAuthContext = New-BcAuthContext `
    -clientID $clientID `
    -clientSecret $clientSecret `
    -tenantID $tenantId `
    -scopes "https://api.businesscentral.dynamics.com/.default"
```

and then transfer bcAuthContext instead - or wait for 6.0.27 (which will be in preview in a few hours)

**Comment by asaez85** [comment] 2024-10-16 13:25
Thank you very much for the quick response!

**Closed** 2024-10-16 19:04 UTC
Labels: bug
