### ISSUE TITLE
IIS URL Rewrite Module Not found

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/navcontainerhelper#1225] opened 2020-08-18 08:46 UTC
**Describe the issue**
While setting up a new docker it gives and you have cleared out your cache it gives a fault on downloading the IIS URL Rewrite module.

**Scripts used to create container and cause the issue**
```
$containerName = 'XYZ'
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'admin' -AsPlainText -Force)
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -version '' -country 'us' -select 'Latest'
$licenseFile = 'c:\data\license.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'XYZ' `
    -includeTestToolkit `
    -includeTestLibrariesOnly `
    -licenseFile $licenseFile `
    -dns '8.8.8.8' `
    -usessl -installCertificateOnHost `
    -memoryLimit 8G `
    -updateHosts
```

**Full output of scripts**
```
BcContainerHelper is version 1.0.2
BcContainerHelper is not running as administrator
Host is Microsoft Windows 10 Pro - 2004
Docker Client Version is 18.09.4
Docker Server Version is 19.03.12
Removing container XYZ
Removing XYZ from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\XYZ
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.19041.450-generic
10.0.19041.450-generic: Pulling from dynamicsnav
295f12394c4f: Already exists
b1cbf80244af: Already exists
8ea60ddac1dd: Already exists
6c5025716b21: Already exists
dafb3197a0d0: Already exists
4a6e01421e1a: Already exists
08f1b5cd4be5: Already exists
c274681aa0c9: Already exists
dc094d2d2a6d: Already exists
753106884cd7: Already exists
5c03f068e04b: Already exists
9bca890692a3: Already exists
92ee7304e9c6: Already exists
a2baadd9cff0: Already exists
50a806c60c8d: Already exists
737a05d22156: Already exists
5b071d228b54: Pulling fs layer
21c6f3c805a6: Pulling fs layer
21c6f3c805a6: Verifying Checksum
21c6f3c805a6: Download complete
5b071d228b54: Verifying Checksum
PS C:\Scapta Git\XYZ\app> $containerName = 'XYZ'
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'admin' -AsPlainText -Force)
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -version '' -country 'us' -select 'Latest'
$licenseFile = 'c:\data\license.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'XYZ' `
    -includeTestToolkit `
    -includeTestLibrariesOnly `
    -licenseFile $licenseFile `
    -dns '8.8.8.8' `
    -usessl -installCertificateOnHost `
    -memoryLimit 8G `
    -updateHosts
BcContainerHelper is version 1.0.2
BcContainerHelper is not running as administrator
Host is Microsoft Windows 10 Pro - 2004
Docker Client Version is 18.09.4
Docker Server Version is 19.03.12
Removing C:\ProgramData\BcContainerHelper\Extensions\XYZ
ArtifactUrl and ImageName specified
Fetching all docker images
Downloading application artifact /sandbox/16.4.14693.15627/us
Downloading C:\Users\FrankAuwers\AppData\Local\Temp\aa33d253-7152-411a-86d3-c4baa0bba2bb.zip
Unpacking application artifact to tmp folder using 7zip
Image XYZ:sandbox-16.4.14693.15627-us-mt doesn't exist
Building multitenant image XYZ:sandbox-16.4.14693.15627-us-mt based on https://bcartifacts.azureedge.net/sandbox/16.4.14693.15627/us
Building image XYZ:sandbox-16.4.14693.15627-us-mt based on mcr.microsoft.com/dynamicsnav:10.0.19041.450-generic
XYZ:sandbox-16.4.14693.15627-us-mt
Pulling latest image mcr.microsoft.com/dynamicsnav:10.0.19041.450-generic
10.0.19041.450-generic: Pulling from dynamicsnav
Generic Tag: 0.1.0.16
Container OS Version: 10.0.19041.450 (2004)
Host OS Version: 10.0.19041.450 (2004)
Using process isolation
Files in c:\bcartifacts.cache\tmp637333438415202542\my:
Downloading platform artifact /sandbox/16.4.14693.15627/platform
Downloading C:\Users\FrankAuwers\AppData\Local\Temp\21697ae2-1e74-44c9-9fd8-db331ec8e4b9.zip
Unpacking platform artifact to tmp folder using 7zip
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\16.4.14693.15627\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\16.4.14693.15627\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Download-File : Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.2\Misc\Download-Artifacts.ps1:206 char:45
+ ...             Download-File -sourceUrl $url -destinationFile $path -tim ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Download-File], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Download-File
...
```

**Additional context**
- does it happen all the time?
Yes, if the cache is cleared. If the cache folder is not cleared, it download nothing and will proceed the script.
- did it use to work?
It's the first time I try to use docker with artifacts.

**Comment by freddydk** [comment] 2020-08-18 08:46
Duplicate of #1224

**Comment by freddydk** [comment] 2020-08-18 08:47
You need ContainerHelper 1.0.3 - just shipped.
This morning everything broke.

**Closed by freddydk** 2020-08-18 08:46 UTC

**Comment by FrankAuwers** [comment] 2020-08-18 08:59
Hi Freddy,

Thank for the quick response.

I uninstalled the ContainerHelper 1.0.2 and installed the ContainderHelper 1.0.3 but when I execute the script it still says it is using version 1.0.2.

Also the error is the same:
[cid:image001.png@01D6754E.986A23C0]


Frank Auwers
Frank.Auwers@scapta.com
+32 477 498 527
Scapta
Corda Campus Kempische Steenweg 293 bus 38, 3500 Hasselt
Phone: +32 11 600 600
info@scapta.com
www.scapta.com
Scapta neemt een aantal uitzonderlijke maatregelen om de verspreiding van het coronavirus in te dijken.
This email may contain confidential information and/or
copyright material. This email is intended for the use of the addressee only.
Any unauthorized use may be unlawful. If you receive this mail by mistake,
please advise the sender immediately by using the reply facility in your email
software. Please don't print this e-mail unless you really need to.

**Comment by freddydk** [comment] 2020-08-18 09:10
Restart PowerShell after installing new ContainerHelper
