### ISSUE TITLE
Creating Container BC 17.2 don't install Microsoft_Tests-TestLibraries

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#1546] opened 2020-12-15 09:35 UTC
**Describe the issue**
on creating the BC17.2 image the script doesn't install the Test Libraries, they got downloaded to the bcartifacts.cache folder (see screenshot) but it does not install them. With BC17.1 all works great.
```
Downloading symbols: Microsoft_Tests-TestLibraries_17.0.0.0.app
Url : https://xxx.xxx.xxx.xxx:7049/BC/dev/packages?publisher=Microsoft&appName=Tests-TestLibraries&versionText=17.0.0.0&tenant=default
##[error]The remote server returned an error: (404) Not Found. No published package matches the provided arguments.
```

**Scripts used to create container and cause the issue**
```
New-BcImage -artifactUrl $artifactUrl -imageName $newImageName -includePerformanceToolkit:$true -includeTestToolkit:$true -licenseFile $licensefile
```

**Full output of scripts**
```
Formatted command: . 'C:\agent-01\_work\16\s\Create-Environment\Create-BCImage.ps1' -artifactUrl "https://bcartifacts.azureedge.net/sandbox/17.2.19367.20025/de" -imageName sandbox172de -workingDirectory C:\agent-01\_work\16\s -license fin.flf -includeTestToolkit True
========================== Starting Command Output ===========================
##[command]"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\agent-01\_work\_temp\25171795-cdca-4d68-a397-db6a450b0be2.ps1'"
Setting bcartifactsCacheFolder = c:\bcartifacts.cache
Setting usePsSession = True
Setting hostHelperFolder = C:\ProgramData\BcContainerHelper
Setting use7zipIfAvailable = True
Setting genericImageName = mcr.microsoft.com/dynamicsnav:{0}-generic
Setting containerHelperFolder = C:\ProgramData\BcContainerHelper
Setting sandboxContainersAreMultitenantByDefault = False
Setting defaultContainerName = bcserver
Setting defaultNewContainerParameters = 
BcContainerHelper version 1.0.16
Downloading application artifact /sandbox/17.2.19367.20025/de
Downloading C:\Users\beatAdmin\AppData\Local\Temp\34d4d928-96d6-4dad-a682-962e862f4888.zip
Unpacking application artifact to tmp folder using Expand-Archive
c:\bcartifacts.cache\sandbox\17.2.19367.20025\de
Downloading platform artifact /sandbox/17.2.19367.20025/platform
Downloading C:\Users\beatAdmin\AppData\Local\Temp\c223ab5d-771a-41db-8480-8ea936baf979.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\17.2.19367.20025\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\17.2.19367.20025\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\sandbox\17.2.19367.20025\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
c:\bcartifacts.cache\sandbox\17.2.19367.20025\platform
sandbox172de:testtoolkit
Building image sandbox172de:testtoolkit based on mcr.microsoft.com/dynamicsnav:10.0.17763.1577-generic with https://bcartifacts.azureedge.net/sandbox/17.2.19367.20025/de
Pulling latest image mcr.microsoft.com/dynamicsnav:10.0.17763.1577-generic
10.0.17763.1577-generic: Pulling from dynamicsnav
Generic Tag: 0.1.0.24
Container OS Version: 10.0.17763.1577 (ltsc2019)
Host OS Version: 10.0.17763.1637 (ltsc2019)
Using hyperv isolation
Using license file C:\agent-01\_work\16\s\fin.flf
Files in c:\bcartifacts.cache\ctwhyvmt.e54\my:
Copying Platform Artifacts
Copying Database
Copying Licensefile
Copying ConfigurationPackages
Copying Extensions
Copying Applications.DE
c:\bcartifacts.cache\ctwhyvmt.e54
Sending build context to Docker daemon  1.864GB

Step 1/6 : FROM mcr.microsoft.com/dynamicsnav:10.0.17763.1577-generic
 ---> 8e70404d55fc
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/17.2.19367.20025/de
 ---> Running in d0e7a80cd8fc
Removing intermediate container d0e7a80cd8fc
 ---> e2769f5ce330
Step 3/6 : COPY my /run/
 ---> 64cae37f5f9a
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 335c11369fbb
Step 5/6 : RUN \Run\start.ps1 -installOnly -includeTestToolkit -includePerformanceToolkit
 ---> Running in 4a977f0027b9
Using installer from C:\Run\150-new
Installing Business Central
Installing from DVD
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.DE
Starting Business Central Service Tier
Importing CRONUS license file
Publishing C:\Applications.DE\Microsoft_Any_17.2.19367.20025.app
Synchronizing Any
Installing Any
Publishing C:\Applications.DE\Microsoft_Library Assert_17.2.19367.20025.app
Synchronizing Library Assert
Installing Library Assert
Publishing C:\Applications.DE\Microsoft_Library Variable Storage_17.2.19367.20025.app
Synchronizing Library Variable Storage
Installing Library Variable Storage
Publishing C:\Applications.DE\Microsoft_Test Runner_17.2.19367.20025.app
This Extension cannot be published as it has the same Publisher, Name, and Version as a previously published Extension.
Removing intermediate container 4a977f0027b9
 ---> 174ad1d5adcd
Step 6/6 : LABEL legal="http://go.microsoft.com/fwlink/?LinkId=837447"       created="202012150900"       nav=""       cu=""       country="DE"       version="17.2.19367.20025"       platform="17.0.19353.19941"
 ---> Running in 8ef2ab1f91a5
Removing intermediate container 8ef2ab1f91a5
 ---> 86837c8cb0b6
Successfully built 86837c8cb0b6
Successfully tagged sandbox172de:testtoolkit
Building image took 344 seconds
New sandbox172de:TestToolkit Image Created!
```

**Screenshot**
![image](https://user-images.githubusercontent.com/7090519/102197157-0e08cc80-3ec1-11eb-90d9-632b54659225.png)

**Additional context**
- BCContainerHelper is version 1.0.16
- BCContainerHelper is running as administrator
- Host is Windows Server 2019 Datacenter - ltsc2019
- Docker Client Version is 19.03.11
- Docker Server Version is 19.03.11

**Comment by freddydk** [comment] 2020-12-15 11:59
Duplicate of #1545  - I will respond in the first issue

**Comment by freddydk** [comment] 2020-12-15 12:16
I don't think this is a duplicate anyway.
I will investigate this.

**Comment by freddydk** [comment] 2020-12-15 13:14
In 17.2, the performance toolkit and the test runner are pre-published in the database.
BcContainerHelper will automatically check whether the test apps are installed before installing, but the generic image doesn't do this (since I thought I knew that apps couldn't be installed):-(
if you add -myscripts @("https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/150-new/navinstall.ps1") to your new-bcimage call then it will grab the installer from the next generic version and use that.

It is not all though - it seems like the performance toolkit cannot be installed on Docker at all - there seem to be a check which disallows it to be installed on anything but onprem or online sandboxes - this check of course will need to change in the perf toolkit app - for now - avoid -includeperformancetoolkit on sandbox images.

**Comment by freddydk** [comment] 2020-12-16 06:45
All generic images:
```
SQL 2019: mcr.microsoft.com/businesscentral:{0}
SQL 2017: mcr.microsoft.com/businesscentral:{0}-qsl2017
```
(note the new naming of the sql2017 image)

have been rebuilt with a fix to handle the existence of Test Runner in the database.
Performance toolkit fix waits for a fix from the perf toolkit team in a future version of 17.2 likely.
Note: perf toolkit will still works on onprem containers.

**Closed** 2020-12-18 14:51 UTC
Labels: Fix Ready, bug
