### ISSUE TITLE
Publish-BcContainerApp "Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty, and then try the co mmand again."

### ISSUE THREAD

**Issue by QuartzBC** [microsoft/navcontainerhelper#1446] opened 2020-11-12 11:57 UTC
Hola,
I wanted to publish an extension on a container with the command "publish-BcContainerApp" (PowerShell as admin). I get the following error:
Application App Exists
Downloading app: Application
Url : http://172.24.138.137:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=17.0.16993.0&tenant=default
Publishing
Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty, and then try the co
mmand again.
at <ScriptBlock>, <No file>: line 15
Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty, and then try the
command again.
Au caractère C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.13\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 : 13
+ Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidData : (:) [Publish-NAVApp], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
+ PSComputerName : ee34cc225445648c78b93f82f2a48477c7df2d20b732714bc43bbe1d174cc99d_

thank you in advance for your help,
Pedro

**Comment by freddydk** [comment] 2020-11-12 12:40
full script and full output - else it is impossible to help

**Comment by QuartzBC** [comment] 2020-11-12 14:05
of course Freddy,..thank for you help


<img width="912" alt="2020-11-12 13_52_57-CESSES Mathilde _ Microsoft Teams" src="https://user-images.githubusercontent.com/68864527/98942583-852bf900-24ee-11eb-82cb-7d8c6163e9b4.png">


PS C:\WINDOWS\system32> Publish-NewApplicationToBcContainer -appFile "C:\Users\mathilde.cesses\VESI_Core Model VE_1.0.0.0.app" -containerName BC17US -credential admin -doNotUseDevEndpoint
Application App Exists
Downloading app: Application
Url : http://172.24.138.137:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=17.0.16993.0&tenant=default
Publishing
Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty, and then try the co
mmand again.
at <ScriptBlock>, <No file>: line 15
Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty, and then try the
command again.
Au caractère C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.13\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 : 13
+ Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidData : (:) [Publish-NAVApp], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
+ PSComputerName : ee34cc225445648c78b93f82f2a48477c7df2d20b732714bc43bbe1d174cc99d 


same problem with publish-bcContainerapp.
The problem occurs on a colleague (functional consultant)computer. She is the admin of her PC.

**Comment by TrippyZ** [comment] 2020-11-12 18:02
You didn't proved the container creation script.  

However I think the problem is your credential parameter.  You should be doing something like this to construct it;
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword

**Comment by freddydk** [comment] 2020-11-13 12:12
You are using Publish-NewApplicationToBcContainer - that is used to publish a new base application to a container (and remove the old).
If you are publishing an app, you should use Publish-BcContainerApp.

**Comment by jrowland1993** [comment] 2020-11-17 11:35
Hi @freddydk - I am also experiencing this issue trying to publish a container app (Publish-BCContainerApp). I see this is marked as Fix Ready, is there any way to get this fix?

**Comment by freddydk** [comment] 2020-11-17 18:50
The fix for @QuartzBC was to use Publish-BcContainerApp instead of Publish-NewApplicationToBcContainer
Your issue is different - it looks like you have created the container using docker run (not New-BcContainer) - the functions in containerhelper will only work if you created the container with New-BcContainer (creates a number of shares used by other functions).

**Comment by jrowland1993** [comment] 2020-11-17 18:52
Thanks @freddydk, that’s correct. I’ll give it a go tomorrow

**Closed** 2020-11-22 15:21 UTC
Labels: Fix Ready, question
