### ISSUE TITLE
Microsoft.Dynamics.Nav.Apps.Tools not loaded on container restart

### ISSUE THREAD

**Issue by nickgoddard777** [microsoft/navcontainerhelper#2763] opened 2022-11-03 12:51 UTC
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
A clear and concise description of what the issue is.

If I have a docker container created from BCContainerHelper. If I restart the container either as restart-bccontainer or stop-bccontainer/start-bccontainer.  I can no longer run any scripts that use Invoke-ScriptInBcContainer.  if I Enter-BCContainer than I can load-module and run commands.

**Scripts used to create container and cause the issue**
```
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'gb' -select 'Latest'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'bc21-saas-171022' `
    -multitenant:$false `
    -includeTestToolkit `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -vsixFile (Get-LatestAlLanguageExtensionUrl) `
    -updateHosts `
    -EnableTaskScheduler:$false
```

**Full output of scripts**
```
Get-BcContainerServerConfiguration -containerName "bc21-fdl"
The term 'Get-NavServerInstance' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.

Exception Script Stack Trace:
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.12\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 61
at Get-BcContainerServerConfiguration, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.12\ContainerInfo\Get-NavContainerServerConfiguration.ps1: line 19
at <ScriptBlock>, <No file>: line 1

PowerShell Call Stack:
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.12\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 71
at Get-BcContainerServerConfiguration, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.12\ContainerInfo\Get-NavContainerServerConfiguration.ps1: line 19
at <ScriptBlock>, <No file>: line 1

Container Free Physical Memory: 2.3Gb

Services in container bc21-fdl:
- MicrosoftDynamicsNavServer$BC is Running
- MSSQL$SQLEXPRESS is Running

Get-BcContainerServerConfiguration Telemetry Correlation Id: 2d4879c0-002b-4db8-94bb-fa573ae25bd9
The term 'Get-NavServerInstance' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.12\ContainerHandling\Invoke-ScriptInNavContainer.ps1:112 char:13
+             throw $errorMessage
+             ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The term 'Get-N... and try again.:String) [], RuntimeException
    + FullyQualifiedErrorId : The term 'Get-NavServerInstance' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
    path was included, verify that the path is correct and try again.
...
```

**Screenshots**

**Additional context**
- does it happen all the time?  I'm pretty sure this happens after every restart and has done for a number of versions
- did it use to work? It works when the Container is first created

**Comment by freddydk** [comment] 2022-11-03 13:13
Looks like a duplicate of #2671, which was fixed in 4.0.2
You are running 3.0.12, which is a very old version.

**Closed** 2023-05-06 14:36 UTC
Labels: question, Fix Ready
