### ISSUE TITLE
After updating Docker(Win10) and after PC restart all containers cannot be stopped or started

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/navcontainerhelper#548] opened 2019-08-06 14:28 UTC
After updating Docker(Win10) and after PC restart all containers cannot work. You cannot stop it or run it again. It just stays there  and do nothing.
ERROR:
docker container error: an error occurred while sending the request. unable to connect to the remote server a connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Note: i have changed the ip address of container and everithing is fine when i inspect container. But it cannot be stopped

**Comment by freddydk** [comment] 2019-08-06 15:20
If I understand this correctly, you had some containers running and did an update of docker - and now the containers are limbo - they are there but you cannot use them, stop them or kill them?
Your only option might be to open docker desktop settings and reset to factory defaults (which will kill everything) and you can start from scratch.

**Comment by freddydk** [comment] 2019-08-06 15:37
What version of Docker are you running?
(run docker version in a cmd prompt)

**Comment by VladimirVeljovic** [comment] 2019-08-06 15:57
PS C:\WINDOWS\system32> docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:25:07 2019
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by VladimirVeljovic** [comment] 2019-08-06 15:58
and i installed from docker site:
![image](https://user-images.githubusercontent.com/53824412/62555723-bf323800-b873-11e9-9850-5ad413627ef4.png)

**Comment by VladimirVeljovic** [comment] 2019-08-06 15:59
> If I understand this correctly, you had some containers running and did an update of docker - and now the containers are limbo - they are there but you cannot use them, stop them or kill them?
> Your only option might be to open docker desktop settings and reset to factory defaults (which will kill everything) and you can start from scratch.

YES, exactly

**Comment by freddydk** [comment] 2019-08-06 15:59
Yes, I am running the same and I also had a similar problem yesterday and again today.
I thought I was doing something wrong - but realize that this might be a problem with the latest docker version.
will try to downgrade and see if my problem disappears.

**Comment by VladimirVeljovic** [comment] 2019-08-06 16:01
if you downgrade it will work. We already try that. I am also in contact with several partners and they are having the same issue

**Comment by freddydk** [comment] 2019-08-06 16:03
You are saying that downloading this Docker Community Edition 2.0.0.3 2019-02-15
from https://docs.docker.com/docker-for-windows/release-notes/ will fix the issue?
Then that should be the workaround.

Will do some testing and contact the people in MS who work with docker and see what we can do.

**Comment by VladimirVeljovic** [comment] 2019-08-06 16:04
i tried everithing with Hiper-V. Tried to stop, restart, kill the docker containt but it doesnt work. I tried changing to linux and set the memory to 4gb and return back to windows container...doesnt work.
I you have any ideas or approach i would appropriate it

**Comment by VladimirVeljovic** [comment] 2019-08-06 16:04
> You are saying that downloading this Docker Community Edition 2.0.0.3 2019-02-15
> from https://docs.docker.com/docker-for-windows/release-notes/ will fix the issue?
> Then that should be the workaround.
> 
> Will do some testing and contact the people in MS who work with docker and see what we can do.

Yes!

**Comment by freddydk** [comment] 2019-08-06 16:06
re: I you have any ideas or approach i would appropriate it
Is this because you have a container with something inside you need?

**Comment by VladimirVeljovic** [comment] 2019-08-06 16:07
i also suspect on isolation parameter

> re: I you have any ideas or approach i would appropriate it
> Is this because you have a container with something inside you need?

Not at the moment. But in the future i will need. Also creating all from the scratch is very time consuming

**Comment by VladimirVeljovic** [comment] 2019-08-06 16:08
i will try removing isolation parameter later today to see if it is going to work

**Comment by freddydk** [comment] 2019-08-06 16:08
I expect that this is a bug in docker - they will have to fix.
Use the old version instead of spending more time on 2.1.0.0

**Comment by freddydk** [comment] 2019-08-07 05:52
https://freddysblog.com/2019/08/07/zombie-containers-skip-this-build/

**Comment by freddydk** [comment] 2019-08-08 05:43
The issue is tracked here: https://github.com/moby/moby/issues/39623

**Comment by thaJeztah** [comment] 2019-08-09 00:05
Fix is in the works; https://github.com/moby/moby/pull/39703

**Comment by freddydk** [comment] 2019-09-06 07:08
Docker Engine 19.03.2 has been released, which fixes this issue.
Docker Desktop 2.1.0.2 includes this

**Closed by freddydk** 2019-09-06 07:08 UTC
Labels: Unrelated to navcontainerhelper
