### ISSUE TITLE
Publish-PerTenantExtensionApps does not remove the previous version during republish

### ISSUE THREAD

**Issue by roma-228** [microsoft/navcontainerhelper#3372] opened 2024-02-26 09:05 UTC
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When republishing the app as a PTE but with a new version using Publish-PerTenantExtensionApps.ps1, the problem is that the old version remains.
That is, an application with version 1.0.1.0 has already been published on Business central
i want to update this app and install 1.0.2.0
the app is published and installed, but the old version still hangs, how can I remove it, and can I add an option that will do this in Publish-PerTenantExtensionApps
I would like it to work as Publish-BcContainerApp when re-installing the extension as a PTE, namely when re-publishing the app with a newer version, the new version is published and installed and the old version is completely removed from the Business central SaaS

**Scripts used to create container and cause the issue**
```
              Publish-PerTenantExtensionApps `
              -bcAuthContext $authContext `
              -environment $environment `
              -appFiles $appPaths `
              -hideInstalledExtensionsOutput
```

**Full output of scripts**
```
BcContainerHelper version 6.0.6
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Attempting authentication to https://api.businesscentral.dynamics.com/user_impersonation offline_access using refresh token...
Authenticated using refresh token as user ***
https://api.businesscentral.dynamics.com/v2.0/Sandbox/api/microsoft/automation/v2.0/companies
Company 'My Company' has id 37375089-41bc-ee11-907c-6045bde9cc8b
https://api.businesscentral.dynamics.com/v2.0/Sandbox/api/microsoft/automation/v2.0/companies(37375089-41bc-ee11-907c-6045bde9cc8b)/extensions

NP_Functionality_1.0.47811.0.app - upgrading..............completed

...
```

**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/60844215/f5779840-9707-49a0-bcf3-248a2d8ec59b)

**Comment by OUAIRY** [comment] 2024-06-16 16:30
I'm interested for the same functionnality. Thank you

**Comment by freddydk** [comment] 2024-06-17 10:41
Duplicate of #2808

**Closed by freddydk** 2024-06-17 10:41 UTC
Labels: duplicate, enhancement
