### ISSUE TITLE
Restarting the Navison Docker Container and changing ip-addresses

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#139] opened 2018-05-25 18:15 UTC
We're using a seperate SQL Container that's connected to a Navision Container during installation.
It seems that when restarting a container it loses it's current ip-address and receives a new one.
There lays a problem, because the Navision Container then loses it's connection to the SQL Container.
Furthermore when I use the parameter -updateHosts, the hosts file isn't updated during restart.
I use the IP-adress from the SQL Container with the -databaseserver parameter, so when that is changed I loses connection.
Already asked on the docker forum if it's possible to retain the containers ip-address, but didn't receive an answer yet. I see that it's possible to ping the SQL Container by ip-address from within the NAV Container
I can also find the SQL containers ip-address from outside de Nav Containers with a docker command.
My question(s):
Do you know a practical way to reconnect these containers after restart.
Or is it possible to use the same docker command from inside the navision container to find the ip-address from the SQL container, and than reconfigure the Navision Container to reconnect to the SQL container.

**Comment by freddydk** [comment] 2018-05-25 19:05
As I read the problem, it is that your SQL Container gets a new IP address when it restarts - right?
Or do you also have problems with the NAV container?

**Comment by mheijkant** [comment] 2018-05-25 19:52
That's a good option. 
Only problem left, is when I want to add a dosen containers to automatically give them unique ip- addresses. But I think I can solve that problem myself.

**Comment by freddydk** [comment] 2018-05-25 19:57
You can add another network with a range, which you use - all of that is standard docker networking which I don't know much about.

**Comment by Koubek** [comment] 2018-05-26 11:55
@mheijkant I think you should use container names (host names) instead of using IPs. Or is there any reason not to do so?

**Comment by mheijkant** [comment] 2018-05-26 13:52
I thought so too, but than you should be able to see the sql container from inside the nav container. I could only ping the sql container unless I knew the ip-address. I could not ping the sql container by hostname or container name. For now I'm going for the --ip suggestion Freddy gave.

**Comment by Koubek** [comment] 2018-05-27 11:44
IMO, you should be able to ping containers within the same docker network. Maybe, after the restart, you could face DNS refresh problem. I usually use the same container name and container hostname.

* Start SQL container.
* Start NAV container.
* Run `ping [sql_host_name]` from the NAV container. You should be able to ping it correctly.
* Restart your SQL container and ping immediately again your SQ container. You probably won't be able to receive any positive response because your SQL has been assigned another IP address.
* You can wait and try it again later (ping again after some while, 30 minutes should be OK). You probably should be able to ping it again.
* Or you can run `ipconfig /flushdns` from you NAV container and ping again your SQL container. Now you should be able to ping it correctly.

**Comment by mheijkant** [comment] 2018-05-30 08:05
Giving the SQL-container a static IP-address and the nav-Container a Dynamic IP-address works.
Giving the SQL-container a static IP-address and the nav-Container also a static IP-address works.
Until I restart the NAV-Container. So I still seem to have the same problem.

I tried to connect the WebClient to a ipaddress but that didn't work.
Ran the Get-NavContainerEventLog and that gave some information and warnings about the navision installation, but only codes and no textual explanation like "The description for Event ID 202 from source MicrosoftDynamicsNavServer$NAV cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer."

Test-NavContainer gave me a TRUE.

How else can I debug the navision installation to find the problem.

**Comment by mheijkant** [comment] 2018-05-31 07:00
The Navision Service is not restarted after the container has restarted. But by helping it a hand with " Start-Service 'MicrosoftDynamicsNavServer$NAV'" from inside the container, it connects back to the sql-container. Re-connecting back with the RTC client works, but the Web-client doesn't.

I used "Get-Service micro* | select -property name,starttype""to find the startup-type and I found this to be Manual, with partly explains my issue?!

PS C:\> Get-Service micro* | select -property name,starttype
Name                           StartType
----                           ---------
MicrosoftDynamicsNavServer$NAV    Manual

my question(s):
Is this starttype slipped in by accident, or is this somehow related to the configuration that I us.
Can this startup type be "automatic (with delay)" by default in the nav-container. Otherwise I have to do this myself after the container creation.
Are there other services that are used to make the webclient work, that aren't started after the container restart. How to debug the webclient.

**Comment by mheijkant** [comment] 2018-05-31 08:40
I compared the services running after creating the navcontainer and after the container is restarted. I filtered all services that have starttype = manual and that were started the first time after creating the container.
[Services.xlsx](https://github.com/Microsoft/navcontainerhelper/files/2057423/Services.xlsx)

So when manualy restarting the "MicrosoftDynamicsNavServer$NAV" and "W3SVC" services, the Nav service connects back to the SQL Container, the RTC client connects again and the WebClient connects again.

**Comment by freddydk** [comment] 2018-05-31 12:28
That sounds like a bug.
The services are set to manual by design, but they should be started in the navstart script (which is running with a variable names restartinginstance set to true.
Could you tell me the exact parameters you are using to create the nav container (except for passwords)

**Comment by freddydk** [comment] 2018-05-31 12:41
I would also like a output of the logs of a container after restartet.
The navstart contains this code 
if ((Get-Service -name $NavServiceName).Status -ne "Running") {
    Write-Host "Starting NAV Service Tier"
    Start-Service -Name $NavServiceName -WarningAction Ignore
} else {
    Write-Host "Restarting NAV Service Tier"
    Restart-Service -Name $NavServiceName -WarningAction Ignore
}
which should always start the nav service.

**Comment by mheijkant** [comment] 2018-05-31 14:03
What logs are you referring to. Do you mean the container application eventlog and container inspect log or also some oher log.

Recreating this might be kind of tricky, because the nav-container is created together with a SQL container that is also using an exernal database.  But the script I Use to create the Nav Container is as shown below. Just a wild gues, but I overrule the hostname because of the gMsa I configured. Your script uses the containername also as hostname. maybe there's something to look at.

            New-NavContainer -containerName "NAV-dockermodul" `
                            -imageName "microsoft/dynamics-nav:2017-cu9" `
                            -licenseFile "c:\users\michel\foodware\Licenses\5164953 NAV2017.flf" `
                            -Credential $navCredential `
                            -memoryLimit "4G" `
                            -auth "Windows" `
                            -databaseServer "172.18.240.34" `
                            -databaseName "dockermodulesfood" `
                            -databaseCredential $databaseCredential `
                            -shortcuts "Desktop" `
                            -includeCSide `
                            -updateHosts `
                            -accept_eula `
                            -restart always `
                            -doNotExportObjectsToText `
                            -AdditionalParameters @($param)

Where $param = 
[0] = "-v c:\users\michel\foodware\Objects:c:\original -v C:\Users\michel\Schouw\PS\Export\Objects:c:\export -v C:\Users\michel\Schouw\PS\Import\Objects:c:\import -v C:\Users\michel\Schouw\PS\Backup:c:/backup -e locale=nl-NL -p 7150:7045 -p 7156:80 -p 7151:7046 -p 7152:7047 -p 7153:7048 -p 7154:7049"
[1] = "--security-opt credentialspec=file://NAV-Container.json"
[2] = "--hostname NAV-Container"
[3] = "--ip=172.18.240.37"

**Comment by freddydk** [comment] 2018-05-31 14:05
docker logs container

**Comment by mheijkant** [comment] 2018-05-31 14:19
Ive added this logging afterinstall and afterrestart.
[NavContainerLogs.zip](https://github.com/Microsoft/navcontainerhelper/files/2058576/NavContainerLogs.zip)

**Comment by freddydk** [comment] 2018-05-31 14:23
So, what you run into is another bug, causing this:
Initializing...
Cannot find path 'C:\run\my\aes.key' because it does not exist.
at <ScriptBlock>, C:\Run\SetupVariables.ps1: line 44
at <ScriptBlock>, C:\Run\navstart.ps1: line 23
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1

A problem when restarting containers with windows auth. Will be fixed in next update.
for now, you can set this env. variable: 

RemovePasswordKeyFile=N

then aes.key will exist and everything should be fine.

**Comment by mheijkant** [comment] 2018-05-31 14:27
Thanks. I also bypassed this issue by invoking a session to the container and set the service to automatic

**Comment by freddydk** [comment] 2018-05-31 15:08
Well, since it throws during navstart, you might run into other things not being set/working - updating your hosts file is one that never gets executed.

**Comment by freddydk** [comment] 2018-06-04 23:30
This will be fixed in the next version of the navcontainerhelper.

**Comment by freddydk** [comment] 2018-06-06 20:29
version 0.2.9.0 has been released

**Closed by freddydk** 2018-06-06 20:29 UTC
Labels: Fix Ready
