### ISSUE TITLE
Unable to create new container using bc insider

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/navcontainerhelper#848] opened 2020-02-13 10:58 UTC
HI,

trying to create new container using bc insider. 

OS Windows Server 2016 - 64 bit

Below is the error 

```
Initialization of container bcinsider failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.26\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...cinsider failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bcinsider failed
```

below are the details. 

> NavContainerHelper is version 0.6.4.26
> NavContainerHelper is running as administrator
> Host is Microsoft Windows Server 2016 Standard - ltsc2016
> Docker Client Version is 18.09.1
> Docker Server Version is 18.09.1
> Using image bcinsider.azurecr.io/bcsandbox-master:us-ltsc2016
> Creating Container bcinsider
> Version: 16.0.11104.0-us
> Style: sandbox
> Platform: 16.0.11059.0
> Generic Tag: 0.0.9.98
> Container OS Version: 10.0.14393.3443 (ltsc2016)
> Host OS Version: 10.0.14393.3443 (ltsc2016)
> Using locale en-US
> Using process isolation
> Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
> Using license file C:\myFolder\mylicense.flf
> Files in C:\ProgramData\NavContainerHelper\Extensions\bcinsider\my:
> - AdditionalOutput.ps1
> - license.flf
> - MainLoop.ps1
> - SetupVariables.ps1
> - updatehosts.ps1
> Creating container bcinsider from image bcinsider.azurecr.io/bcsandbox-master:us-ltsc2016
> 73854aa201767396beaf45d861ab56dfafbd529454ee07ad59c00fa1879ecfeb
> Waiting for container bcinsider to be ready
> Initializing...
> Setting host.containerhelper.internal to 172.22.0.1 in container hosts file
> Starting Container
> Hostname is bcinsider
> PublicDnsName is bcinsider
> Using NavUserPassword Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint C6F3F6BE92D861CA278357F8D0826DCD4C19B1BB
> Modifying Service Tier Config File with Instance Specific Settings
> Starting Service Tier
> Registering event sources
> Creating DotNetCore Web Server Instance
> The data is invalid. (Exception from HRESULT: 0x8007000D)
> at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
> at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
> at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
> at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
> at <ScriptBlock>, C:\Run\navstart.ps1: line 157
> at <ScriptBlock>, C:\Run\start.ps1: line 121
> at <ScriptBlock>, <No file>: line 1Error
> Initializing...
> Setting host.containerhelper.internal to 172.22.0.1 in container hosts file
> Starting Container
> Hostname is bcinsider
> PublicDnsName is bcinsider
> Using NavUserPassword Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint C6F3F6BE92D861CA278357F8D0826DCD4C19B1BB
> Modifying Service Tier Config File with Instance Specific Settings
> Starting Service Tier
> Registering event sources
> Creating DotNetCore Web Server Instance
> The data is invalid. (Exception from HRESULT: 0x8007000D)
> at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
> at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
> at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
> at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
> at <ScriptBlock>, C:\Run\navstart.ps1: line 157
> at <ScriptBlock>, C:\Run\start.ps1: line 121
> at <ScriptBlock>, <No file>: line 1
```
> Initialization of container bcinsider failed
> At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.26\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
> + ...             throw "Initialization of container $containerName failed" ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Initialization ...cinsider failed:String) [], RuntimeException
>     + FullyQualifiedErrorId : Initialization of container bcinsider failed
```
>

**Comment by freddydk** [comment] 2020-02-13 13:03
Did you retry the operation to see whether it happens the same place?

**Comment by tejabalusu** [comment] 2020-02-13 13:32
yes, tried in multiple docker machines

**Comment by freddydk** [comment] 2020-02-13 13:59
What PowerShell script are you using (without the insider password:-))?

**Comment by Charan-D365** [comment] 2020-02-13 14:12
i am having the same issue

**Comment by Charan-D365** [comment] 2020-02-13 14:13
PS C:\Users\vmadmin> $imageName = "bcinsider.azurecr.io/bcsandbox-master:us"
$containerName = "BC"
$auth = "UserPassword"
$credential = New-Object pscredential 'xxxxxxxxxxxxxx', (ConvertTo-SecureString -String 'xxxxxxxxxxxx' -AsPlainText -Force)
$licenseFile = "C:\Users\vmadmin\Desktop\License_051018.flf"

New-navcontainer -accept_eula `
                -imageName $imageName `
                -containerName $containerName `
                -auth $auth `
                -credential $credential `
                -updateHosts `
                -isolation hyperv ` -licenseFile $licenseFile -includeAL

**Comment by freddydk** [comment] 2020-02-13 14:16
Will try to repro

**Comment by tejabalusu** [comment] 2020-02-13 14:21
New-BCContainer -accept_eula `
                -imageName bcinsider.azurecr.io/bcsandbox-master:us `
                -containerName bcinsider `
                -auth NavUserPassword `
                -licenseFile 'C:\myFolder\mylicense.flf' `
                -updateHosts `
                -alwayspull

**Comment by VejdelekJ-SOL** [comment] 2020-02-13 14:21
The same issue for us - CZ insider image.
Jiří

**Comment by freddydk** [comment] 2020-02-13 15:33
Yep, I can repro this - looks like latest insider builds are broken (which can happen, but shouldn't)
Will investigate

**Comment by tejabalusu** [comment] 2020-02-13 15:56
do you have any previous build version that is working in the meantime?

**Comment by freddydk** [comment] 2020-02-13 16:41
I can see that my pipeline was able to create a container with 16.0.11044.0, so you can use:
bcinsider.azurecr.io/bcsandbox-master:16.0.11044.0-us-ltsc2019 (or ltsc2016 if you are running server 2016)

OR

I found out that the reason for this is, that URL rewrite and ASPNETCORE wasn't installed correctly on the base image - I don't know why, but that seems to be the reason. 
This should be fixed tomorrow (with new builds) or you can add

-usegenericImage 'mcr.microsoft.com/dynamicsnav:generic-ltsc2019'
if you are running Windows Server 2019.

-usegenericImage 'mcr.microsoft.com/dynamicsnav:generic-ltsc2016'
if you are running Windows Server 2016.

and 

-useBestContainerOS
if you are running Windows 10 1903 or 1909.

That should also work (or at least - it works here).

**Comment by Charan-D365** [comment] 2020-02-13 17:21
thanks freddy it worked :)

**Comment by freddydk** [comment] 2020-02-15 05:26
This was caused by a Windows Update to the Docker Build Servers. Read the full story here: https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/  as you might yourself be hit by that security update.

**Closed** 2020-02-23 18:11 UTC
Labels: Fix Ready, question
