### ISSUE TITLE
Login Issue to BC Docker

### ISSUE THREAD

**Issue by BSSIRajbir** [microsoft/navcontainerhelper#1601] opened 2021-01-06 23:51 UTC
**Describe the issue**
 I am creating New Container with BCHelperConatiner. The container is getting created but when I am trying to login it is throwing me an error that "You cannot sign in due to a technical issue. Contact your system administrator.". And When I am trying to download the symbols that time it is throwing me an error that "Authorization has failed or the credentials have expired. The credential cache has been cleaned. Any access to reach Business Central would require new authorization."

**Scripts used to create container and cause the issue**
```
$artifactUrl = Get-BCArtifactUrl -version 17.2 -country us -select latest
New-BCContainer -includeAL -containerName PPR -accept_eula -auth NavUserPassword -ACCEPT_OUTDATED -artifactUrl $artifactUrl  -licenseFile C:\Users\rajbir\Desktop\LicenseKeys\D365BC-V17.flf -updateHosts  -additionalParameters @('--cpu-count 4') -includeTestToolkit   -includeTestLibrariesOnly -assignPremiumPlan


```

**Screenshots**
![image](https://user-images.githubusercontent.com/43894249/103833754-9b5dbd80-5036-11eb-91c5-ebf958c14709.png)

![image](https://user-images.githubusercontent.com/43894249/103833890-e677d080-5036-11eb-92ff-a4075d5df7b5.png)

**Additional context**
- However, previously it was working fine. I am encountering this issue only from yesterday. 
- I did have updated BCContainerHelper to version 1.0.18 prior to this issue. I am not sure if BCConatinerHelper Update is causing the issue. 
- Anybody encounters the same issue?

**Comment by freddydk** [comment] 2021-01-07 04:51
Depends on what you were running before.
BcContainerHelper creates all sandbox images as multitenant.
You need to specify "tenant": "default" in launch.json - is that present?

**Comment by BSSIRajbir** [comment] 2021-01-07 07:04
@freddydk Now I have specified the tenant:"default" in the launch.json and it did compile perfectly.(Thanks)

But  when I directly try to login to the container it throws me the same error.

**Comment by BSSIRajbir** [comment] 2021-01-07 07:09
@freddydk  Also when I running Al-Validation it is throwing me errors on while Connection test. Like below
_Unable to run Connection test on container based on https://bcartifacts.azureedge.net/sandbox/17.2.19367.20652/nl. You can try to re-run with -skipConnectionTest.
Error is: Cannnot open Customer List page_

Do you think there can be any issue with the license key? Because I have only updated two things compare to my previous work environment. 1) BCConatinerhelper Upgrade to 1.0.18 and Updated the license file.

**Comment by freddydk** [comment] 2021-01-07 07:20
What URL are you using to login to the Web Client?
The one created on the desktop will have a ?tenant=default - that is probably what you are missing.

Typically RunConnectionTest fails due to partners having a very intrusive license dialog popping up when people connect.
In validation, this means that the app will be flagged for manual validation and will be delayed a few extra days.
Recommendation is to have your app behave nicely and use notifications to indicate that the user should register.

**Comment by BSSIRajbir** [comment] 2021-01-07 07:30
Yes, I am using Web client and I have put ?tenant=default and it worked fine. (Thanks)

The License file was about to expire though and it was throwing the warning message that Your License is about to expire in 9 days. So, if understand correctly because of the License expiration warning message, connection test was getting failed.

**Comment by freddydk** [comment] 2021-01-07 07:55
If the license file expiration dialog pops up in the web client, that might cause the problem.
I will check this and make sure that if this is the issue, then it gets resolved.

**Comment by BSSIRajbir** [comment] 2021-01-07 17:44
@freddydk  Just for the information, might it be helpful to know the root cause. We have exact two apps, only difference is region we support.  Locally, When I run Al-Validation, It fails for connection test for both apps, however, when we publish to Microsoft, one takes less time for approval and the other one takes more. I am trying to figure out why it is happening.

**Comment by ti-jalopez** [comment] 2021-02-09 21:51
@freddydk, I have the same issue, but with BC17.4 sandbox environment.
There is a strange behavior, because on Windows Server 2019 and my laptop with windows 10 fails, but others collegues don't have the problem.
Maybe the problem is caused by windows version or bccontainer helper.
I'll try to get the origin of the problem and I'tell you more information.

**Comment by freddydk** [comment] 2021-02-09 22:08
@ti-jalopez I am not sure what "same issue" means here.
Please create a new issue and include full scripts, full output, full URLs and behavior + expected behavior.

Thanks

**Comment by freddydk** [comment] 2021-02-10 11:01
I will close this issue.

@BSSIRajbir - when an app fails connectiontest we run manual validation - that can take 1-5 extra days (based on the queue)

In 2.0.5 Run-ConnectionTest has changed a bit. It opens the role center and then opens extension management.
Basically, ensuring that the app doesn't block the user from uninstalling the app again.

**Closed by freddydk** 2021-02-10 11:01 UTC
Labels: Cannot repro

**Comment by freddydk** [comment] 2022-12-11 07:35
@cscsindia - sorry, you are responding to a closed issue and with absolutely no information about what lead to this problem.
In order to get any assistance, you need to create a new issue and support enough information for people to help you.
(Script for creating container, full output and URL used for opening the WebClient would be a minimum)
