### ISSUE TITLE
Error Get-TestsFromNavContainer NavContainerHelper > 0.6.4.27

### ISSUE THREAD

**Issue by pmoison** [microsoft/navcontainerhelper#878] opened 2020-02-26 10:14 UTC
I have updated NavContainerHelper in version 0.6.4.30.
Now, when I run Get-TestsFromNavContainer I got this error : 

The property 'Tests' cannot be found on this object. Verify that the property exists and can be set.
at Get-Tests, C:\ProgramData\NavContainerHelper\Extensions\CAGCO150-Dev\PsTestTool-4\PsTestFunctions.ps1: line 218
at <ScriptBlock>, <No file>: line 51

Was working with NavContainerHelper in version 0.6.4.27.

**Comment by freddydk** [comment] 2020-02-26 14:12
If you uninstall and install 0.6.4.27 - is it then still working?

Or are you using a different image as well?
Could you provide a repro script?

**Comment by freddydk** [comment] 2020-02-27 07:43
When I run this script:
```
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
New-NavContainer `
    -accept_eula `
    -imageName mcr.microsoft.com/businesscentral/sandbox:us `
    -containerName test `
    -auth UserPassword `
    -Credential $credential `
    -updateHosts -licenseFile 'C:\temp\build.flf'
Import-TestToolkitToBCContainer test -credential $credential
# Open client and import tests
Get-TestsFromBCContainer test -credential $credential
```
Then I get
```
Tests                                                                                                                                                                                            Name                          
-----                                                                                                                                                                                            ----                          
{WarmupInvoicePosting}                                                                                                                                                                           Sys. Warmup Scenarios         
{T001_SecondSubscriberCannotSubscribeOfficially, T002_FirstUnofficialSubscriberGetsSkipped, T003_FirstOfficialSecondUnofficialSubscriber, T004_TestOfficialSubscribers...}                       Error Message Handling        
{T001_PostingDateIsInNotAllowedPeriodInGLSetup, T002_PostingDateIsInNotAllowedPeriodInUserSetup, T900_PreviewWithOneLoggedAndOneDirectError, T940_BatchPostingWithOneLoggedAndOneDirectError...} Sales Document Posting Errors 
{T001_PostingDateIsInNotAllowedPeriodInGLSetup, T002_PostingDateIsInNotAllowedPeriodInUserSetup, T900_PreviewWithOneLoggedAndOneDirectError, T940_BatchPostingWithOneLoggedAndOneDirectError...} Purch. Document Posting Errors
```
I need more info about which container, isolation, authentication etc. etc. etc.

I will close this.

Please provide script which was used to create the container and repro the error including the full output of these script if I am to investigate further.

**Closed by freddydk** 2020-02-27 07:43 UTC
Labels: Need more info

**Comment by pmoison** [comment] 2020-02-27 08:53
For the container :
isolation is Process
authentication is UserPassword

The error occurs for the 2nd command when I run at least 2 times the Get-TestsFormNavContainer and for the first App, no test codeunit in the App : 
$Tests = Get-TestsFromNavContainer @Parameters -containerName $ContainerName -ignoreGroups -testSuite $TestSuite -extensionId $AppId1
$Tests = Get-TestsFromNavContainer @Parameters -containerName $ContainerName -ignoreGroups -testSuite $TestSuite -extensionId $AppId2

With $AppId1, no test codeunit in the App
Error occurs at the 2nd command : 
The property 'Tests' cannot be found on this object. Verify that the property exists and can be set.
at Get-Tests, C:\ProgramData\NavContainerHelper\Extensions\CAGCO150-Dev\PsTestTool-4\PsTestFunctions.ps1: line 219
at <ScriptBlock>, <No file>: line 51

If I run at least 2 times for App with test codeunits, no error occurs

**Comment by freddydk** [comment] 2020-02-27 10:01
I am sorry, but this isn't enough information still.
You need to provide repro steps, scripts AND output - I will spend hours and hours trying to repro this without knowing which app, which image version which platform etc etc.

**Comment by pmoison** [comment] 2020-02-27 10:28
Repro steps :

Use NavContainerHelper version higher than 0.6.4.27

Create container with following commands (replace $LicenseFile and $ContainerName with adated values) :

$LicenseFile = "D365BC-V15-DEV-License.flf"
$ContainerName = "BC150" 
$ContainerImageName = "mcr.microsoft.com/businesscentral/onprem:1910-cu2-fr" 
$Auth = "UserPassword" # Authentification NavUserPassword
$User = "sa" 
$Password = "sa" 


$Credential = (New-Object System.Management.Automation.PSCredential ($User, (ConvertTo-SecureString $Password -AsPlainText -Force))) 
$Parameters = @{
	"Accept_Eula" = $true
	"Accept_Outdated" = $true
}
if ($LicenseFile -ne "") { $Parameters += @{"licensefile" = "$LicenseFile"  } }
$IncludeCSide = $false
$EnableSymbolLoading = $false
$DoNotUseRuntimePackages = $true
$DoNotExportObjectsToText = $true
$IncludeTestToolkit  = $true
$IncludeTestLibrariesOnly = $true
$MemoryLimit = "8G"

New-NavContainer @parameters `
	-doNotCheckHealth `
	-containerName $ContainerName `
	-imageName $ContainerImageName `
	-auth $Auth `
	-Credential $Credential `
	-updateHosts `
	-includeCSide:$IncludeCSide `
	-memoryLimit $MemoryLimit `
	-doNotExportObjectsToText:$DoNotExportObjectsToText `
	-enableSymbolLoading:$EnableSymbolLoading `
	-includeTestToolkit:$IncludeTestToolkit `
        -includeTestLibrariesOnly:$IncludeTestLibrariesOnly `
        -doNotUseRuntimePackages:$DoNotUseRuntimePackages `
	-isolation process -useBestContainerOS -includeAL

Create one App with no test codeunit. Publish, Sync, Install in the container. 
Create one App with at least one test codeunit. Publish, Sync, Install in the container.

Run the folowing commands (replace $AppId1 value with id of the first App created with no test condeunit, replace $AppId2 value with id of the second App created with at least one test condeunit ) :

$Parameters = @{}
if ($User -ne "") { $Parameters += @{"credential" = (New-Object System.Management.Automation.PSCredential ($User, (ConvertTo-SecureString $Password -AsPlainText -Force)))}}

$Tests = Get-TestsFromNavContainer @parameters -containerName $ContainerName -ignoreGroups -testSuite $TestSuite -extensionId $AppId1

$Tests = Get-TestsFromNavContainer @parameters -containerName $ContainerName -ignoreGroups -testSuite $TestSuite -extensionId $AppId2

Output :
The property 'Tests' cannot be found on this object. Verify that the property exists and can be set.
at Get-Tests, C:\ProgramData\NavContainerHelper\Extensions\BC150\PsTestTool-4\PsTestFunctions.ps1: line 219
at <ScriptBlock>, <No file>: line 51
The property 'Tests' cannot be found on this object. Verify that the property exists and can be set.
Au caractère C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.30\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 : 13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

**Comment by freddydk** [comment] 2020-02-27 10:42
You still didn't provide the output of the container creation, and you need to mark the script above as code (in the toolbar) - then I can actually see the code formatted correctly.

I really really really want to help - but there has been no change to anything in the test runner since 0.6.4.27 - so I really have a hard time believing that this is caused by containerhelper changes.

This means that I probably won't be able to repro this unless I have exactly what you have.

Reading the text again, you are trying to get tests from an app without test codeunits - now that might be that that is an error. But that would not have anything to do with the version of containerhelper. If you comment out the line getting tests from app1 (which doesn't contain any tests) does it work then?

**Comment by pmoison** [comment] 2020-02-27 10:48
As explained before the error didn't occur on the first line, but on the second one.
If I run just the second one, no error, if i run 2 times the second one, no error.
I will format the script

**Comment by freddydk** [comment] 2020-02-27 11:04
So, if you run the first line using F8 in ISE - it works = empty result.
Then you run the second line using F8 in ISE - it fails.
If you run the first line twice - it works.
If you run the second line twice - it works.

And you have tried to uninstall navcontainerhelper and install navcontainerhelper 0.6.4.27 - and see that it actually works there?
BTW - I also asked for the output of the scripts - cannot do much without that.

**Comment by pmoison** [comment] 2020-02-27 11:04
I formated the scripts and provided container creation output.

The cause of issue looks like more a variable context initialisation omission than a plateform or system related context.

**Comment by freddydk** [comment] 2020-02-27 11:06
Thanks

**Comment by pmoison** [comment] 2020-02-27 11:14
Yes, if I run the first line with F8 = works
Yes, if I run the second one with F8 = fails
Yes, if I run the first one twice with F8 = fails
No, If I run the the second one twice with F8 (after running before the first one at least one time before), the first run fails, the second one works

**Comment by pmoison** [comment] 2020-02-27 11:41
If I downgrade NavContainerHelper to 0.6.4.27 and recreate the container, I have the same issue.
So the cause of the issue seems to be older.
