### ISSUE TITLE
Run-TestsInBCContainer failing with "Cannot open page 130455."

### ISSUE THREAD

**Issue by NAVRockClimber** [microsoft/navcontainerhelper#835] opened 2020-02-06 13:45 UTC
Hi Freddy,

currently Run-TestsInBCContainer and Get-TestsFromBCContainer are throwing the following error if the container runs in hyperv mode.

```
Cannot open page 130455. You might need to import the test toolkit to the
container and/or remove the folder
C:\ProgramData\NavContainerHelper\Extensions\BuildTest\PsTestTool-4 and retry.
You might also have URL or Company name wrong.
At C:\ProgramData\NavContainerHelper\Extensions\BuildTest\PsTestTool-4\PsTestFu
nctions.ps1:154 char:9
+         throw "Cannot open page $testPage. You might need to import t ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot open pag...any name wr
   ong.:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot open page 130455. You might need to impor
   t the test toolkit to the container and/or remove the folder C:\ProgramDat
  a\NavContainerHelper\Extensions\BuildTest\PsTestTool-4 and retry. You migh
 t also have URL or Company name wrong.
```

In process isolation I just get an empty file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<assemblies />
```

I just discovered by accident due to I had to switch from process isolation to hyperv isolation that our pipelines just spit out empty test result files. (My bad, I should not just test for a failing powershell command.) For further investigaten I set up a container and followed the steps from your blog-post: https://freddysblog.com/2019/10/22/running-tests-in-containers-2/

Step 1: 

```Powershell
$credential = ([PSCredential]::new("admin", (ConvertTo-SecureString -String "P@ssw0rd" -AsPlainText -Force)))
New-BCContainer -accept_eula -accept_outdated -containerName BuildTest -imageName mcr.microsoft.com/businesscentral/onprem:1910-rtm-w1 -licenseFile 'C:\Docker\Volumes\BC15\License\German Developer License Business Central 15.flf' -updateHosts -alwaysPull -assignPremiumPlan -includeAL -auth NavUserPassword -isolation hyperv -includeTestToolkit -Credential $credential -includeTestLibrariesOnly
```

Step 2: Publish and Install the packages from your hello world example.

Do not wrap the command in loop like in your example. I just use the codeunit from your hello world example directly.

Step 3:

```Powershell
Run-TestsInBCContainer `
         -containerName $containerName `
         -credential $credential `
         -detailed `
         -XUnitResultFileName $xunitResultsFile `
         -testCodeunit 50133
```

Depending on the isolation you get either the error above or an empty result file.

I am using navcontainerhelper:

```
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
0.6.4.25   navcontainerhelper                  PSGallery            PowerShell module
```

Has something changed and I missed it or am I doing something wrong?
I can open the test pages in the web client and run the tests manually. Sepcifying a test page does not seem to make a diffenence.

Best regards

**Comment by freddydk** [comment] 2020-02-21 10:06
Duplicate of #858 - fix ready

**Closed by freddydk** 2020-02-21 10:06 UTC
Labels: Fix Ready, Under investigation, duplicate
