### ISSUE TITLE
New-NavContainer fails on Windows 10

### ISSUE THREAD

**Issue by megel** [microsoft/navcontainerhelper#598] opened 2019-09-03 05:30 UTC
Don't know the reason, since 2 days I get on my desktop computer (Windows 10) this error, when I try to create a new container with `New-NAVContainer`:

```
PS C:\Users\user> New-NavContainer -containerName navserver -imageName "mcr.microsoft.com/businesscentral/onprem:w1-ltsc2019" -accept_eula
NavContainerHelper is version 0.6.3.2
Host is Microsoft Windows 10 Pro - ltsc2019
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image mcr.microsoft.com/businesscentral/onprem:w1-ltsc2019
Removing C:\ProgramData\NavContainerHelper\Extensions\navserver
Creating Container navserver
Version: 14.4.35602.0-W1
Platform: 14.0.35570.0
Generic Tag: 0.0.9.92
Container OS Version: 10.0.17763.678 (ltsc2019)
Host OS Version: 10.0.17763.678 (ltsc2019)
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\navserver\my:
- MainLoop.ps1
Creating container navserver from image mcr.microsoft.com/businesscentral/onprem:w1-ltsc2019
87fdf28e61ea58f2d4d696f6eebebe79eb3b26cfb516cfc0aa95d769ce219c34
DockerDo : docker.exe: Error response from daemon: container
87fdf28e61ea58f2d4d696f6eebebe79eb3b26cfb516cfc0aa95d769ce219c34 encountered an error during Start: failure in a
Windows system call: Der virtuelle Computer oder Container wurde unerwartet beendet. (0xc0370106).
ExitCode: 125
Commandline: docker run --name navserver --hostname navserver --env auth=Windows --env username="myusername" --env
ExitOnError=N --env locale=en-US --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume
"C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume
"C:\ProgramData\NavContainerHelper\Extensions\navserver\my:C:\Run\my" --isolation process --restart unless-stopped
--env enableApiServices=Y --env useSSL=N --env securePassword=76492d1116223f0423413b16050a5345MgB8AHMAWgBEAEoARwBMAGUAS
gBFAFYAQQByADAATwBsAGsAaAArADYAdQB0AHcAPQA9AHwANertwIAYgBiAGUANQA2AGUAZAAwADEAYwBiAGEAOAAzADIAZQBiADAANABhADgANwBiAGIA
YQA4AGUANAAzAGEasdw5ADMAYQBmAGMAYgA4ADgANgAzADAAOQBkADEAMwAwADkAMwAwADcAMQA3ADIAMgBiADMAMwA4AGQAMwA= --env
passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --detach
mcr.microsoft.com/businesscentral/onprem:w1-ltsc2019
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.2\ContainerHandling\New-NavContainer.ps1:1078
Zeichen:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
```

Docker Version is:
![image](https://user-images.githubusercontent.com/15800069/64146242-7b076880-ce1c-11e9-8454-9d26933e3f14.png)

**Comment by freddydk** [comment] 2019-09-03 05:35
What does Docker ps -a return?
Did you try to reset to factory defaults on docker?

**Comment by megel** [comment] 2019-09-03 20:59
![image](https://user-images.githubusercontent.com/15800069/64206591-01628f80-ce9b-11e9-98bd-9349fbffa962.png)
![image](https://user-images.githubusercontent.com/15800069/64206602-117a6f00-ce9b-11e9-9fa8-404fb602fb7a.png)
Docker mode is also set to "Windows Container" :/

Same error after reset to default:
![image](https://user-images.githubusercontent.com/15800069/64208143-7aafb180-ce9e-11e9-816c-90fac5581a38.png)

**Comment by freddydk** [comment] 2019-09-03 21:24
ExitCode 125 means that docker run fails and unfortunately, there can be a lot of reasons why. Mostly this is version mismatches (doesn't seem to be the case here), virus scanner problems or shares that doesn't work.
You could try basic troubleshooting to see if you can run a basic windowsserver image.
Alternatively, you can uninstall and reinstall docker - the problem is normally unrelated to the NAV / business central containers.

**Comment by freddydk** [comment] 2019-10-04 02:24
Closing this as there is nothing really I can do about this.
Please reopen with additional info if you discover something new.

**Closed by freddydk** 2019-10-04 02:24 UTC
Labels: Cannot repro, Unrelated to navcontainerhelper
