### ISSUE TITLE
Windows User name Limit

### ISSUE THREAD

**Issue by thomasbook** [Microsoft/navcontainerhelper#181] opened 2018-08-12 00:18 UTC
The Window User I have is User.Name@SomeCompany-New.com seem to be too long....

Cannot validate argument on parameter 'Name'. The character length of the 28 argument is too long. Shorten the character length of the argument so it is fewer than
 or equal to "20" characters, and then try the command again.
at <ScriptBlock>, C:\Run\SetupWindowsUsers.ps1: line 11
at <ScriptBlock>, C:\Run\navstart.ps1: line 154
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1
Initialization of container dyn-sandbox failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.0.2\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...-sandbox failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container dyn-sandbox failed

**Comment by freddydk** [comment] 2018-08-13 11:31
Duplicate of this: https://github.com/Microsoft/nav-docker/issues/241

**Comment by thomasbook** [comment] 2018-08-13 16:07
Looking at the BC tables the field length in them has not changed for this, it's not always possible to use NAV User and Password or to make the window user name shorter.

**Comment by freddydk** [comment] 2018-08-13 20:37
Correct, but then you will have to setup GMSA.
The thing that is failing here is the attempt to create a windows user in the container with the same name as the windows user on the host.
New-localuser limits the length – nothing I can do about that, and I cannot get Windows Auth to work without GMSA without a local windows user in the container.

/Freddy

**Comment by freddydk** [comment] 2018-08-30 19:25
The username provided in credentials for the container should be the local username - not the microsoft account setup for login with this user.

**Closed by freddydk** 2018-08-30 19:25 UTC
Labels: Under investigation, duplicate
