### ISSUE TITLE
GenerateBcNuGet packageIdTemplate: {publisher}.{name}.{id}

### ISSUE THREAD

**Issue by Arthurvdv** [microsoft/navcontainerhelper#3349] opened 2024-02-20 15:10 UTC
**Describe the issue**
The default value of the packageIdTemplate on the GenerateNuGetPackages.ps1 doesn't seems to work with the GenerateBcNuGet function of the BCCH.

**Scripts used to create container and cause the issue**
https://github.com/VanRoey/GenerateBcNuGet/actions/runs/7975477117/job/21773795948.

```
env:
  nuGetToken: ***
  nuGetServerUrl: ***/_packaging/BusinessCentral/nuget/v3/index.json
  apps: ***
  symbolsOnly: 
  packageIdTemplate: {publisher}.{name}.{id}
```

The packageIdTemplate is set in the env variables

```
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>VanRoey.***.b561d731-1e39-4bf4-a2ea-a162f3ab38a8</id>
        <version>22.0.129063.0</version>
        <title>***</title>
        <description>***</description>
        <authors>VanRoey</authors>
        <dependencies>
            <dependency id="Microsoft.Application" version="22.0.0.0" />
            <dependency id="Microsoft.Platform" version="1.0.0.0" />
        </dependencies>
    </metadata>
    <files>
        <file src="115f5598-f6e3-4dac-888d-f320f2f4c87e.app" target="115f5598-f6e3-4dac-888d-f320f2f4c87e.app" />
    </files>
</package>
```

But the package file src/target doesn't match the `{publisher}.{name}.{id}` format.

**Full output of scripts**
```
2024-02-20T14:58:26.4976899Z Requested labels: ubuntu-latest
2024-02-20T14:58:26.4977187Z Job defined at: VanRoey/GenerateBcNuGet/.github/workflows/generateNuGet.yml@refs/heads/main
2024-02-20T14:58:26.4977299Z Waiting for a runner to pick up this job...
2024-02-20T14:58:26.9731933Z Job is waiting for a hosted runner to come online.
2024-02-20T14:58:30.2836334Z Job is about to start running on the hosted runner: GitHub Actions 4 (hosted)
2024-02-20T14:58:33.7565458Z Current runner version: '2.313.0'
2024-02-20T14:58:33.7588848Z ##[group]Operating System
2024-02-20T14:58:33.7589545Z Ubuntu
2024-02-20T14:58:33.7590031Z 22.04.3
2024-02-20T14:58:33.7590381Z LTS
2024-02-20T14:58:33.7590821Z ##[endgroup]
2024-02-20T14:58:33.7591232Z ##[group]Runner Image
2024-02-20T14:58:33.7591749Z Image: ubuntu-22.04
2024-02-20T14:58:33.7592241Z Version: 20240212.1.0
2024-02-20T14:58:33.7593292Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240212.1/images/ubuntu/Ubuntu2204-Readme.md
2024-02-20T14:58:33.7594868Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240212.1
2024-02-20T14:58:33.7595776Z ##[endgroup]
2024-02-20T14:58:33.7596226Z ##[group]Runner Image Provisioner
2024-02-20T14:58:33.7596792Z 2.0.341.1
2024-02-20T14:58:33.7597168Z ##[endgroup]
2024-02-20T14:58:33.7599456Z ##[group]GITHUB_TOKEN Permissions
2024-02-20T14:58:33.7601131Z Actions: write
2024-02-20T14:58:33.7601692Z Checks: write
2024-02-20T14:58:33.7602294Z Contents: write
2024-02-20T14:58:33.7603238Z Deployments: write
2024-02-20T14:58:33.7603724Z Discussions: write
2024-02-20T14:58:33.7604252Z Issues: write
2024-02-20T14:58:33.7604660Z Metadata: read
2024-02-20T14:58:33.7605063Z Packages: write
2024-02-20T14:58:33.7605554Z Pages: write
2024-02-20T14:58:33.7605953Z PullRequests: write
2024-02-20T14:58:33.7606412Z RepositoryProjects: write
2024-02-20T14:58:33.7606973Z SecurityEvents: write
2024-02-20T14:58:33.7607423Z Statuses: write
2024-02-20T14:58:33.7607902Z ##[endgroup]
2024-02-20T14:58:33.7611003Z Secret source: Actions
2024-02-20T14:58:33.7611631Z Prepare workflow directory
2024-02-20T14:58:33.8235873Z Prepare all required actions
2024-02-20T14:58:33.8395415Z Getting action download info
2024-02-20T14:58:34.0504808Z Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
2024-02-20T14:58:34.2692349Z Complete job name: Generate NuGet Packages
2024-02-20T14:58:34.3587698Z ##[group]Run actions/checkout@v3
2024-02-20T14:58:34.3588488Z with:
2024-02-20T14:58:34.3588944Z   repository: VanRoey/GenerateBcNuGet
2024-02-20T14:58:34.3589860Z   token: ***
2024-02-20T14:58:34.3590309Z   ssh-strict: true
2024-02-20T14:58:34.3590785Z   persist-credentials: true
2024-02-20T14:58:34.3591395Z   clean: true
2024-02-20T14:58:34.3591854Z   sparse-checkout-cone-mode: true
2024-02-20T14:58:34.3592473Z   fetch-depth: 1
2024-02-20T14:58:34.3592911Z   fetch-tags: false
2024-02-20T14:58:34.3593337Z   lfs: false
2024-02-20T14:58:34.3593812Z   submodules: false
2024-02-20T14:58:34.3594261Z   set-safe-directory: true
2024-02-20T14:58:34.3594773Z ##[endgroup]
2024-02-20T14:58:34.5504731Z Syncing repository: VanRoey/GenerateBcNuGet
2024-02-20T14:58:34.5506890Z ##[group]Getting Git version info
2024-02-20T14:58:34.5507906Z Working directory is '/home/runner/work/GenerateBcNuGet/GenerateBcNuGet'
2024-02-20T14:58:34.5509224Z [command]/usr/bin/git version
2024-02-20T14:58:34.5523231Z git version 2.43.0
2024-02-20T14:58:34.5546524Z ##[endgroup]
2024-02-20T14:58:34.5562095Z Temporarily overriding HOME='/home/runner/work/_temp/8cddebee-c347-4e84-85e3-db4fa2cfa94b' before making global git config changes
2024-02-20T14:58:34.5564702Z Adding repository directory to the temporary git global config as a safe directory
2024-02-20T14:58:34.5567185Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/GenerateBcNuGet/GenerateBcNuGet
2024-02-20T14:58:34.5611044Z Deleting the contents of '/home/runner/work/GenerateBcNuGet/GenerateBcNuGet'
2024-02-20T14:58:34.5614666Z ##[group]Initializing the repository
2024-02-20T14:58:34.5618018Z [command]/usr/bin/git init /home/runner/work/GenerateBcNuGet/GenerateBcNuGet
2024-02-20T14:58:34.5687981Z hint: Using 'master' as the name for the initial branch. This default branch name
2024-02-20T14:58:34.5689886Z hint: is subject to change. To configure the initial branch name to use in all
2024-02-20T14:58:34.5691613Z hint: of your new repositories, which will suppress this warning, call:
2024-02-20T14:58:34.5692922Z hint: 
2024-02-20T14:58:34.5694390Z hint: 	git config --global init.defaultBranch <name>
2024-02-20T14:58:34.5695719Z hint: 
2024-02-20T14:58:34.5696909Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2024-02-20T14:58:34.5699145Z hint: 'development'. The just-created branch can be renamed via this command:
2024-02-20T14:58:34.5700455Z hint: 
2024-02-20T14:58:34.5701305Z hint: 	git branch -m <name>
2024-02-20T14:58:34.5702706Z Initialized empty Git repository in /home/runner/work/GenerateBcNuGet/GenerateBcNuGet/.git/
2024-02-20T14:58:34.5711778Z [command]/usr/bin/git remote add origin https://github.com/VanRoey/GenerateBcNuGet
2024-02-20T14:58:34.5752223Z ##[endgroup]
2024-02-20T14:58:34.5753062Z ##[group]Disabling automatic garbage collection
2024-02-20T14:58:34.5755497Z [command]/usr/bin/git config --local gc.auto 0
2024-02-20T14:58:34.5795040Z ##[endgroup]
2024-02-20T14:58:34.5795864Z ##[group]Setting up auth
2024-02-20T14:58:34.5800885Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-02-20T14:58:34.5838457Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-02-20T14:58:34.6200906Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-02-20T14:58:34.6238716Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-02-20T14:58:34.6485964Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2024-02-20T14:58:34.6528369Z ##[endgroup]
2024-02-20T14:58:34.6529409Z ##[group]Fetching the repository
2024-02-20T14:58:34.6537048Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +da9cb7d4f39272c757a7e6e92c54bcbe5d515dba:refs/remotes/origin/main
2024-02-20T14:58:35.0504577Z remote: Enumerating objects: 14, done.        
2024-02-20T14:58:35.0506330Z remote: Counting objects:   7% (1/14)        
2024-02-20T14:58:35.0507694Z remote: Counting objects:  14% (2/14)        
2024-02-20T14:58:35.0508992Z remote: Counting objects:  21% (3/14)        
2024-02-20T14:58:35.0509958Z remote: Counting objects:  28% (4/14)        
2024-02-20T14:58:35.0510813Z remote: Counting objects:  35% (5/14)        
2024-02-20T14:58:35.0511711Z remote: Counting objects:  42% (6/14)        
2024-02-20T14:58:35.0512495Z remote: Counting objects:  50% (7/14)        
2024-02-20T14:58:35.0513295Z remote: Counting objects:  57% (8/14)        
2024-02-20T14:58:35.0514030Z remote: Counting objects:  64% (9/14)        
2024-02-20T14:58:35.0514684Z remote: Counting objects:  71% (10/14)        
2024-02-20T14:58:35.0515417Z remote: Counting objects:  78% (11/14)        
2024-02-20T14:58:35.0516056Z remote: Counting objects:  85% (12/14)        
2024-02-20T14:58:35.0516719Z remote: Counting objects:  92% (13/14)        
2024-02-20T14:58:35.0517406Z remote: Counting objects: 100% (14/14)        
2024-02-20T14:58:35.0518136Z remote: Counting objects: 100% (14/14), done.        
2024-02-20T14:58:35.0518932Z remote: Compressing objects:   7% (1/13)        
2024-02-20T14:58:35.0519632Z remote: Compressing objects:  15% (2/13)        
2024-02-20T14:58:35.0520299Z remote: Compressing objects:  23% (3/13)        
2024-02-20T14:58:35.0521014Z remote: Compressing objects:  30% (4/13)        
2024-02-20T14:58:35.0521682Z remote: Compressing objects:  38% (5/13)        
2024-02-20T14:58:35.0522331Z remote: Compressing objects:  46% (6/13)        
2024-02-20T14:58:35.0523427Z remote: Compressing objects:  53% (7/13)        
2024-02-20T14:58:35.0524095Z remote: Compressing objects:  61% (8/13)        
2024-02-20T14:58:35.0524883Z remote: Compressing objects:  69% (9/13)        
2024-02-20T14:58:35.0859504Z remote: Compressing objects:  76% (10/13)        
2024-02-20T14:58:35.0860832Z remote: Compressing objects:  84% (11/13)        
2024-02-20T14:58:35.0861562Z remote: Compressing objects:  92% (12/13)        
2024-02-20T14:58:35.0862223Z remote: Compressing objects: 100% (13/13)        
2024-02-20T14:58:35.0863024Z remote: Compressing objects: 100% (13/13), done.        
2024-02-20T14:58:35.1075874Z remote: Total 14 (delta 2), reused 3 (delta 0), pack-reused 0        
2024-02-20T14:58:35.1129727Z From https://github.com/VanRoey/GenerateBcNuGet
2024-02-20T14:58:35.1131356Z  * [new ref]         da9cb7d4f39272c757a7e6e92c54bcbe5d515dba -> origin/main
2024-02-20T14:58:35.1158791Z ##[endgroup]
2024-02-20T14:58:35.1159844Z ##[group]Determining the checkout info
2024-02-20T14:58:35.1161147Z ##[endgroup]
2024-02-20T14:58:35.1162065Z ##[group]Checking out the ref
2024-02-20T14:58:35.1165817Z [command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
2024-02-20T14:58:35.1222092Z Switched to a new branch 'main'
2024-02-20T14:58:35.1223920Z branch 'main' set up to track 'origin/main'.
2024-02-20T14:58:35.1229780Z ##[endgroup]
2024-02-20T14:58:35.1271848Z [command]/usr/bin/git log -1 --format='%H'
2024-02-20T14:58:35.1303686Z 'da9cb7d4f39272c757a7e6e92c54bcbe5d515dba'
2024-02-20T14:58:35.1672056Z ##[group]Run . (Join-Path $env:GITHUB_WORKSPACE "MaskInput.ps1")
2024-02-20T14:58:35.1673108Z [36;1m. (Join-Path $env:GITHUB_WORKSPACE "MaskInput.ps1")[0m
2024-02-20T14:58:35.1753434Z shell: /usr/bin/pwsh -command ". '{0}'"
2024-02-20T14:58:35.1754055Z env:
2024-02-20T14:58:35.1757242Z   secrets: {
  "AUTOCREATED_129063_1": "***",
  "AUTOCREATED_125898_2": "***",
  "github_token": "***",
  "NUGETSERVERURL": " ***",
  "AUTOCREATED_129063_2": "***",
  "AUTOCREATED_129063_4": "***",
  "AUTOCREATED_129063_3": "***"
}
2024-02-20T14:58:35.1758757Z ##[endgroup]
2024-02-20T14:58:36.4121343Z ##[group]Run . (Join-Path $env:GITHUB_WORKSPACE "GenerateNuGetPackages.ps1")
2024-02-20T14:58:36.4122262Z [36;1m. (Join-Path $env:GITHUB_WORKSPACE "GenerateNuGetPackages.ps1")[0m
2024-02-20T14:58:36.4188442Z shell: /usr/bin/pwsh -command ". '{0}'"
2024-02-20T14:58:36.4188970Z env:
2024-02-20T14:58:36.4189753Z   nuGetToken: ***
2024-02-20T14:58:36.4190638Z   nuGetServerUrl: ***/_packaging/BusinessCentral/nuget/v3/index.json
2024-02-20T14:58:36.4192847Z   apps: ***
2024-02-20T14:58:36.4193273Z   symbolsOnly: 
2024-02-20T14:58:36.4193718Z   packageIdTemplate: {publisher}.{name}.{id}
2024-02-20T14:58:36.4194295Z ##[endgroup]
2024-02-20T14:58:37.1565365Z Generate Runtime NuGet Packages
2024-02-20T14:58:37.1684754Z Downloading BcContainerHelper developer version from https://bccontainerhelper.blob.core.windows.net/public/preview.zip
2024-02-20T14:58:40.2036515Z BcContainerHelper version 6.0.7-preview1139
2024-02-20T14:58:40.8428494Z BC.HelperFunctions emits usage statistics telemetry to Microsoft
2024-02-20T14:58:40.8806810Z Running on Linux
2024-02-20T14:58:41.6508634Z Downloading /tmp/115f5598-f6e3-4dac-888d-f320f2f4c87e
2024-02-20T14:58:41.6594134Z Downloading using HttpClient
2024-02-20T14:58:43.3481655Z Downloading AL Language Extension (Prerelease) to /home/runner/.bccontainerhelper/alLanguageExtension/13.0.937154.zip
2024-02-20T14:58:43.3483981Z Downloading using HttpClient
2024-02-20T14:58:45.4390207Z using Expand-Archive
2024-02-20T14:58:50.1951395Z Setting execute permissions on altool
2024-02-20T14:58:50.7319602Z Search NuGetFeed ***/_packaging/BusinessCentral/nuget/v3/index.json
2024-02-20T14:58:50.9451902Z Search package using ***/_packaging/82099a1a-fe04-4c03-9594-3ab7937dc1df/nuget/v3/query2/?q=b561d731-1e39-4bf4-a2ea-a162f3ab38a8&take=50
2024-02-20T14:58:51.2126211Z 1 matching packages found
2024-02-20T14:58:51.2129286Z - VanRoey.***.b561d731-1e39-4bf4-a2ea-a162f3ab38a8
2024-02-20T14:58:51.2155248Z PackageId: VanRoey.***.b561d731-1e39-4bf4-a2ea-a162f3ab38a8
2024-02-20T14:58:51.2247930Z 1 versions found
2024-02-20T14:58:51.2271189Z First version is 22.0.128364
2024-02-20T14:58:51.2281808Z Last version is 22.0.128364
2024-02-20T14:58:51.2368521Z No package found matching version '22.0.129063.0' for package id VanRoey.***.b561d731-1e39-4bf4-a2ea-a162f3ab38a8
2024-02-20T14:58:51.2376706Z No package found matching package name b561d731-1e39-4bf4-a2ea-a162f3ab38a8 Version 22.0.129063.0
2024-02-20T14:58:51.2408157Z '/tmp/e556facb-99f4-469f-91bc-32d6c5fccc08/115f5598-f6e3-4dac-888d-f320f2f4c87e.app'
2024-02-20T14:58:51.2414900Z System.String
2024-02-20T14:58:51.2516294Z Create NuGet package
2024-02-20T14:58:51.2517154Z AppFile:
2024-02-20T14:58:51.2518795Z /tmp/e556facb-99f4-469f-91bc-32d6c5fccc08/115f5598-f6e3-4dac-888d-f320f2f4c87e.app
2024-02-20T14:58:51.2564992Z Setting execute permissions on altool
2024-02-20T14:58:51.7878610Z NUSPEC file:
2024-02-20T14:58:51.7913800Z <?xml version="1.0" encoding="utf-8"?>
2024-02-20T14:58:51.7915139Z <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
2024-02-20T14:58:51.7916420Z     <metadata>
2024-02-20T14:58:51.7917819Z         <id>VanRoey.***.b561d731-1e39-4bf4-a2ea-a162f3ab38a8</id>
2024-02-20T14:58:51.7918896Z         <version>22.0.129063.0</version>
2024-02-20T14:58:51.7919979Z         <title>***</title>
2024-02-20T14:58:51.7921368Z         <description>***</description>
2024-02-20T14:58:51.7922422Z         <authors>VanRoey</authors>
2024-02-20T14:58:51.7923472Z         <dependencies>
2024-02-20T14:58:51.7924512Z             <dependency id="Microsoft.Application" version="22.0.0.0" />
2024-02-20T14:58:51.7925841Z             <dependency id="Microsoft.Platform" version="1.0.0.0" />
2024-02-20T14:58:51.7926878Z         </dependencies>
2024-02-20T14:58:51.7927743Z     </metadata>
2024-02-20T14:58:51.7928359Z     <files>
2024-02-20T14:58:51.7929945Z         <file src="115f5598-f6e3-4dac-888d-f320f2f4c87e.app" target="115f5598-f6e3-4dac-888d-f320f2f4c87e.app" />
2024-02-20T14:58:51.7931203Z     </files>
2024-02-20T14:58:51.7932125Z </package>
2024-02-20T14:58:51.8681634Z Successfully created NuGet package (Size: 169Kb)
2024-02-20T14:58:52.2842582Z Preparing NuGet Package for submission
2024-02-20T14:58:52.3239632Z Submitting NuGet package
2024-02-20T14:58:53.6661957Z 
2024-02-20T14:58:53.6666969Z NuGet package successfully submitted
2024-02-20T14:58:53.8063646Z Post job cleanup.
2024-02-20T14:58:53.8887664Z [command]/usr/bin/git version
2024-02-20T14:58:53.8933946Z git version 2.43.0
2024-02-20T14:58:53.8972090Z Temporarily overriding HOME='/home/runner/work/_temp/c82464ea-1603-47fd-8e4e-f7690c302250' before making global git config changes
2024-02-20T14:58:53.8973915Z Adding repository directory to the temporary git global config as a safe directory
2024-02-20T14:58:53.8977938Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/GenerateBcNuGet/GenerateBcNuGet
2024-02-20T14:58:53.9018475Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-02-20T14:58:53.9056818Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-02-20T14:58:53.9298037Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-02-20T14:58:53.9326733Z http.https://github.com/.extraheader
2024-02-20T14:58:53.9337857Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-02-20T14:58:53.9375345Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-02-20T14:58:53.9849195Z Cleaning up orphan processes
```

**Comment by freddydk** [comment] 2024-02-20 22:43
Can you elaborate on what the problem is?
this:
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/220c9ea8-0c52-461d-9d1a-f13a87cbf2af)
does look like publisher.name.appid - right???

**Comment by Arthurvdv** [comment] 2024-02-21 08:13
I may have interpreted the parameter incorrectly 🤔

I'm referencing to this part of the NUSPEC file;

```
<files>
    <file src="115f5598-f6e3-4dac-888d-f320f2f4c87e.app" target="115f5598-f6e3-4dac-888d-f320f2f4c87e.app" />
</files>
```

This is now a guid, where I'm wondering if there a possibility to have a human readable name. Like for example the way the Apps of Microsoft have `Microsoft__Exclude_APIV2__23.3.14876.15404.app` as the `file src` and `target`.

```
NUSPEC:
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>Microsoft._Exclude_APIV2_.10cb69d9-bc8a-4d27-970a-9e110e9db2a5</id>
        <version>23.3.14876.15404</version>
        <title>_Exclude_APIV2_</title>
        <description>_Exclude_APIV2_</description>
        <authors>Microsoft</authors>
        <dependencies>
            <dependency id="Microsoft.Application" version="23.3.0.0" />
            <dependency id="Microsoft.Platform" version="23.0.0.0" />
        </dependencies>
    </metadata>
    <files>
        <file src="Microsoft__Exclude_APIV2__23.3.14876.15404.app" target="Microsoft__Exclude_APIV2__23.3.14876.15404.app" />
    </files>
</package>
```

**Comment by freddydk** [comment] 2024-02-21 09:46
Ahhh - the file section is wrong - that is a bug in GenerateBcNuGet - will fix that.

**Comment by freddydk** [comment] 2024-02-22 05:10
So, the files section should have the name of the app file you send to the workflow
Are you transferring the app as `<GUID>.app`? or are you sending the real app name?
It looks like you are sending the GUID yourself?

**Comment by Arthurvdv** [comment] 2024-02-22 08:42
We're using Azure Blob Storage with a SAS-token to transfer the file to the Github runner.

The filename itself should be `VanRoey_Finance Extension_22.0.129063.0_sandbox_23.4_base.app` in this example.

This is the step in our Azure DevOps pipeline

```yaml
- task: PowerShell@2
  displayName: 'Generate NuGet Packages'
  condition: succeeded()
  env:
    GH_TOKEN: $(generatebcnuget-github-token)
    ADO_TOKEN: $(generatebcnuget-azure-devops-token)
    APPS: $(BcArtifactFileUri)
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "* Login to Github ..."
      gh auth login

      Write-Host "Kick off 'Generate NuGet Packages' workfow on Github"
      $workflow = 'Generate NuGet Packages'
      $nuGetServerUrl = 'https://<organisation>.pkgs.visualstudio.com/_packaging/<feed>/nuget/v3/index.json'
      $nuGetToken = $env:ADO_TOKEN
      gh workflow run --repo $repo $workflow -f apps=$env:APPS -f nuGetServerUrl=$nuGetServerUrl -f nuGetToken=$nuGetToken -f run-name="$(Build.BuildId)"
```

$(BcArtifactFileUri) = https://nameofthestorageaccount.blob.core.windows.net/artifacts/VanRoey_Finance%20Extension_22.0.129063.0_sandbox_23.4_base.app?se=2024-02-20T15%3A27Z&sp=r&spr=https&sv=2022-11-02&sr=b&skoid=814bba0f-37aa-48b8-af5f-1f50ff15bf5b&sktid=792ef33d-36e5-42f2-a34c-350815e43795&skt=2024-02-20T14%3A57%3A48Z&ske=2024-02-20T15%3A27%3A00Z&sks=b&skv=2022-11-02&sig=sRfHBpBwbZFFaBzp8c%2BYTo4eAV2zXRo1rOqnsTI7JHk%3D

**Comment by freddydk** [comment] 2024-02-22 10:17
Got it - will check this path

**Closed** 2024-02-22 12:14 UTC
Labels: Cannot repro

**Comment by Arthurvdv** [comment] 2024-02-23 09:18
Thank you! This has resolved the issue and everything is now working as expected :-)
