### ISSUE TITLE
Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'

### ISSUE THREAD

**Issue by yogipatel07081992** [microsoft/navcontainerhelper#820] opened 2020-01-21 08:58 UTC
When I trying to create a new docker container on windows 10 system I'm getting the error.
I am using below power shell script for creating a docker container.

"Install-Module -Name navcontainerhelper -Force

$imageName = "mcr.microsoft.com/businesscentral/sandbox:15.2.39040.39489-ca-ltsc2019"
$containerName = "BC15CA"
$auth = "UserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'Admin@123' -AsPlainText -Force)
$licenseFile = "************************"

New-BCContainer -accept_eula `
                -alwaysPull `
                -imageName $imageName `
                -containerName $containerName `
                -auth $auth `
                -credential $credential `
                -licenseFile $licenseFile `
                -assignPremiumPlan `
                -updateHosts `
                -includeAL `
                -memoryLimit 4G
"

**Full output with an error.**

Login Succeeded
NavContainerHelper is version 0.6.4.25
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1903
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Pulling image mcr.microsoft.com/businesscentral/sandbox:15.2.39040.39489-ca-ltsc2019
15.2.39040.39489-ca-ltsc2019: Pulling from businesscentral/sandbox
65014b3c3121: Pulling fs layer
faf31ee0aa3d: Pulling fs layer
12dc3659100c: Pulling fs layer
f414e541ee3c: Pulling fs layer
8c280c670523: Pulling fs layer
45179d426cc4: Pulling fs layer
f414e541ee3c: Waiting
8c280c670523: Waiting
45179d426cc4: Waiting
ddcea2e95c2e: Pulling fs layer
ddcea2e95c2e: Waiting
5f5dad69e903: Pulling fs layer
5f5dad69e903: Waiting
5ef637fb39f3: Pulling fs layer
5ef637fb39f3: Waiting
d7d509fe501b: Pulling fs layer
d7d509fe501b: Waiting
32da2edb848e: Pulling fs layer
32da2edb848e: Waiting
0ea6a41afa6e: Pulling fs layer
fa725046e829: Pulling fs layer
0ea6a41afa6e: Waiting
fa725046e829: Waiting
40d6ced096a2: Pulling fs layer
40d6ced096a2: Waiting
b49f8afa3690: Pulling fs layer
b49f8afa3690: Waiting
3565a05d7e31: Pulling fs layer
11f9ea515e55: Pulling fs layer
3565a05d7e31: Waiting
c3297e98d816: Pulling fs layer
11f9ea515e55: Waiting
ebbd03897733: Pulling fs layer
489483f4430d: Pulling fs layer
c3297e98d816: Waiting
da6b278bacb3: Pulling fs layer
782064d60bce: Pulling fs layer
8c18a5fc5e0c: Pulling fs layer
ebbd03897733: Waiting
514885ce4d32: Pulling fs layer
489483f4430d: Waiting
da6b278bacb3: Waiting
782064d60bce: Waiting
8c18a5fc5e0c: Waiting
bab5c08db96b: Pulling fs layer
1538172e6ba2: Pulling fs layer
7159f51ce8da: Pulling fs layer
93a2da301ad6: Pulling fs layer
4e9cbbc6ef5f: Pulling fs layer
ca075a20a2c9: Pulling fs layer
0790e2377233: Pulling fs layer
6f21a51ffbb7: Pulling fs layer
63913e0eb763: Pulling fs layer
54e134c45235: Pulling fs layer
5a260f11dc0f: Pulling fs layer
94f6e6a9e60c: Pulling fs layer
bab5c08db96b: Waiting
1538172e6ba2: Waiting
7159f51ce8da: Waiting
93a2da301ad6: Waiting
4e9cbbc6ef5f: Waiting
ca075a20a2c9: Waiting
0790e2377233: Waiting
6f21a51ffbb7: Waiting
63913e0eb763: Waiting
54e134c45235: Waiting
5a260f11dc0f: Waiting
94f6e6a9e60c: Waiting
12dc3659100c: Verifying Checksum
12dc3659100c: Download complete
f414e541ee3c: Verifying Checksum
f414e541ee3c: Download complete
8c280c670523: Verifying Checksum
8c280c670523: Download complete
faf31ee0aa3d: Verifying Checksum
faf31ee0aa3d: Download complete
ddcea2e95c2e: Verifying Checksum
ddcea2e95c2e: Download complete
5f5dad69e903: Verifying Checksum
5f5dad69e903: Download complete
5ef637fb39f3: Verifying Checksum
5ef637fb39f3: Download complete
d7d509fe501b: Verifying Checksum
d7d509fe501b: Download complete
45179d426cc4: Verifying Checksum
45179d426cc4: Download complete
0ea6a41afa6e: Verifying Checksum
0ea6a41afa6e: Download complete
fa725046e829: Verifying Checksum
fa725046e829: Download complete
32da2edb848e: Verifying Checksum
32da2edb848e: Download complete
40d6ced096a2: Verifying Checksum
40d6ced096a2: Download complete
b49f8afa3690: Verifying Checksum
b49f8afa3690: Download complete
3565a05d7e31: Verifying Checksum
3565a05d7e31: Download complete
11f9ea515e55: Verifying Checksum
11f9ea515e55: Download complete
c3297e98d816: Verifying Checksum
c3297e98d816: Download complete
ebbd03897733: Verifying Checksum
ebbd03897733: Download complete
489483f4430d: Verifying Checksum
489483f4430d: Download complete
da6b278bacb3: Verifying Checksum
da6b278bacb3: Download complete
782064d60bce: Verifying Checksum
782064d60bce: Download complete
8c18a5fc5e0c: Verifying Checksum
8c18a5fc5e0c: Download complete
514885ce4d32: Verifying Checksum
514885ce4d32: Download complete
bab5c08db96b: Verifying Checksum
bab5c08db96b: Download complete
1538172e6ba2: Verifying Checksum
1538172e6ba2: Download complete
7159f51ce8da: Verifying Checksum
7159f51ce8da: Download complete
4e9cbbc6ef5f: Verifying Checksum
4e9cbbc6ef5f: Download complete
ca075a20a2c9: Verifying Checksum
ca075a20a2c9: Download complete
65014b3c3121: Verifying Checksum
65014b3c3121: Download complete
6f21a51ffbb7: Verifying Checksum
6f21a51ffbb7: Download complete
0790e2377233: Verifying Checksum
0790e2377233: Download complete
54e134c45235: Verifying Checksum
54e134c45235: Download complete
63913e0eb763: Verifying Checksum
63913e0eb763: Download complete
94f6e6a9e60c: Verifying Checksum
94f6e6a9e60c: Download complete
5a260f11dc0f: Verifying Checksum
5a260f11dc0f: Download complete
93a2da301ad6: Verifying Checksum
93a2da301ad6: Download complete
65014b3c3121: Pull complete
faf31ee0aa3d: Pull complete
12dc3659100c: Pull complete
f414e541ee3c: Pull complete
8c280c670523: Pull complete
45179d426cc4: Pull complete
ddcea2e95c2e: Pull complete
5f5dad69e903: Pull complete
5ef637fb39f3: Pull complete
d7d509fe501b: Pull complete
32da2edb848e: Pull complete
0ea6a41afa6e: Pull complete
fa725046e829: Pull complete
40d6ced096a2: Pull complete
b49f8afa3690: Pull complete
3565a05d7e31: Pull complete
11f9ea515e55: Pull complete
c3297e98d816: Pull complete
ebbd03897733: Pull complete
489483f4430d: Pull complete
da6b278bacb3: Pull complete
782064d60bce: Pull complete
8c18a5fc5e0c: Pull complete
514885ce4d32: Pull complete
bab5c08db96b: Pull complete
1538172e6ba2: Pull complete
7159f51ce8da: Pull complete
93a2da301ad6: Pull complete
4e9cbbc6ef5f: Pull complete
ca075a20a2c9: Pull complete
0790e2377233: Pull complete
6f21a51ffbb7: Pull complete
63913e0eb763: Pull complete
54e134c45235: Pull complete
5a260f11dc0f: Pull complete
94f6e6a9e60c: Pull complete
Digest: sha256:f666f2a2fe565e1a2ff8072fee41d661febbee0880e13a2ca91b96cc1205238b
Status: Downloaded newer image for mcr.microsoft.com/businesscentral/sandbox:15.2.39040.39489-ca-ltsc2019
mcr.microsoft.com/businesscentral/sandbox:15.2.39040.39489-ca-ltsc2019
Using image mcr.microsoft.com/businesscentral/sandbox:15.2.39040.39489-ca-ltsc2019
Creating Container BC15CA
Version: 15.2.39040.39489-ca
Style: sandbox
Platform: 15.0.39461.0
Generic Tag: 0.0.9.97
Container OS Version: 10.0.17763.914 (ltsc2019)
Host OS Version: 10.0.18362.476 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-CA
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file **********************
Files in C:\ProgramData\NavContainerHelper\Extensions\BC15CA\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC15CA from image mcr.microsoft.com/businesscentral/sandbox:15.2.39040.39489-ca-ltsc2019
00182837baef02d2850504d0788f23528537281044856650f4b047092fd3d0af
Waiting for container BC15CA to be ready
Initializing...
Setting host.docker.internal to 10.10.1.77 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.10.1.77 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to fe80 in container hosts file (copy from host hosts file)
Starting Container
Hostname is BC15CA
PublicDnsName is BC15CA
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint CCF6184601AA4A5BA565ACDCECE33DD90C80A9FA
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.docker.internal to 10.10.1.77 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.10.1.77 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to fe80 in container hosts file (copy from host hosts file)
Starting Container
Hostname is BC15CA
PublicDnsName is BC15CA
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint CCF6184601AA4A5BA565ACDCECE33DD90C80A9FA
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container BC15CA failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.25\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r BC15CA failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC15CA failed

**Comment by freddydk** [comment] 2020-01-21 09:38
Please do not reveal credentials for bcinsider in issues here. I have deleted them, will have to do an impact assessment...

This is likely your license file which is wrong or like.
Try the same without a license file to see whether this is the issue.

**Comment by NAVspecialist** [comment] 2020-01-21 11:53
I got the same error - License file was expired yesterday :) You'll get the same error if you use a BC license file on a NAV 201X image...

**Comment by freddydk** [comment] 2020-01-22 06:36
An easy way of discovering what's wrong is to use Get-NavContainerEventLog <containerName> when container initialization fails like this - then you get the event log, which will probably state that the license expired.

**Comment by yogipatel07081992** [comment] 2020-01-22 07:30
Thanks, @freddydk for a quick response.
I have i tried to a without a licence file in the script but same error is faced.

I am using the below image
$imageName = "mcr.microsoft.com/businesscentral/sandbox:15.2.39558.39792-ca-ltsc2019"

**Error Log**

Container OS Version: 10.0.17763.914 (ltsc2019)
Host OS Version: 10.0.18362.592 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-CA
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\BC152CA\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC152CA from image mcr.microsoft.com/businesscentral/sandbox:15.2.39558.39792-ca-ltsc2019
d9cb462341da9e9cd2b2560f9b376cfbd105df9bbbbf91e7febcb0fa25129a0a
Waiting for container BC152CA to be ready
Initializing...
Setting host.containerhelper.internal to fe80 in container hosts file (copy from host hosts file)
Setting host.docker.internal to 10.10.1.77 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.10.1.77 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Starting Container
Hostname is BC152CA
PublicDnsName is BC152CA
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 099F3990EAA8BCFD8996E861D45AB8E649A114BA
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.containerhelper.internal to fe80 in container hosts file (copy from host hosts file)
Setting host.docker.internal to 10.10.1.77 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.10.1.77 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Starting Container
Hostname is BC152CA
PublicDnsName is BC152CA
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 099F3990EAA8BCFD8996E861D45AB8E649A114BA
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container BC152CA failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.25\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ... BC152CA failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC152CA failed

**Comment by freddydk** [comment] 2020-01-22 08:49
Ran this script:

```
$imageName = "mcr.microsoft.com/businesscentral/sandbox:15.2.39558.39792-ca-ltsc2019"
$containerName = "BC15CA"
$auth = "UserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'Admin@123' -AsPlainText -Force)

New-BCContainer -accept_eula -alwaysPull `
 -imageName $imageName -containerName $containerName `
 -auth $auth -credential $credential `
 -assignPremiumPlan `
 -updateHosts -includeAL `
 -memoryLimit 4G
```
works fine here.

Could you use get-navcontainereventlog to download the event log for the failed container and attach that here?

Thanks

**Comment by yogipatel07081992** [comment] 2020-01-22 12:28
Thanks @freddydk your script is working for me.
The container is successfully created.

**Comment by freddydk** [comment] 2020-01-22 16:03
The script is an exact copy of the script you have above (which you say didn't work) - I didn't change a thing.
Do you know why?

**Comment by yogipatel07081992** [comment] 2020-01-23 05:52
I was just wondering and thinking about what is different between your script and my script. I have compared both scripts but I can't see any changes. 
Can you please tell me how did your script is working for me?

**Comment by freddydk** [comment] 2020-01-23 07:00
You have two identical scripts and one works and the other doesn't...
I have no chance to telling you how or why - I can only say you must be doing something wrong or right.
Closing this as the issue is resolved.

**Closed by freddydk** 2020-01-23 07:00 UTC
