### ISSUE TITLE
Cannot install the extension xxxx by zzz 18.3.0.7 because the tenant default already uses a different version of it.

### ISSUE THREAD

**Issue by herojo** [microsoft/navcontainerhelper#1944] opened 2021-05-29 10:42 UTC
**Describe the issue**
We try to run the ALValidation, but run into error "Cannot install the extension ... by ... 18.3.0.7 because the tenant default already uses a different version of it."

It is an "upgrade"-Test with a version 15- and version 18-App-File.

I think we detect the reason of the error: We have a "ö" in our company-name und in the app.json the publisher is "Comsol Unternehmenslösungen AG". An it looks, that the detection if "-install" or "-upgrade"-command is required come to the wrong result in the AIValidation-Script.

I changed the publisher in both apps to "Comsol Computerloesungen AG" (remove the "ö") and then it works. But i think this would be a breaking change for the Appsource-publishing, so we have to leave the "ö" in the publisher-property - or is it possible to do this change? 

**Scripts used to create container and cause the issue**
Run-AlValidation `
    -licenseFile $env:DockerBcLicense `
    -previousApps @($Old_AppDocuTie, $Old_AppStripe) `
    -apps @($New_AppDocuTie, $New_AppSubscriptionManager) `
    -affixes $Affixes `
    -countries $Countries `
    -skipVerification 

**Full output of scripts**
Previous Apps
- C:\Users\jh\OneDrive - Comsol Unternehmenslösungen AG\Develop\_Releases\Comsol Unternehmensloesungen AG_DocuTie_15.2.0.1.app
- C:\Users\jh\OneDrive - Comsol Unternehmenslösungen AG\Develop\_Releases\Comsol Unternehmenslösungen AG_Comsol Monetization_15.2.1.0.app
Apps
- C:\Users\jh\OneDrive - Comsol Unternehmenslösungen AG\Develop\_Releases\Comsol Unternehmensloesungen AG_DocuTie_18.3.0.9.app
- C:\Users\jh\OneDrive - Comsol Unternehmenslösungen AG\Develop\_Releases\Comsol Unternehmenslösungen AG_Comsol Subscription Manager_18.1.2.5.app
-

**Screenshots**
-> with "ö" in Companyname (publisher)
![image](https://user-images.githubusercontent.com/43319397/120067309-23db0a00-c07b-11eb-9f37-be76391a8d6f.png)
-> with "oe" in Companyname (publisher)
![image](https://user-images.githubusercontent.com/43319397/120067334-410fd880-c07b-11eb-9437-85f52cbe54ff.png)

**Comment by mightyjens** [comment] 2021-05-31 15:45
Hi guys, 
just to underline Jochen's idea:

If I replace the german special chars, the upgrade - routine is running correctly instead of installing.
This way the AL-Validation runs correctly. 

![image](https://user-images.githubusercontent.com/17178233/120216224-05217280-c237-11eb-950f-e82528a06743.png)

The "Replace-SpecialChars()" function:
(https://social.technet.microsoft.com/Forums/windowsserver/de-DE/8af91b31-7712-499c-a90b-a5cc8f95a8ff/umlaute-in-powershell-script-verwenden?forum=powershell_de)
```

function Replace-SpecialChars () {
    param ([string]$s)

    $SpecialChar = New-Object PSObject | Add-Member -MemberType NoteProperty -Name Name -Value $s -PassThru
 
    $characterMap = New-Object system.collections.hashtable
    $characterMap.ä = "ae"
    $characterMap.ö = "oe"
    $characterMap.ü = "ue"
    $characterMap.ß = "ss"
    $characterMap.Ä = "Ae"
    $characterMap.Ü = "Ue"
    $characterMap.Ö = "Oe"
 
 
    foreach ($property  in 'Name') { 
        foreach ($key in $characterMap.Keys) {
            $SpecialChar.$property = $SpecialChar.$property -creplace $key, $characterMap[$key] 
        }
    }
 
    $SpecialChar
}
```


Results in upgrading instead of new installation:
![image](https://user-images.githubusercontent.com/17178233/120216812-c809b000-c237-11eb-8e8f-f5ed4e165bc7.png)

Probably this helps.

**Comment by freddydk** [comment] 2021-06-01 05:16
Thanks for this info.
The real problem here is not in this location though.
The real problem is that the PowerShell Get-Content function works poorly with UTF8 text files without BOM if you do not specify the encoding.

Extract-AppFileToFolder used Get-Content to read the NavXManifest (which doesn't have a BOM) and then it writes the file using Set-Content - which also doesn't write the BOM - leaving it to the reader to determine what's right and wrong.

I will add encoding to both, which should solve this issue.

**Comment by mightyjens** [comment] 2021-06-01 06:57
Great, thank you!

**Comment by freddydk** [comment] 2021-06-01 07:53
this just shipped in the latest preview of BcContainerHelper - please let me know if this fix solves the issue

**Comment by mightyjens** [comment] 2021-06-01 10:01
Hi Freddy, 
now the update is triggered correctly using the updated _Run-AlValidation()_ from the preview:

![image](https://user-images.githubusercontent.com/17178233/120297264-3a76a080-c2c9-11eb-9166-2b76c1ce24d4.png)

So this part seems to be fixed. But unfortunately, now i get an error that looks like an encoding problem as well:
 
![image](https://user-images.githubusercontent.com/17178233/120301109-d48c1800-c2cc-11eb-8dee-c97974f24dc1.png)

Just to cross-check i've reinstalled version 2.0.12 and the error doesn't occur anymore (using my dirty fix from yesterday to avoid the underlaying problem).
So, probably a consequential error to your hotfix?

**Comment by freddydk** [comment] 2021-06-01 12:04
Could you email me a link to a .zip file with the apps you are running this with (Both previousapps and apps)?
You cannot email the .zip file.
freddyk at microsoft dot com

**Comment by freddydk** [comment] 2021-06-02 09:18
Just checked in another fix, which should fix this issue.
Another few cases of missing UTF8 conversion

**Comment by mightyjens** [comment] 2021-06-02 13:13
I can confirm the Al-Validation is now running without any errors. 

Thanks a lot!

**Comment by freddydk** [comment] 2021-06-02 13:22
Thanks for the assistance on troubleshooting:-)

**Closed by freddydk** 2021-06-02 13:22 UTC
Labels: Fix Ready, Ships in a future version, bug
