### ISSUE TITLE
UseSSL not working???

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#2205] opened 2021-11-24 16:24 UTC
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Creating a container using SSL creates the container fine but will not connect via the browser.  Get this error:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/4333956/143276140-5b548ff3-96c5-4938-bb46-3c8942c35824.png">

**Scripts used to create container and cause the issue**
```
$containerName = 'bc19cu01'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '19.1' -country 'gb' -select 'Latest'
$licenseFile = 'd:\license\bc19license.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -dns '192.168.0.1' `
    -usessl -installCertificateOnHost `
    -updateHosts `
    -isolation hyperv
```

**Full output of scripts**
```
BcContainerHelper is version 2.0.21
BcContainerHelper is running as administrator
Host is Microsoft Windows 11 Pro - 21H2
Docker Client Version is 20.10.10
Docker Server Version is 20.10.10
Removing container bc19cu01
Removing bc19cu01 from container hosts file
Removing bc19cu01-* from container hosts file
Removing d:\bccontainerhelper\Extensions\bc19cu01
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.20348.350
Creating Container bc19cu01
Style: onprem
Multitenant: No
Version: 19.1.31886.32186
Platform: 19.0.31889.32155
Generic Tag: 1.0.1.8
Container OS Version: 10.0.20348.350 (ltsc2022)
Host OS Version: 10.0.22000.318 (21H2)
Using hyperv isolation
Using locale en-GB
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file d:\license\bc19license.flf
Files in d:\bccontainerhelper\Extensions\bc19cu01\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bc19cu01 from image mcr.microsoft.com/businesscentral:10.0.20348.350
05cf7ed6ed4e9e0848a204b9e10f396817a347db152bf742dbec2bb6fd135dbb
Waiting for container bc19cu01 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/19.1.31886.32186/gb
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\19.1.31886.32186\platform\ServiceTier\Program Files
c:\dl\onprem\19.1.31886.32186\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\19.1.31886.32186\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\19.1.31886.32186\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\19.1.31886.32186\gb\database\Demo Database BC (19-0).bak
Changing Database Server Collation to Latin1_General_100_CI_AS
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\onprem\19.1.31886.32186\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\19.1.31886.32186\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\19.1.31886.32186\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\19.1.31886.32186\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\19.1.31886.32186\platform
c:\dl\onprem\19.1.31886.32186\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\19.1.31886.32186\gb\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\19.1.31886.32186\platform\Test Assemblies
Copying Applications
C:\dl\onprem\19.1.31886.32186\gb\Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 116 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.0.11 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.11 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting dbserver.containerhelper.internal to 192.168.0.11 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.27.176.1 in container hosts file
Starting Container
Hostname is bc19cu01
PublicDnsName is bc19cu01
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 0FCB0365B22C3DDD9061124AC985F3ED70F17A15
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.27.190.242
Container Hostname  : bc19cu01
Container Dns Name  : bc19cu01
Web Client          : https://bc19cu01/BC/
Dev. Server         : https://bc19cu01
Dev. ServerInstance : BC
Setting bc19cu01 to 172.27.190.242 in host hosts file

Files:
http://bc19cu01:8080/ALLanguage.vsix
http://bc19cu01:8080/certificate.cer

Container Total Physical Memory is 8.5Gb
Container Free Physical Memory is 5.9Gb

Initialization took 32 seconds
Ready for connections!
Reading CustomSettings.config from bc19cu01
Certificate with thumbprint 0FCB0365B22C3DDD9061124AC985F3ED70F17A15 imported successfully
Creating Desktop Shortcuts for bc19cu01
Container bc19cu01 successfully created

Use:
Get-BcContainerEventLog -containerName bc19cu01 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName bc19cu01 to get debug information about the container
Enter-BcContainer -containerName bc19cu01 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName bc19cu01 to remove the container again
docker logs bc19cu01 to retrieve information about URL's again
```

**Screenshots**

**Additional context**
- does it happen all the time?  Yes, but same script without -useSSL fails.
- did it use to work? For most other containers I use this and it has worked.

**Comment by freddydk** [comment] 2021-11-25 08:18
Duplicate of #2178

**Comment by freddydk** [comment] 2021-11-25 08:21
Why are you using DNS 192.168.0.1 - are you sure that your container can reach this address for DNS?

**Comment by GreatScott000** [comment] 2021-11-25 08:28
That is what the New-BCContainerWizard script picked up.  I made no changes to the script generated other than adding `-isolation hyperv`

**Comment by freddydk** [comment] 2021-11-25 08:30
Ok, thanks - I can repro this problem - seems like useSSL is broken on Windows 11 also with HyperV - I am investigating this with the Windows team already on Process isolation (and now add hyperv...:-()

**Comment by GreatScott000** [comment] 2021-11-25 08:32
Okay thanks.  I have always just selected option "C" here.
<img width="974" alt="image" src="https://user-images.githubusercontent.com/4333956/143406598-dfa81ff6-d093-471a-9f11-787e32c336cb.png">

**Comment by freddydk** [comment] 2021-11-25 09:30
Did some

**Comment by freddydk** [comment] 2021-11-25 10:33
The problem is not related to DNS

**Comment by freddydk** [comment] 2021-11-29 18:17
@yrubnerAL  - what host OS are you using for your AzureVM?

**Comment by freddydk** [comment] 2021-11-29 18:45
this machine: http://fkbc2022.westeurope.cloudapp.azure.com is an AzureVM with Windows Server 2022 and BC in a container using letsencrypt for SSL - setup using https://aka.ms/getbc
That works just fine - also connecting from Windows 11 edge/chrome.

**Comment by freddydk** [comment] 2021-11-29 19:56
and this machine: http://fkbctest.westeurope.cloudapp.azure.com/ is using Windows Server 2019 and a self-signed certificate.
It seems that the problem occurs when the docker host is Windows 11.
You should be able to use https://aka.ms/getbc to get an Azure VM with a certificate to test postman stuff.

**Comment by yrubnerAL** [comment] 2021-11-30 07:53
> @yrubnerAL - what host OS are you using for your AzureVM?

I was using Windows Server 2022 (datacenter core), which was set up using a community template: https://azure.microsoft.com/de-de/resources/templates/docker-portainer-traefik-windows-vm/

>
![image](https://user-images.githubusercontent.com/95237624/144007032-ddee7e3a-421e-4371-9410-0e9bb5e2307e.png)


After creating a VM with above template, I created a BC Docker Container (BC 14) using one of your scripts from a while ago regarding port-mapping:
![image](https://user-images.githubusercontent.com/95237624/144006955-69e7957e-2726-49cd-a655-e1eeaf061b2a.png)


I'll try your above suggestions asap and let you know whether it worked.
Thank you for taking another look at this topic.

**Comment by freddydk** [comment] 2021-11-30 10:34
OK, I do not have any insights in that ARM template - also if you have traefik installed - it is definitely not the same problem.
I think the script you are using here is incompatible with a traefik VM - when running traefik, all containers share the same port - it looks like you are publishing the container ports differently on the VM and in order for that to work, these ports must be opened in Azure and in the firewall.
This seems to be a different problem than the issue here in 2205 - and not related.

**Comment by freddydk** [comment] 2021-11-30 10:36
@GreatScott000 - when running a container with hyperV on Windows 11 with SSL, you can try to add this parameter:

```
-myScripts @("https://raw.githubusercontent.com/microsoft/nav-docker/master/override/selfsignedcertificate/SetupCertificate.ps1")
```
to override the SetupCertificate.ps1 script with a different version, which should work.
Let me know if this works for you?

**Comment by GreatScott000** [comment] 2021-11-30 11:44
@freddydk that script seems to solve the problem (using Edge, I have not tried Chrome but would expect it to work there too).

Is this a long term fix or will you be making changes to BCContainerHelper?

**Comment by freddydk** [comment] 2021-11-30 11:52
I will be investigating some more and find a more durable solution.
Consider this a temporary workaround.

**Comment by freddydk** [comment] 2021-12-02 06:37
The real fix here is to replace SetupCertificate in the generic image with this new version, I will probably get this done over the next week or two.
Until then - the myscript override above is the way to go.

**Comment by freddydk** [comment] 2022-01-20 14:16
New generic image has been deployed, issue should be resolved.

**Closed by freddydk** 2022-01-20 14:16 UTC
Labels: bug, Fix Ready, Ships in a future version
