### ISSUE TITLE
Error when creating NAV 2017 container with NavUserPassword authentication

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/navcontainerhelper#2334] opened 2022-03-03 07:26 UTC
**Describe the issue**
When creating a new NAV 2017 container, the container creation process terminates when the service tier is started.

A look at the event viewer indicates that it has something to do with the self-signed certificate.

Windows authentication works without any problems (when creating a new container), the mentioned error occurs only when using "NavUserPassword".

In addition to the output during container creation, I have also included the messages from the event viewer here.

**Scripts used to create container and cause the issue**
```
$containerName = 'Test-Container'

$securePassword = ConvertTo-SecureString -String "123frewedf544jh76" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "test", $securePassword

New-BCContainer -accept_eula `
                -alwaysPull `
                -containerName $containerName `
                -artifactUrl (Get-NavArtifactUrl -nav 2017 -country at -cu 14 -select Latest) `
                -auth NavUserPassword `
                -licensefile $mylicense `
                -updateHosts `
                -shortcuts CommonStartMenu `
                -doNotExportObjectsToText `
                -useBestContainerOS `
                -includeCSide `
                -Credential $credential
```

**Full output of scripts**
```
Setting use7zipIfAvailable = True
Setting digestAlgorithm = SHA256
Setting mapCountryCode = @{ae=w1; br=w1; co=w1; ee=w1; fo=dk; gl=dk; hk=w1; hr=w1; hu=w1; id=w1; ie=w1; jp=w1; kr=w1; lt=w1; lv=w1; my=w1; pe=w1; ph=w1; pl=w1; rs=w1; ro
=w1; sg=w1; si=w1; th=w1; tw=w1; vn=w1; za=w1}
Setting MicrosoftTelemetryConnectionString = 
Setting hostHelperFolder = C:\ProgramData\BcContainerHelper
Setting defaultContainerName = bcserver
Setting timeStampServer = http://timestamp.digicert.com
Setting bcartifactsCacheFolder = D:\bcartifacts.cache
Setting containerHelperFolder = C:\ProgramData\BcContainerHelper
Setting sandboxContainersAreMultitenantByDefault = True
Setting usePsSession = True
Setting genericImageName = mcr.microsoft.com/businesscentral:{0}
Setting defaultNewContainerParameters = @{doNotExportObjectsToText=True; Accept_Eula=True; shortcuts=CommonStartMenu; UpdateHosts=True; doNotCheckHealth=True; Auth=NavUs
erPassword; Accept_Outdated=True; MemoryLimit=8g}
BcContainerHelper version 3.0.2
Default parameter doNotCheckHealth = True
Default parameter Accept_Outdated = True
Default parameter MemoryLimit = 8g
BcContainerHelper is version 3.0.2
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Datacenter - ltsc2016
Docker Client Version is 20.10.12
Docker Server Version is 20.10.12
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.14393.4946
10.0.14393.4946: Pulling from businesscentral
Digest: sha256:c4d8b3c9855df8d64ec855e08b6ffa02ca3545bcedca9e6ada5495de35893310
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.14393.4946
Using image mcr.microsoft.com/businesscentral:10.0.14393.4946
Disabling Health Check (always report healthy)
Creating Container Test-Container
Style: onprem
Multitenant: No
Version: 10.0.19831.0
Platform: 10.0.19831.0
Generic Tag: 1.0.2.1
Container OS Version: 10.0.14393.4946 (ltsc2016)
Host OS Version: 10.0.14393.4946 (ltsc2016)
Using process isolation
Using locale de-AT
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file D:\_dev\license\DevLicense.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\Test-Container\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container Test-Container from image mcr.microsoft.com/businesscentral:10.0.14393.4946
0b002007d1eafe9376637645e7c83513e063904347e223431b3c1fdd1e970bb1
Waiting for container Test-Container to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/10.0.19831.0/at
Using installer from C:\Run\100
Copying Platform Artifacts
c:\dl\onprem\10.0.19831.0\platform
Copying Application Artifacts
Copying Database
Copying Installers
c:\dl\onprem\10.0.19831.0\at\Installers
Copying TestToolKit
c:\dl\onprem\10.0.19831.0\at\TestToolKit
Copying UpgradeToolKit
c:\dl\onprem\10.0.19831.0\at\UpgradeToolKit
Copying Extensions
c:\dl\onprem\10.0.19831.0\at\Extensions
Installing NAV
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Determining Database Collation
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\AT\OlAddin\OutlookAddIn.Local.At.msi
Installing C:\NAVDVD\Installers\AT\RTC\RoleTailoredClient.Local.At.msi
Installing C:\NAVDVD\Installers\AT\Server\Server.Local.At.msi
Installing C:\NAVDVD\Installers\AT\WebClient\WebClient.Local.At.msi
Skipping C:\NAVDVD\Installers\AT\WebHelp\WebHelp.Local.At.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 228 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.30.96.1 in container hosts file
Starting Container
Hostname is Test-Container
PublicDnsName is Test-Container
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 6EBD5B56F8FB55EAA17C6CD6744CBEE2FAAA5867
DNS identity Test-Container
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVDError
Using artifactUrl https://bcartifacts.azureedge.net/onprem/10.0.19831.0/at
Using installer from C:\Run\100
Copying Platform Artifacts
c:\dl\onprem\10.0.19831.0\platform
Copying Application Artifacts
Copying Database
Copying Installers
c:\dl\onprem\10.0.19831.0\at\Installers
Copying TestToolKit
c:\dl\onprem\10.0.19831.0\at\TestToolKit
Copying UpgradeToolKit
c:\dl\onprem\10.0.19831.0\at\UpgradeToolKit
Copying Extensions
c:\dl\onprem\10.0.19831.0\at\Extensions
Installing NAV
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Determining Database Collation
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\AT\OlAddin\OutlookAddIn.Local.At.msi
Installing C:\NAVDVD\Installers\AT\RTC\RoleTailoredClient.Local.At.msi
Installing C:\NAVDVD\Installers\AT\Server\Server.Local.At.msi
Installing C:\NAVDVD\Installers\AT\WebClient\WebClient.Local.At.msi
Skipping C:\NAVDVD\Installers\AT\WebHelp\WebHelp.Local.At.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 228 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.30.96.1 in container hosts file
Starting Container
Hostname is Test-Container
PublicDnsName is Test-Container
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 6EBD5B56F8FB55EAA17C6CD6744CBEE2FAAA5867
DNS identity Test-Container
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVD
Initialization of container Test-Container failed
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.2\ContainerHandling\Wait-NavContainerReady.ps1:42 Zeichen:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...ontainer failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container Test-Container failed
 
```

** Event Log Error 1**
```
Server instance: NAV
Tenant: 
<ii>The service MicrosoftDynamicsNavServer$NAV failed to start. This could be caused by a configuration error. Detailed error information: System.ArgumentException: It is likely that certificate 'CN=Test-Container' may not have a private key that is capable of key exchange or the process may not have access rights for the private key. Please see inner exception for detail. ---> System.Security.Cryptography.CryptographicException: Ungültigen Anbietertyp angegeben

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.ServiceModel.Security.SecurityUtils.GetKeyContainerInfo(X509Certificate2 certificate)
   at System.ServiceModel.Security.SecurityUtils.CanKeyDoKeyExchange(X509Certificate2 certificate)
   at System.ServiceModel.Security.SecurityUtils.EnsureCertificateCanDoKeyExchange(X509Certificate2 certificate)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Security.SecurityUtils.EnsureCertificateCanDoKeyExchange(X509Certificate2 certificate)
   at System.ServiceModel.Security.ServiceCredentialsSecurityTokenManager.CreateServerX509TokenProvider()
   at System.ServiceModel.Security.ServiceCredentialsSecurityTokenManager.CreateLocalSecurityTokenProvider(RecipientServiceModelSecurityTokenRequirement recipientRequirement)
   at System.ServiceModel.Security.ServiceCredentialsSecurityTokenManager.CreateSecurityTokenProvider(SecurityTokenRequirement requirement)
   at System.ServiceModel.Channels.SslStreamSecurityUpgradeProvider.CreateServerProvider(SslStreamSecurityBindingElement bindingElement, BindingContext context)
   at System.ServiceModel.Channels.ConnectionOrientedTransportChannelListener..ctor(ConnectionOrientedTransportBindingElement bindingElement, BindingContext context)
   at System.ServiceModel.Channels.TcpChannelListener..ctor(TcpTransportBindingElement bindingElement, BindingContext context)
   at System.ServiceModel.Channels.TcpTransportBindingElement.BuildChannelListener[TChannel](BindingContext context)
   at System.ServiceModel.Channels.SessionChannelDemuxer`2..ctor(BindingContext context, TimeSpan peekTimeout, Int32 maxPendingSessions)
   at System.ServiceModel.Channels.ChannelDemuxer.CreateTypedDemuxer(Type channelType, BindingContext context)
   at System.ServiceModel.Channels.ChannelDemuxer.GetTypedDemuxer(Type channelType, BindingContext context)
   at System.ServiceModel.Channels.ChannelDemuxer.BuildChannelListener[TChannel](BindingContext context, ChannelDemuxerFilter filter)
   at System.ServiceModel.Channels.ChannelBuilder.BuildChannelListener[TChannel]()
   at System.ServiceModel.Channels.ChannelBuilder.BuildChannelListener[TChannel](MessageFilter filter, Int32 priority)
   at System.ServiceModel.Channels.SecurityChannelListener`1.InitializeListener(ChannelBuilder channelBuilder)
   at System.ServiceModel.Channels.TransportSecurityBindingElement.BuildChannelListenerCore[TChannel](BindingContext context)
   at System.ServiceModel.Channels.ReliableChannelListener`3..ctor(ReliableSessionBindingElement binding, BindingContext context)
   at System.ServiceModel.Channels.ReliableListenerOverSession`5..ctor(ReliableSessionBindingElement binding, BindingContext context)
   at System.ServiceModel.Channels.ReliableListenerOverDuplexSession`2..ctor(ReliableSessionBindingElement binding, BindingContext context)
   at System.ServiceModel.Channels.ReliableSessionBindingElement.BuildChannelListener[TChannel](BindingContext context)
   at Microsoft.Dynamics.Nav.Types.Channels.ChunkingBindingElement.BuildChannelListener[TChannel](BindingContext context)
   at System.ServiceModel.Channels.Binding.BuildChannelListener[TChannel](Uri listenUriBaseAddress, String listenUriRelativeAddress, ListenUriMode listenUriMode, BindingParameterCollection parameters)
   at System.ServiceModel.Description.DispatcherBuilder.MaybeCreateListener(Boolean actuallyCreate, Type[] supportedChannels, Binding binding, BindingParameterCollection parameters, Uri listenUriBaseAddress, String listenUriRelativeAddress, ListenUriMode listenUriMode, ServiceThrottle throttle, IChannelListener& result, Boolean supportContextSession)
   at System.ServiceModel.Description.DispatcherBuilder.BuildChannelListener(StuffPerListenUriInfo stuff, ServiceHostBase serviceHost, Uri listenUri, ListenUriMode listenUriMode, Boolean supportContextSession, IChannelListener& result)
   at System.ServiceModel.Description.DispatcherBuilder.InitializeServiceHost(ServiceDescription description, ServiceHostBase serviceHost)
   at System.ServiceModel.ServiceHostBase.InitializeRuntime()
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartWcfServices()
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName).</ii>

```

** Event Log Error 2 **
```
Server instance: NAV
Tenant ID: 
<ii>User: 
Type: System.ObjectDisposedException
Message:
  <ii>Cannot access a disposed object.
  Object name: 'NavSystemTenant'.</ii>
ObjectName: NavSystemTenant
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavSystemTenant.get_NCLMetadata()
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscription.<FindDefinedEventSubscriptions>d__29.MoveNext()
     at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscriptionMetadata.CreateNavEventSubscriptionsFromCodeunitIds(IEnumerable`1 codeunitIds, NavAppGroup appGroup)
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscriptionMetadata.Initialize(Boolean bindSubscriptions)
     at Microsoft.Dynamics.Nav.Runtime.NavEnvironment.OnApplicationMounted(NavTenantCollection tenantCollection)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, String appDatabaseUserName, ProtectedDatabasePassword appDatabasePassword, Boolean verifyConnection, String newEncryptionKey, IDatabasePasswordPublicEncryptionKeyStorage keyStorage, Boolean allowOverwritePublicKey, Boolean verifyServerInstanceKey)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSingleLegacyTenant(String databaseServerName, String databaseName, String databaseUserName, ProtectedDatabasePassword databasePassword, EncryptionProvider encryptionProvider, AzureKeyVaultSettings azureKeyVaultSettings)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.ConfigureTenants(ServerUserSettings settings)
     at Microsoft.Dynamics.Nav.Runtime.NavTaskFactory.<>c__DisplayClass11_0.<StartNewTask>b__0()
     at System.Threading.Tasks.Task.Execute()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146232798
</ii>
```

** Event Log Error 3 **
```
The "Microsoft Passport Key Storage Provider" provider was not loaded due to an initialization error.

  Context Local system 
  Provider Microsoft Passport Key Storage Provider 
  Failure NCryptOpenStorageProvider 
  ErrorCode The provider DLL was not found. 0x8009001e (-2146893794 NTE_PROV_DLL_NOT_FOUND) 
```

**Screenshots**

**Additional context**
- does it happen all the time?
  - Yes
- did it use to work?
  - Yes

**Comment by freddydk** [comment] 2022-03-04 13:23
Looks like a duplicate of #2277 and #2264

**Closed** 2022-03-22 14:12 UTC
