### ISSUE TITLE
Invoke-ScriptInBcContainer/Enter-BcContainer fails to load other powershell modules

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/navcontainerhelper#3330] opened 2024-02-07 07:36 UTC
A beautiful, typical, rainy Wednesday morning! You can almost smell the summer in DK! :D 

I get lately more of the following reported by the dev team: 
"The Expand-Archive command was found in the module "blablabla", but the module could not be loaded." What has bccontainerhelper tp do with this? well: 

What I added in our scripts was some Invoke-ScriptInBcContainer, that after I moved in some zip file to the container, is about to extract the content within the container to some folder ... and that worked well, but now I get, as I said, more and more reports on this....

Not sure what triggered this "massive" raise on reports. While I investigate I could also see, it has the same issue with Enter-BcContainer ( while Open-BcContainer just worked fine).... so that lead me to: Must be the Session handling...

So my current attempt to help people out: switch the $bcContainerHelperConfig.UsePsSession flag to false. What I don't get is: some have it others not. 
There is one "unique" approach we (are forced to ) use: run everything as normal users ( IT took away the local administrator rights if you maybe recall)

So my current theory is : something is not good in identifying the circumstances about that "state" the user is trigging the commands... I recall some comment on PsSession about identifying if it should use a given Session or do docker run command instead...

And because this is all I have around this topic I will leave it to you if this is worth to look in or not :D 
Maybe it is at least helping others with the same issue ?! 

I could ask: Is it "ok" to force the UsePsSession to false on all our machines? Do we "lose" functionality? (not that it ends up in a like the "pick your Isolation poison" dilemma ).

**Comment by freddydk** [comment] 2024-02-07 09:59
When you say: What I don't get is: some have it others not.
Does that mean that some people don't have this flag in config?
If they have the latest version, they should.
It should work with true or false - what I have seen earlier is that when copying files into the container, the file might not be available immediately - there might be a delay.
You can also try to run import-module explicit, which then will tell you why this error is thrown

**Comment by KristofKlein** [comment] 2024-02-07 11:52
"keep powershell modeules" up2date...same like fighting windmills ;) 

when I see it I breach it again and again....fun aside...when I say "some works others not"... so I have set it to true and I don't have any issues, but the developer with the same sort of setup: non admin, same version, does get the issue...

Well.... 
got this from one of the "never give up developers":
_... showed me something interesting - if my container has a folder named the same as what "Get-SystemLanguage" on the host OS puts out (in my case it's "en-GB") in the location C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\, the dll update script can run without any errors (the folder contents can jut be copied from "en-US" - seems to just be some localisation strings).  This is very  cumbersome to do though, so it's probably easier to just change the PS variable to "false" as described above, but I thought I would share this interesting information anyway_

I did try to enter-bccontainer import which did not work, and I think it did not because of the "scope" / admin ... that was also why I started to tell them set the PsSession to false such that it runs "isolated" or in it's own scope (or what ever it for real means). I will try to find someone and redo to get the correct error.

Never experienced this delay in file copy....will also have an eye on this.

**Comment by dannoe** [comment] 2024-02-07 18:43
I got the same error message (``The Expand-Archive command was found in the module...``) on running localDevEnv.ps1 in the BaseApp repo (https://github.com/microsoft/BusinessCentralApps).

On further research loading the Microsoft.PowerShell.Archive module failed inside the container with the following error:
```pwsh
Import-Module Microsoft.PowerShell.Archive
Cannot find the Windows PowerShell data file 'ArchiveResources.psd1' in directory
'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\de-DE\', or in any
parent culture directories.
    + CategoryInfo          : ObjectNotFound: (C:\Windows\syst...eResources.psd1:String) [Import-Localiz
   edData], PSInvalidOperationException
    + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData
```

So it tries to load the de-DE localization data (my host system is de-DE). On the Internet I found a workaround with copying the en-US files to the de-DE folder, but since this was done while running ``localDevEnv.ps1``, I didn't want to fiddle with the script. I did manage to workaround this error by setting the culture to en-US inside my powershell session before calling the script:

```pwsh
$culture = [System.Globalization.CultureInfo]::GetCultureInfo("en-US")
[System.Threading.Thread]::CurrentThread.CurrentCulture = $culture
[System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture
```

Not sure if this helps finding the problem.

**Comment by freddydk** [comment] 2024-02-08 05:32
Did you add these lines to the script you invoke inside the container?
or did you run these lines on the host - before invoking the script?

**Comment by dannoe** [comment] 2024-02-08 05:52
On the host

**Comment by freddydk** [comment] 2024-02-08 07:26
I assume this happens because you are running process isolation?
Switching to hyperv isolation might fix the issue altogether.

But..., could you try the following:

Set the culture to de-DE on the host.

Modify the file c:\run\prompt.ps1 inside the container and add the 3 lines right after the PARAM section, like:
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/92059673-779b-4e4f-900c-be5c65753e85)

Then run `Remove-BcContainerSession -containerName $containerName` on the host

Then retry the operation - does it work?
Did the culture change on the host in that session?

**Comment by KristofKlein** [comment] 2024-02-08 08:49
so the last guy reported the issue to me is using hyperv :(

**Comment by dannoe** [comment] 2024-02-08 09:02
I did try **process and hyperv isolation**. Got the same error on both modes.
I can not modify the file inside the container, because this always happens on a fresh run of ``localDevEnv.ps1``. (The container is recreated everytime.)

Should the container normally be created with en-US or the culture of the host?

**Comment by freddydk** [comment] 2024-02-09 11:48
This is what I think:
The container is en-US - but the session inherits the locale of the host (apparently) - and since the container is en-US - it doesn't have de-DE (or other) resources.

If you have a running container - and then start a new PowerShell prompt and run this script:
```
$containerName = 'bcserver'
$containerId = Get-BcContainerId -containerName $containerName
$session = New-PSSession -ContainerId $containerId -RunAsAdministrator
$PSVersionTable | Out-Host
Write-Host "Host Culture Before: $([System.Threading.Thread]::CurrentThread.CurrentCulture)"
Write-Host "Host UICulture Before: $([System.Threading.Thread]::CurrentThread.CurrentUICulture)"
Invoke-Command -Session $session -ScriptBlock {
    Write-Host "Container Culture Before: $([System.Threading.Thread]::CurrentThread.CurrentCulture)"
    Write-Host "Container UI Culture Before: $([System.Threading.Thread]::CurrentThread.CurrentUICulture)"
    $culture = [System.Globalization.CultureInfo]::GetCultureInfo("en-US")
    [System.Threading.Thread]::CurrentThread.CurrentCulture = $culture
    [System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture
    Write-Host "Container Culture After: $([System.Threading.Thread]::CurrentThread.CurrentCulture)"
    Write-Host "Container UI Culture After: $([System.Threading.Thread]::CurrentThread.CurrentUICulture)"
}
Write-Host "Host Culture After: $([System.Threading.Thread]::CurrentThread.CurrentCulture)"
Write-Host "Host UICulture After: $([System.Threading.Thread]::CurrentThread.CurrentUICulture)"
```
Restart the PowerShell prompt and re-run the same script.
Paste both outputs here,

Thanks

**Comment by dannoe** [comment] 2024-02-09 20:05
I was trying it first with my still existing container:

First run (PowerShell 5 with admin rights)
```pwsh
BcContainerHelper version 6.0.6-preview1129
Setting MicrosoftTelemetryConnectionString =

Name                           Value
----                           -----
PSVersion                      5.1.19041.3930
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3930
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


Host Culture Before: de-DE
Host UICulture Before: de-DE
Container Culture Before: en-US
Container UI Culture Before: en-US
Container Culture After: en-US
Container UI Culture After: en-US
Host Culture After: de-DE
Host UICulture After: de-DE
```

Second run (PowerShell 5 with admin rights)
```pwsh
BcContainerHelper version 6.0.6-preview1129
Setting MicrosoftTelemetryConnectionString =

Name                           Value
----                           -----
PSVersion                      5.1.19041.3930
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3930
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


Host Culture Before: de-DE
Host UICulture Before: de-DE
Container Culture Before: en-US
Container UI Culture Before: en-US
Container Culture After: en-US
Container UI Culture After: en-US
Host Culture After: de-DE
Host UICulture After: de-DE
```

I couldn't run it without admin or with admin and powershell core, because on these sessions ``New-PSSession`` couldn't find the container. (It was definitely running and had enough permissions.)

I tried to reproduce the error but did a pull of the newest version from https://github.com/microsoft/BusinessCentralApps before. Now I can't reproduce it.

**Comment by KristofKlein** [comment] 2024-02-12 09:51
I have this from one of my developers:

we get the same first and second run: 
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.3930
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3930
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Host Culture Before: en-GB
Host UICulture Before: en-GB
Container Culture Before: en-US
Container UI Culture Before: en-US
Container Culture After: en-US
Container UI Culture After: en-US
Host Culture After: en-GB
Host UICulture After: en-GB
```

Same here with the New-PsSession and a containerID had to start an admin Shell to execute the command. 

for the fun I checked my (just fine working) machine it says:
```
Host Culture Before: en-GB
Host UICulture Before: **en-US**  # that is most likely why it works fine?!

```
while my container says:
```
Container Culture After: de-DE
Container UI Culture After: en-US
Container Culture Before: de-DE
Container UI Culture Before: en-US
Container Culture After: de-DE
Container UI Culture After: en-US
```

**Comment by KristofKlein** [comment] 2024-02-12 10:46
another developer, another output:
Host Culture Before: en-GB
Host UICulture Before: en-GB
Container Culture Before: de-DE
Container UI Culture Before: en-US
Container Culture After: en-US
Container UI Culture After: en-US

and the second round:
Host Culture Before: en-GB
Host UICulture Before: en-GB
Container Culture Before: de-DE
Container UI Culture Before: en-US
Container Culture After: en-US
Container UI Culture After: en-US

**Comment by freddydk** [comment] 2024-03-06 09:40
Looked through the code...
Could you try to add `-locale 'en-US'` to your New-BcContainer and see whether this solves the issue.
I can see that the locale is taken from the countrycode of the version we spin up and set inside the SetupVariables script in the generic docker image:
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/5e6e3dad-6758-491e-88a9-f2362ae648a2)
Maybe this is really for older versions of NAV/BC and Windows - maybe we don't need this anymore - I will investigate.

**Comment by KristofKlein** [comment] 2024-03-15 14:07
Sorry, late to the party. I will give it a try and forward to the folks having the issue. As all works for my setup I need to find a Guinea pig ;)

**Comment by KristofKlein** [comment] 2024-03-19 08:36
nope. that did not work.

**Comment by freddydk** [comment] 2024-04-29 14:16
I am pretty sure that the latest preview has a fix for this.

**Comment by kfuglsang** [comment] 2024-05-21 19:49
I'm starting to see this issue today on 6.0.17.
Didn't apply any patches or config overrides to my setup. Simply upgraded to 6.0.17.


Powershell 5.1.22621.2506
no WinRM

Generic Tag: 1.0.2.22
Container OS Version: 10.0.20348.2461 (ltsc2022)
Host OS Version: 10.0.22631.3447 (23H2)

**Comment by freddydk** [comment] 2024-05-21 20:11
@kfuglsang - Very strange - that issue should have been resolved.
You get the expand-archive problem?

What version of BC are you running?
Does it work if you revert to 6.0.16?
What does this:

```
$PSVersionTable | Out-Host
Write-Host "Culture: $([System.Threading.Thread]::CurrentThread.CurrentCulture)"
Write-Host "UICulture: $([System.Threading.Thread]::CurrentThread.CurrentUICulture)"
```

output when run inside the container?

**Comment by kfuglsang** [comment] 2024-05-21 20:18
Yep, I get the Expand-Archive issue now. Didn't have that previously.

I'm seeing the issue across multiple BC versions that were tried today.
- https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/20.1.39764.40432/dk
- https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/23.1.13431.13812/dk
- https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/21.5.53619.53819/dk
- https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/22.4.59114.59154/dk

Just now attempted to remove all docker images and let it rebuild, but same issue happened.
Will test your suggestions now.

**Comment by freddydk** [comment] 2024-05-21 20:21
Or maybe try to add `-locale 'en-US'`
Maybe we can arrange a teams meeting tomorrow and troubleshoot your machine/setup.
I am available at 9:00

**Comment by freddydk** [comment] 2024-05-21 20:47
One more thing to try is to set $bcContainerHelperConfig.usePsSession = $false and see if that changes anything
When I run the lines above, I get:

![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/c1764eca-65c5-49b4-8920-4bff0d635b25)

**Comment by kfuglsang** [comment] 2024-05-21 20:47
The container outputted

```
$PSVersionTable | Out-Host

Name                           Value
----                           -----
PSVersion                      5.1.20348.2400
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.2400
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Write-Host "Culture: $([System.Threading.Thread]::CurrentThread.CurrentCulture)"
Culture: da-DK

Write-Host "UICulture: $([System.Threading.Thread]::CurrentThread.CurrentUICulture)"
UICulture: en-GB

```

Reverted to 6.0.15 now (we had to roll back 6.0.16 previously due to #3518). With 6.0.15 the build works again.
Will invite for a call tomorrow at 09

**Comment by freddydk** [comment] 2024-05-21 20:49
And with 6.0.15 - does the lines above output the same?

UICulture?

**Comment by freddydk** [comment] 2024-05-21 20:50
BTW - are you running as admin?
What does whoami return inside the container?

**Comment by kfuglsang** [comment] 2024-05-21 20:55
I'm running as admin. `whoami` returns `user manager\containeradministrator` 


With 6.0.15 I get the following:
```
$PSVersionTable | Out-Host

Name                           Value
----                           -----
PSVersion                      5.1.20348.2400
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.2400
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Write-Host "Culture: $([System.Threading.Thread]::CurrentThread.CurrentCulture)"
Culture: en-GB

Write-Host "UICulture: $([System.Threading.Thread]::CurrentThread.CurrentUICulture)"
UICulture: en-GB
```

**Comment by freddydk** [comment] 2024-05-21 23:13
I know what happened - will issue a fix.
The issue is (as already stated) in the PowerShell Archive module.
6.0.15 will patch this module no matter what.
In 6.0.17, it patches the module only if the generic version is lower than 1.0.2.21 - because the patching is now part of the generic image.

But...

The patching failed during build of the generic image - hence with 6.0.17 - nobody patches the new generic image.

I am creating a new generic image with correct patching.

**Comment by freddydk** [comment] 2024-05-22 04:25
Generic image 1.0.2.23 is rolling out now.
Please try that with 6.0.17 before our meeting if possible

If this fixes the issue, feel free to cancel the meeting if you like.

**Comment by kfuglsang** [comment] 2024-05-22 06:52
Upgraded and ran a few builds on our pipelines this morning. They have all succeeded.
Thanks for the quick action!

**Comment by freddydk** [comment] 2024-05-22 06:57
With this, I will close this issue
Please ensure you have generic image 1.0.2.23 when running.

**Closed by freddydk** 2024-05-22 06:57 UTC
Labels: bug, Fix Ready, Ships in a future version
