### ISSUE TITLE
[Question] Run-AlPipeline: different behavior to previous versions from Hello World CI/CD example

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/navcontainerhelper#1401] opened 2020-10-26 08:13 UTC
Hi @freddydk,

we are using an adapted version from your [Hello World CI/CD example](https://dev.azure.com/businesscentralapps/HelloWorld) to run our build pipelines (which works quite well so far).

Your example has now switched to use the Run-AlPipeline scripts, which now shows a different behavior:

- Runtime packages are always generated (we are using the variable from the YAML)
used by the `DevOps-Pipeline.ps1` script
```
$createRuntimePackages = "$env:CreateRuntimePackages" -eq 'True'
Run-AlPipeline
   -CreateRuntimePackages:$createRuntimePackages `
```

- At the very end the container is removed by Run-AlPipeline **and** your Cleanup script
(therefore the Remove-BcContainer call in `Cleanup.ps1` fails) _-not really important-_
We are using the RemoveBcContainer script block to override that (we stop the containers...)
`Run-AlPipeline -RemoveBcContainer $RemoveBcContainer `

- The resulting Artifact has now a `<AppVersion>.0.0` version (ignoring AppBuild and AppRevision)
Without an app.json file (like before).

Any idea how I can get an Artifact with AppRevision `<AppVersion>.<AppBuild>.<AppRevision>` and that app.json file again?

Remark: we are running those build pipelines within Azure Devops for an OnPrem solution.

**Comment by freddydk** [comment] 2020-10-26 11:10
The runtime packages piece is a bug.
It should be part of settings as to which builds should get runtime packages generated and what not - will fix that.

Remove-BcContainer should not fail - I can call it 10 times with the same name.
It is on purpose to remove it in both places. If the run-alPipeline fails, then the container might still be around, hence the cleanup.

On appversion - you would have to stamp major and minor version number into app.json manually.

**Comment by freddydk** [comment] 2020-10-26 11:25
As I am working on the new HOL now - I have fixed the runtime packages issue now.

**Comment by ralf-escher** [comment] 2020-10-26 12:28
Hello @freddydk, thanks for the quick response.

About:
_On appversion - you would have to stamp major and minor version number into app.json manually._
AppVersion is fine, but AppBuild & AppRevision are **not** increased.

the Run-AlPipeline script contains the following part, so I wonder why the resulting app has `Major.Minor.0.0`

```
    $appJsonFile = Join-Path $folder "app.json"
    $appJson = Get-Content $appJsonFile | ConvertFrom-Json
    if ($appBuild) {
        $appJsonVersion = [System.Version]$appJson.Version
        $version = [System.Version]::new($appJsonVersion.Major, $appJsonVersion.Minor, $appBuild, $appRevision)
        Write-Host "Using Version $version"
        $appJson.version = "$version"
        $appJson | ConvertTo-Json -Depth 99 | Set-Content $appJsonFile
    }
```
Set BuildNumber
```
2020-10-26T11:25:05.9967373Z ##[section]Async Command Start: Update Build Number
2020-10-26T11:25:06.1642021Z Update build number to 29.0.0.3794 for build 3794
2020-10-26T11:25:06.1642472Z ##[section]Async Command End: Update Build Number
2020-10-26T11:25:06.1643786Z ##[section]Finishing: Set BuildNumber
```

**Comment by freddydk** [comment] 2020-10-27 12:47
In the .yaml file, the build and revision are increased by
    appBuild: $(Build.BuildID)
    appRevision: 0

and transferred to the devops-pipeline using: 
      targetType: filePath
      filePath: 'scripts\DevOps-Pipeline.ps1'
      arguments: '-version "$(version)" -appBuild $(appBuild) -appRevision $(appRevision)'
      failOnStderr: true

If you are not using azure devops - you would have to increase things differently.

**Comment by freddydk** [comment] 2020-10-27 13:16
are you running in Azure DevOps or locally?

**Comment by ralf-escher** [comment] 2020-10-27 13:50
Azure DevOps

**Comment by freddydk** [comment] 2020-10-27 16:09
I don't understand that your apprevision has a number and appbuild is 0.
In CI.yml, apprevision is hardcoded to 0
how does your variables part of ci.yml look?

**Comment by ralf-escher** [comment] 2020-10-28 09:36
we use a static appBuild number and increase the appRevision number (see above)

```
    version: 'current'
    appVersion: '29.0'
    appBuild:  '0'
    appRevision: $(Build.BuildID)
```

in the previous version we used:

```
      appVersion: "29.0"
      appBuild: 0
      appRevision: $[counter(variables['appVersion'],0)]
```

"Set BuildNumer" shows the correct version (also see above)

Maybe your routine always generates an `<Major><Minor><Build>.0` app?

Get-NAVAppInfo also shows AppRevision 0
```
Get-NAVAppInfo -Path BE-terna_BE-Industry_29.0.0.0.app
Name                : BE-Industry
Version             : 29.0.0.0
```

**Comment by ralf-escher** [comment] 2020-10-28 10:33
Guess I found the problem:
in the Run-AlPipeline script:

   ```
    $appJsonFile = Join-Path $folder "app.json"
    $appJson = Get-Content $appJsonFile | ConvertFrom-Json
    if ($appBuild) {
        $appJsonVersion = [System.Version]$appJson.Version
        $version = [System.Version]::new($appJsonVersion.Major, $appJsonVersion.Minor, $appBuild, $appRevision)
        Write-Host "Using Version $version"
        $appJson.version = "$version"
        $appJson | ConvertTo-Json -Depth 99 | Set-Content $appJsonFile
    }

Since we are using currently AppBuild "0", that script part does not write the AppRevision to the app.json file
```

**Comment by freddydk** [comment] 2020-10-28 10:40
Got it - I will fix that to check for build -or revision.

**Comment by ralf-escher** [comment] 2020-10-29 09:25
Still creates a `<Major><Minor><Build>.0` app

Did I use the wrong BcContainerhelper Preview version?

```
2020-10-29T08:45:49.5893382Z Use bcContainerHelper Version: preview
2020-10-29T08:45:49.6252656Z Determine latest BcContainerHelper preview version
2020-10-29T08:45:56.0253058Z BcContainerHelper 1.0.12-preview234 is the latest preview version
[...]
2020-10-29T08:46:00.8167049Z AppBuild                    0
2020-10-29T08:46:00.8171727Z AppRevision                 3874
```

**Comment by freddydk** [comment] 2020-10-29 09:59
preview looks fine - did you check that the code change is in? (it should be)

**Comment by freddydk** [comment] 2020-10-29 11:14
Just tried to change one of my projects - and it works in that one:
![image](https://user-images.githubusercontent.com/10775043/97561304-41120200-19e0-11eb-92ce-2e46bc6a5523.png)

**Comment by ralf-escher** [comment] 2020-10-29 11:59
Works now...  :-)
```
2020-10-29T11:27:08.2091723Z Use bcContainerHelper Version: preview
2020-10-29T11:27:08.2462630Z Determine latest BcContainerHelper preview version
2020-10-29T11:27:22.7502442Z BcContainerHelper 1.0.12 is the latest preview version
[...]
2020-10-29T11:29:40.7319919Z Compiling...
2020-10-29T11:29:40.7388415Z .\alc.exe <...> /out:"c:\sources\.output\BE-terna_BE-Industry_29.0.0.3882.app" 
2020-10-29T11:29:55.6887301Z Microsoft (R) AL Compiler version 6.0.5.10826
```
_How ever I don't understand the correct usage of the build no. and if our method is suitable to use it for the revision_
   ` appRevision: $(Build.BuildID)`
_From where is that BuildID derived from? (further information?)_

I am extremely grateful for your good support, thanks a lot!  👍

**Comment by freddydk** [comment] 2020-10-29 12:01
The build id is just an increasing number in your organization.
You can also use the counters as you did before - the problem I have with counters is, that if you have multiple projects with dependencies, then it becomes a hazzle.

**Closed** 2020-10-29 12:01 UTC
Labels: Fix Ready, Ships in a future version, bug

**Comment by ralf-escher** [comment] 2020-10-29 12:16
Sorry to bother you with another (smaller) issue:

your example [YAML file](https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=%2Fscripts%2FCI.yml) is using the variable `TestResults`

  ```
- task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: and(succeeded(),ne(variables['TestResults'],''))
    inputs:
      testResultsFormat: XUnit
      testResultsFiles: '$(testResults)'
      failTaskOnFailedTests: true
```
...but I can find where you set it within your scripts (CDI/CD Hello World & navcontainerhelper) 

Since I don't run Tests, I get a warning ...
```
##[warning]No test result files matching testresults*.xml were found.
##[section]Finishing: Publish Test Results
```

**Comment by freddydk** [comment] 2020-10-29 12:48
That is by design.
If you have a publish test results task and there are no test results - you will get a warning.
You can remove the publish test results from your yml file.
