### ISSUE TITLE
Windows activation lost after creating container

### ISSUE THREAD

**Issue by corsbj** [microsoft/navcontainerhelper#1331] opened 2020-10-03 12:47 UTC
**Describe the issue**
After creating a new container, Windows activation on the host is lost. We're running Windows 10 Enterprise 1903.
It seems to only happen with containers created using navcontainerhelper.
We're not using docker desktop, but the Windows feature 'containers', I don't know if that's important.
Reactivating through Settings is possible, but when activation is lost, Windows throws out the Direct Access settings and they don't come back until the computer is able to apply GPOs again. That means developers are effectively cut off from internal resources until they're back in the office.

**Scripts used to create container and cause the issue**
$BCArtifactUrl = Get-BCArtifactUrl -type onprem -version 16.5.15897.15953 -country dk
    New-NavContainer `
        -containerName $containerName `
        -accept_eula `
        -alwaysPull `
        -auth NavUserPassword `
        -Credential $credential `
        -artifactUrl $BCArtifactUrl `
        -licenseFile $licenseFile `
        -memoryLimit 8G `
        -useBestContainerOS `
        -doNotExportObjectsToText `
        -doNotCheckHealth `
        -enableTaskScheduler:$true `
        -bakFile $backupFile `
        -shortcuts Desktop `
        -updateHosts `
        -dns 1.1.1.1

**Full output of scripts**
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1903
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.18362.1082-generic
10.0.18362.1082-generic: Pulling from dynamicsnav
Using image mcr.microsoft.com/dynamicsnav:10.0.18362.1082-generic
Disabling Health Check (always report healthy)
Creating Container XXX
Version: 16.5.15897.15953-dk
Style: onprem
Platform: 16.0.15884.15941
Generic Tag: 0.1.0.23
Container OS Version: 10.0.18362.1082 (1903)
Host OS Version: 10.0.18362.1082 (1903)
Using locale da-DK
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file \\xxx\4804774_BC16DKDEV.flf
Additional Parameters:
--env customNavSettings=EnableTaskScheduler=True
Files in C:\ProgramData\NavContainerHelper\Extensions\XXX\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container XXX from image mcr.microsoft.com/dynamicsnav:10.0.18362.1082-generic
4aeb568a3cabeae2746e34aac7d5e188e998afda8b409b3e9d32ac45533e6ec7
Waiting for container XXX to be ready
Using artifactUrl https://bcartifacts.blob.core.windows.net/onprem/16.5.15897.15953/dk
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Installation took 17 seconds
Installation complete
Initializing...
Setting host.docker.internal to 10.1.0.59 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.1.0.59 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.28.48.1 in container hosts file
Starting Container
Hostname is XXX
PublicDnsName is XXX
Using NavUserPassword Authentication
Using Database .bak file 'C:\ProgramData\NavContainerHelper\Extensions\XXX\database.bak'
Using database server localhost\SQLEXPRESS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint FBF91FA61E9F8E5E5BB0B2E81D7F857463C6E7FD
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to True
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating demo as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements.
It should be at least 8 characters long and contain at least one uppercase
letter, one lowercase letter, and one number.
Container IP Address: 172.28.48.217
Container Hostname  : XXX
Container Dns Name  : XXX
Web Client          : http://XXX/BC/
Dev. Server         : http://XXX
Dev. ServerInstance : BC
Setting XXX to 172.28.48.217 in host hosts file

Files:
http://XXX:8080/ALLanguage.vsix

Container Total Physical Memory is 31.8Gb
Container Free Physical Memory is 15.7Gb

Initialization took 84 seconds
Ready for connections!
Reading CustomSettings.config from XXX
Creating Desktop Shortcuts for XXX
Container XXX successfully created

**Screenshots**

**Additional context**
Seems to happen every time a NAV container is created.
We recently switched to process isolation, and that seems to have made this happen.

**Comment by freddydk** [comment] 2020-10-03 13:04
That sounds very very strange.
You say you don't have docker installed - but when you start a CMD prompt - you can write: 
docker ps -a
right?
Windows Containers is a prerequisite for docker as far as I know.
Does it make any difference if you run the containers in hyperv isolation? (add -isolation hyperv)

**Comment by corsbj** [comment] 2020-10-03 13:33
I don't have Docker Desktop, but I have the Windows feature 'Containers' installed.
docker command works, yes.
If I use hyper-v isolation it doesn't remove the activation, so I guess we'll use that going forward. That just sucks, since we were hoping to use process isolation instead to save a bit on resources.

I found this post in my searching https://github.com/docker/for-win/issues/4831.
It redirects to https://github.com/moby/moby/issues/40545 where I posted a "me too" reply, since it appears we're not alone with the issue.

**Comment by freddydk** [comment] 2020-10-03 14:07
I am running WIndows 2004 and it doesn't happen for me (anymore)
I remember that it happened for me earlier - although I never linked the activation with docker containers.

**Comment by corsbj** [comment] 2020-10-03 14:14
Ok, so it might get fixed by updating.
Will be a while untill we're on 2004, we'll just run hyper-v isolation I guess.
Thanks for the help!

**Comment by freddydk** [comment] 2020-10-03 16:36
So I guess I learned why a number of my presentations last year was done with Windows not being activated - I had no idea that this was due to containers.
Re the docker thingy - the dump above says:

Docker Client Version is 19.03.5
Docker Server Version is 19.03.5

Are you sure that docker is not installed???
All documentation I can find is that the containers feature is a pre-requisite for docker - not a replacement.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-10-Client

Maybe you have installed docker enterprise?

**Comment by corsbj** [comment] 2020-10-03 17:29
Yes, that's it. Sorry, I'm slow on saturdays :)
We're not using Docker Desktop, we're running Docker Enterprise.

**Comment by freddydk** [comment] 2020-10-04 04:10
You could try to replace Docker Enterprise with Docker Desktop on one machine to see whether that makes a difference.
Docker Enterprise is as far as I know only licensed for Windows Server, maybe that is what is causing the issue.
Just saw that there is also a Docker Desktop Enterprise - don't know what that is.

**Comment by corsbj** [comment] 2020-10-04 08:34
Docker Desktop caused some instability issues that Docker Engine Enterprise (not just Docker Enterprise) didn't, that was the main cause of the switch.
We followed the guide here for installation https://www.kauffmann.nl/2019/03/04/how-to-install-docker-on-windows-10-without-hyper-v/.
I'm actually not sure regarding licensing, that's a very good point. 
In the guide he says it's free, and the fact I can just install it seems to confirm that. I'm never asked for a license file.

**Comment by freddydk** [comment] 2020-10-04 08:43
AJ uses a special script to install something that was intended (and licensed for Windows Server) on Windows 10.
Not sure you can take that as being proof that it is licensed.

I must admit, that I don't know.

BTW FYI Looking at issues with Docker, Windows 10 1903 seems to be over-represented there.

Will close this issue as we seem to know what the problem is.

**Closed by freddydk** 2020-10-04 08:43 UTC

**Comment by thomas-tarp** [comment] 2020-11-11 21:21
Sorry for reopening this one, but my team frequently experiences this as well, and I'm not sure I see what the problem is from reading this issue.

We run Windows Enterprise 10 1909 and use process isolation - it doesn't occur with hyper-v. It seems to only occur sometimes, and only after shutting down while having a container running.

Currently, we use the workaround described in the link above to the issue on Docker for Windows.

**Comment by freddydk** [comment] 2020-11-11 23:27
I also don't know what the problem is in detail, but it is a problem with Docker and Windows 10: https://github.com/moby/moby/issues/40545
I do not have insights into what and why, sorry.
