### ISSUE TITLE
Cannot open 365 BC web client installed on docker

### ISSUE THREAD

**Issue by Waseemdk** [microsoft/navcontainerhelper#546] opened 2019-08-06 09:22 UTC
Hi everyone,
I have updated my windows to window version 1903, windows 10 Enterprise. Docker is version 2.1.0.0 (36874).
I have just created new container and new image using this script using Powershell in Admin mode:

New-NavContainer -accept_eula -containerName "bcsandbox" -auth NavUserPassword -imageName "mcr.microsoft.com/businesscentral/sandbox:dk" -useBestContainerOS -updatehost

I get a status yesterday with container bcsandbox succesfully created. I was also able to use link created on desktop to open 365 BC on Cloud, which means I could log to 365 BC using username and password.
![image](https://user-images.githubusercontent.com/53815948/62527933-57acc600-b83c-11e9-901e-71c361e7319d.png)

I am not able to use same created link on my desktop today. After a while it time out. "ERR_CONNECTION_TIMED_OUT"
I have tried to use several hours to search on Google but I am not able to find an answer.

I just realized that I am not able to ping 172.26.44.51. What happen from yesterday?

Please help or advice which information do you need to assist me.
Thanks

**Comment by freddydk** [comment] 2019-08-06 12:35
What does

docker ps -a

return (should show which containers you have running or stopped)

**Comment by Waseemdk** [comment] 2019-08-06 13:56
It returns:
![image](https://user-images.githubusercontent.com/53815948/62545821-b4bb7280-b862-11e9-8418-36fbd3d98ca1.png)

**Comment by freddydk** [comment] 2019-08-06 13:58
Ok, looks fine, what does

ping bcsandbox

and

docker inspect bcsandbox

return?

**Comment by Waseemdk** [comment] 2019-08-06 14:03
I am not able to Ping as I wrote earlier:
![image](https://user-images.githubusercontent.com/53815948/62546169-4cb95c00-b863-11e9-9935-9f3e75985951.png)

Docker inspect bcsandbox return:
PS C:\WINDOWS\system32> docker inspect bcsandbox
[
    {
        "Id": "ff6388358745fb2646e9ddfe016bce24d050dd5e20e6341ac794471b3ddb3068",
        "Created": "2019-08-05T20:14:42.6179673Z",
        "Path": "powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\\Run\\start.ps1",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 16424,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-08-05T20:14:48.7351183Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2019-08-06T08:22:35.2068578+02:00",
                        "End": "2019-08-06T08:22:39.7781936+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-08-06T08:23:10.531863+02:00",
                        "End": "2019-08-06T08:23:20.6050608+02:00",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (10s)"
                    },
                    {
                        "Start": "2019-08-06T08:23:50.9556053+02:00",
                        "End": "2019-08-06T08:23:53.8596747+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-08-06T08:24:23.9168013+02:00",
                        "End": "2019-08-06T08:24:24.6499028+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-08-06T08:24:54.6604747+02:00",
                        "End": "2019-08-06T08:24:55.2148631+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:1eb66e7f3d2b9f069462fee5fa7e565f0ed46d5f00d97ba39b1cb55014148862",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\ff6388358745fb2646e9ddfe016bce24d050dd5e20e6341ac794471b3ddb3068\\ff6388358745fb2646e9ddfe016bce24d050dd5e20e6341ac794471b3ddb3068-json.log",
        "Name": "/bcsandbox",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\ProgramData\\NavContainerHelper\\14.3.34444.34812-DK-Files:c:\\NAVDVD",
                "c:\\windows\\system32\\drivers\\etc:C:\\driversetc",
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\bcsandbox\\my:C:\\Run\\my"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\ff6388358745fb2646e9ddfe016bce24d050dd5e20e6341ac794471b3ddb3068"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\windows\\system32\\drivers\\etc",
                "Destination": "c:\\driversetc",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\14.3.34444.34812-dk-files",
                "Destination": "c:\\navdvd",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\bcsandbox\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "bcsandbox",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "username=admin",
                "locale=da-DK",
                "databaseInstance=",
                "securePassword=76492d1116743f0423413b16050a5345MgB8ADcAWQBGADEATABZAC8ATwBBAEYAcABWAFAAegArAHUANAB4AC8ALwB2AEEAPQA9AHwANAA3AGEANwAyADYAOAAzADgAZgBiADgAYQBmAGQAZQA0ADkAYwA0AGQANwAzAGEAOABkAGYAZgA4AGYAZgA3ADEAOAA5ADkAZgBiADkAYgBhAGIAOQBmAD
IAYgA3ADkANwA5ADkANQAzADAAMgAwADYAOQAwADUAZABmAGIAYgA=",
                "enableApiServices=Y",
                "useSSL=N",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "removePasswordKeyFile=Y",
                "auth=NavUserPassword",
                "ExitOnError=N",
                "licenseFile=",
                "databaseServer=",
                "accept_eula=Y",
                "COMPLUS_NGenProtectedProcess_FeatureEnabled=0"
            ],
            "Cmd": [
                "powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "mcr.microsoft.com/dynamicsnav:generic-1903",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "DK",
                "created": "201908011052",
                "cu": "update27",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "maintainer": "Dynamics SMB",
                "nav": "",
                "osversion": "10.0.18362.239",
                "platform": "14.0.34724.0",
                "tag": "0.0.9.91",
                "version": "14.3.34444.34812"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ff6388358745fb2646e9ddfe016bce24d050dd5e20e6341ac794471b3ddb3068",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "ff6388358745fb2646e9ddfe016bce24d050dd5e20e6341ac794471b3ddb3068",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "f958d561aea10e14fa2c6b51e1ef077fa0cbd9b1201ac64dc3885d1dd5b91719",
                    "EndpointID": "82ab4d330e60d10d9f29814cdbd3ae2cb5eb31a4cef3e5179a5cac7a43475b2c",
                    "Gateway": "172.26.32.1",
                    "IPAddress": "172.26.44.51",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:22:49:d9",
                    "DriverOpts": null
                }
            }
        }
    }
]

PS C:\WINDOWS\system32>

**Comment by freddydk** [comment] 2019-08-06 15:34
The reason I asked you to ping bcsandbox was to see whether the hosts file had been changed to a different IP address.

What happens if you write 

docker exec -it test cmd

**Comment by freddydk** [comment] 2019-08-06 15:38
what does 

docker version

return?

**Comment by Waseemdk** [comment] 2019-08-06 19:38
> The reason I asked you to ping bcsandbox was to see whether the hosts file had been changed to a different IP address.
> _Thanks for explanation_
> What happens if you write
> 
> docker exec -it test cmd
> 
> (You should get a command prompt inside the container)
> And inside that - you should be able to write ipconfig /all - does that give the same IP address?
This is my result: Maybe I am writing wrong
![image](https://user-images.githubusercontent.com/53815948/62571768-7e95e700-b892-11e9-86bc-516697aa7969.png)

**Comment by Waseemdk** [comment] 2019-08-06 19:43
> what does
> 
> docker version
> 
> return?

Here are the results:
![image](https://user-images.githubusercontent.com/53815948/62572080-388d5300-b893-11e9-9778-fa66371a404c.png)

**Comment by freddydk** [comment] 2019-08-06 19:44
You are not - you are seing the same bug that I am. Trying to make a repro to send to Docker

**Comment by Waseemdk** [comment] 2019-08-06 19:46
> You are not - you are seing the same bug that I am. Trying to make a repro to send to Docker

Please explain what is a repro to send to Docker. I don't understand. What should I do here?

**Comment by freddydk** [comment] 2019-08-06 19:52
You shouldn't do anything.
A repro is a description how the support team in Docker can reproduce the bug and find a solution.

The problem is:
- Create a container
- Restart Windows
- Container is now limbo


I found out that if you stop the container before restarting windows - then you can start the container afterwards - and they work.

**Comment by Waseemdk** [comment] 2019-08-06 20:00
> You shouldn't do anything.
> A repro is a description how the support team in Docker can reproduce the bug and find a solution.
> 
> The problem is:
> 
> * Create a container
> * Restart Windows
> * Container is now limbo
> 
> I found out that if you stop the container before restarting windows - then you can start the container afterwards - and they work.

If I understand correct this means you need to stop container before closing Windows. 
You need to start windows then container again and that will work. 
Is this effective to use container on Docker?
This could be a major issue since a lot of colleague on my workplace has same issue that they cannot reach their containers.
It worries me containers is running, but you cannot ping the ip address. Any explanations?

**Comment by freddydk** [comment] 2019-08-06 20:03
As I see it, this is a bug in Docker Desktop 2.1.0.0
This is obviously not how it is supposed to work.
I don't have any more explanations before I have investigated further.
I will also come with my recommendations as to what I think people should do while waiting for the bug to be fixed.
Right now - I don't know any more than what I have written here.

**Comment by Waseemdk** [comment] 2019-08-06 20:14
> As I see it, this is a bug in Docker Desktop 2.1.0.0
> This is obviously not how it is supposed to work.
> I don't have any more explanations before I have investigated further.
> I will also come with my recommendations as to what I think people should do while waiting for the bug to be fixed.
> Right now - I don't know any more than what I have written here.
> and... - if this worries you - you should be in my shoes...

Docker Desktop 2.1.0.0 is the latest release after using "Check for updates" function on Docker. 
I am very grateful for your great help in clarifying what it might be. It gives some reassurance that I'm not the only one experiencing this error.
Thanks :-)

**Comment by freddydk** [comment] 2019-08-06 20:16
Yes, this is a bug in the latest version
I think every single partner using docker will run into this - that is what worries me.

**Comment by Waseemdk** [comment] 2019-08-06 20:17
Where can you see list about all the bugs discovered by Version. Is there a link?

**Comment by freddydk** [comment] 2019-08-06 20:18
In docker? I don't know

**Comment by Waseemdk** [comment] 2019-08-06 20:30
> In docker? I don't know

Or it could also by on another site... 
or just the latest version bugs...

**Comment by freddydk** [comment] 2019-08-07 05:52
https://freddysblog.com/2019/08/07/zombie-containers-skip-this-build/

**Comment by freddydk** [comment] 2019-08-08 05:43
The issue is tracked here: https://github.com/moby/moby/issues/39623

**Comment by freddydk** [comment] 2019-08-08 17:28
Duplicate of #548

**Closed by freddydk** 2019-08-08 17:28 UTC
Labels: Unrelated to navcontainerhelper, duplicate

**Comment by TrademillSJ** [comment] 2020-10-09 14:13
I'm having a similar issue but I am running 2.4.0.0 client with 19.03.13 engine.  

I used this script to build the docker sandbox environment but when I try to open the Web client it times out and pinging the IP times out as well.

#Use this instead of the other which has ImageName as they are no longer updating the images after July 2020
$artifactUrl = Get-BCArtifactUrl -select Latest
String "P@ssword1" -AsPlainText -Force)
New-NavContainer `
		-accept_eula `
        -containerName "D365BC" `
		-artifactUrl $artifactUrl `
        -Auth NavUserPassword `
		-updateHosts
