### ISSUE TITLE
Initialization of container test failed

### ISSUE THREAD

**Issue by Devango** [microsoft/navcontainerhelper#519] opened 2019-07-14 23:59 UTC
I will be thankful for getting help for below issue while creating nav container.
Used this command :

$additionalParameters = @("-v c:\temp:c:\temp")
New-NavContainer -accept_eula `
                 -containerName "test" `
                 -auth NavUserPassword `
                 -imageName "microsoft/bcsandbox:ca" `
                 -Credential $credential `
                 -additionalParameters $additionalParameters `
                 -licensefile "c:\temp\mylicense.flf"

=========================================
Import License
Your program license has expired.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 151
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container test failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.5\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container test failed

=================================
Checked. License is not expired

**Comment by freddydk** [comment] 2019-07-15 04:53
If you start the exact same container without the license, I assume that it will start.
This error doesn't come from docker - the service tier reports this when trying to import the license and unless the date in the container is set wrong - the license that ends up being imported is expired.
Try to start the container without the license. Then open a prompt in the container using Enter-navcontainer test - inspect the date - exit and use import-navcontainerlicense to import the license.
BTW. I don't think you have to share the folder with the license to the container.
Also BTW - note that images have moved to mcr (https://freddysblog.com/2019/07/14/nav-and-business-central-docker-images-moved-to-microsoft-container-registry/) - not that that makes a difference.

**Comment by Devango** [comment] 2019-07-16 12:54
The problem was with license file, I got new license file and it solved.

But, I tried image : microsoft/bcsandbox:ca which apparently using microsoft/bcsandbox:ca-ltsc2019
and other images
mcr.microsoft.com/businesscentral/sandbox:ltsc2019
mcr.microsoft.com/businesscentral/sandbox:ltsc2016 
Getting warning for all images ,

WARNING: This license is not compatible with this version of Business Central.
WARNING: You are running a container which is 81 days old.
Container is created without errors though can not access any shortcuts
Development envionment says my-test\sqlexpress server cannot be found.
Web/Windows saying server not found.

I am running on windows-10, I will try using other image.

**Comment by freddydk** [comment] 2019-07-16 13:22
You probably need to add -updatehosts

the warnings are by design - you need to specify -accept_outdated in order to state that you allow a container which is older than 90 days to run.
the license warning is because your license is for another BC version.

**Comment by Devango** [comment] 2019-07-16 15:59
Thank you.

I moved forward, With warning extension is created and I can access the container as well.
In visual studio code, I can also download the symbols. Few errors while building regarding some tables are missing and some data is missing.

**Comment by freddydk** [comment] 2019-07-16 16:59
Ok, not sure what you are trying to build but I close this one since you have the container up running

**Closed by freddydk** 2019-07-16 16:59 UTC
