### ISSUE TITLE
Create-AlProjectFolderFromNavContainer : Parameter set cannot be resolved using the specified named parameters

### ISSUE THREAD

**Issue by peterz84** [microsoft/navcontainerhelper#625] opened 2019-09-19 12:23 UTC
After creating a BC container with -includeAL I'm trying to export the base line with the following command:
```
$alProjectFolder = "D:\ProgramData\NavContainerHelper\AL\BaseApp"
Create-AlProjectFolderFromNavContainer -containerName $containerName `
                                       -alProjectFolder $alProjectFolder `
                                       -useBaseLine 
```

Then I'm getting this error message:

```
Create-AlProjectFolderFromNavContainer : Parameter set cannot be resolved using the specified named parameters.
At line:2 char:1
+ Create-AlProjectFolderFromNavContainer -containerName $containerName  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Create-AlProjectFolderFromNavContainer], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Create-AlProjectFolderFromNavContainer
```

I must be overlooking something, but cannot seem to find the error.

**Comment by freddydk** [comment] 2019-09-19 12:24
Duplicate of https://github.com/microsoft/navcontainerhelper/issues/618

**Closed** 2019-09-19 12:24 UTC
