### ISSUE TITLE
Chrome, Firefox, and VS Code force https for a BC container named "dev"

### ISSUE THREAD

**Issue by steveendow** [microsoft/navcontainerhelper#1329] opened 2020-10-02 17:08 UTC
**Describe the issue**
This is not an issue with BcContainerHelper, but is an environmental issue that affects how BC containers are used, which may lead to additional support requests for BcContainerHelper and the AL Language extension.

If I create a BC container named "dev" without https, I am unable to access the container via Chrome and am unable to download symbols from VS Code.

If I attempt to connect to a container named "dev" with this URL:

http://dev/BC/?tenant=default

Both Firefox and Chrome will silently and automatically redirect to https:

https://dev/BC/?tenant=default

The browser will then display a connection timeout error:

![image](https://user-images.githubusercontent.com/11199908/94948784-c0212280-0494-11eb-9c61-0e7f1398a23b.png)

VS Code also fails to connect when trying to download symbols.

![image](https://user-images.githubusercontent.com/11199908/94949494-daa7cb80-0495-11eb-862e-a5584842d1dc.png)

This caused me to spend a few hours trying to troubleshoot the cause.

1. The hosts file is updated properly with the "dev" and "dev-default" entries
2. I can ping the container successfully
3. I can access the dev container by typing the IP address in the address bar of Chrome
4. The container is working fine 

Credit to [Sergio Gayan](https://twitter.com/GayanSergio/status/1311945012519854080?s=20) on Twitter for finding the cause of this behavior, which is a browser security "feature":

https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

I confirmed this issue by opening the http://dev URL in Internet Explorer.  That browser did not redirect me to https and I was able to access the dev container without issue in IE.

To help others avoid this issue, and to help reduce BcContainerHelper and AL Language extension support requests around this issue, I'm wondering if it would be worthwhile to have BcContainerHelper detect the use of the container name "dev" and perhaps issue a warning or require https / certificate install for that particular container name.

However, if Chrome is requiring HSTS, I don't know if that will require additional steps to configure the cert on a dev machine. (HSTS apparently requires that the cert is trusted by the computer hosting Docker)

I am happy to assist with testing any potential solution to address this issue.

**Scripts used to create container and cause the issue**
```
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -country us -select Latest -type Sandbox -version 16.5 
New-BcContainer `
    -accept_eula `
    -containerName "dev" `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -dns "192.168.25.21" `
    -updateHosts `
    -imageName "dev1"
```

**Full output of scripts**
```
Container is created successfully, no errors occur, and the container works fine if accessed by IP address, or from IE.
```

**Comment by freddydk** [comment] 2020-10-02 20:38
I think the problem is, that once a web site has requested https, then that hostname will be marked as "requiring https" in chrome and other newer browsers. I think you can remove the hostname using
https://www.ssl2buy.com/wiki/how-to-clear-hsts-settings-on-chrome-firefox-and-ie-browsers
but there really isn't much we can do in the containerhelper.
Only thing I can think of would be, that if I can detect that HSTS is set on a hostname, I would add -usessl to the container creation - but not sure that it is possible

**Comment by freddydk** [comment] 2020-10-03 05:13
Just tried myself as well.
On my machine dev is also registered for HSTS and I cannot remove it.
if I use -useSSL when creating the container, it is created with a self-signed certificate, but that also gets blocked by Chrome.
worse then - I also cannot download the certifcate from http://dev:8080/certificate.cer because that also uses https.
nor can I use the ip address.
I can however use -useSSL and -installcertificateonhost which will install the container self signed certificate in the trusted root  certification store on your computer (and remove it when removing the container):
![image](https://user-images.githubusercontent.com/10775043/94983967-8c530500-0547-11eb-9ceb-835d92220764.png)

If I ever stumble over a good way to detect HSTS, then I might auto-set these parameters.

**Comment by freddydk** [comment] 2020-10-03 05:28
I might have found a way...
https://hstspreload.com/api/v1/status/dev

will actually return whether the domain is in the hsts preload list (meaning: Will always be https and you cannot remove it locally).

Will try to add this to next preview of new-bccontainer (subject for removal if it causes issues)

**Comment by freddydk** [comment] 2020-10-03 05:35
```
$hsts = (New-Object System.Net.WebClient).DownloadString('https://hstspreload.com/api/v1/status/dev') | ConvertFrom-Json
if (($hsts.chrome) -or ($hsts.firefox) -or ($hsts.tor)) {
   Write-Host "HSTS preloaded"
}
```

**Comment by freddydk** [comment] 2020-10-03 05:36
This doesn't detect whether you have some domain, which has added itself to the list, but it should give an indication if you are trying to use a name, which will never work.

**Comment by steveendow** [comment] 2020-10-03 17:10
Very cool!  I think a warning or a log entry that gives an indicator about the potential issue would be great.  Thanks!

**Comment by freddydk** [comment] 2020-10-07 06:14
I will close this issue with the warning added.

**Closed by freddydk** 2020-10-07 06:14 UTC
Labels: Unrelated to navcontainerhelper
