### ISSUE TITLE
Font issue with bc15 conteiner fonts

### ISSUE THREAD

**Issue by worldofthenavcraft** [microsoft/navcontainerhelper#830] opened 2020-02-04 08:28 UTC
Hello Freddy,
I hope you have time to help me out. I create container like this:

``New-BCContainer `
    -accept_eula `
    -accept_outdated `
    -containerName $containerName `
    -imageName $imageName `
    -updateHosts `
    -auth 'NavUserPassword' `
    -Credential $credential `
    -shortcuts $shortcuts `
    -bakFile $BakFile
    
Import-NavContainerLicense `
    -containerName $containerName `
    -licenseFile $LicenseFileDev``

As result I have docker up and running but reports looks like 80-s comming back :) Please see picture.
![image](https://user-images.githubusercontent.com/38262971/73726616-8ac30a00-4738-11ea-8ca3-cb23d066d2eb.png) 

On the left you see font issue. On the Right it 's OK. Plese advise. I am using Chrome. I got same result wiht IE as well.

********* Log of container creation. Symbols **** used to hide some sentsitive data
Running as *****
Checking permissions to C:\ProgramData\NavContainerHelper
**** has the right permissions to C:\ProgramData\NavContainerHelper
Checking permissions to C:\WINDOWS\System32\drivers\etc\hosts
**** has the right permissions to C:\WINDOWS\System32\drivers\etc\hosts
Checking permissions to docker commands
**** has the right permissions to run docker commands
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
NavContainerHelper is version 0.6.2.6
Host is Microsoft Windows 10 Enterprise - Unknown/Insider build
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image mcr.microsoft.com/businesscentral/onprem:1910-cu1-w1-ltsc2019
Removing container ****
Removing **** from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\vkg-dev15-w1
Downloading C:\ProgramData\NavContainerHelper\Extensions\vkg-dev15-w1\database.bak
Creating Container ****
Version: 15.1.37881.38071-W1
Platform: 15.0.37898.0
Generic Tag: 0.0.9.96
Container OS Version: 10.0.17763.805 (ltsc2019)
Host OS Version: 10.0.18363.592 (Unknown/Insider build)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\vkg-dev15-w1\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- updatehosts.ps1
Creating container ****  from image mcr.microsoft.com/businesscentral/onprem:1910-cu1-w1-ltsc2019
5f7af251cc9c929cf8a7db9b7a00a4897964d6d9d29b98967ee668cf3e4415e6
Waiting for container ****  to be ready
Initializing...
Starting Container
Hostname is ****
PublicDnsName is ****
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'C:\ProgramData\NavContainerHelper\Extensions\**** \database.bak'
Creating Self Signed Certificate
Self Signed Certificate Thumbprint ****
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
Creating **** as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.23.162.193
Container Hostname  : ****
Container Dns Name  : **** 
Web Client          : http://**** /BC/
Dev. Server         : http:// ****
Dev. ServerInstance : BC

**Comment by freddydk** [comment] 2020-02-04 11:35
Duplicate of issue #515 
The workaround is described there (use Add-FontsToBcContainer)

**Comment by worldofthenavcraft** [comment] 2020-02-04 14:49
I run command like this: (on host side)

`Add-FontsToNavContainer -containerName $ContainerName -path "C:\Windows\Fonts\Segoe UI\segoeui.ttf" -verbose`

Still no effect for report. I open it as user with web client. 

If i look fonts dir inside container then I see only lucon.ttf

**Comment by freddydk** [comment] 2020-02-04 14:51
What was the output of that command?

**Comment by worldofthenavcraft** [comment] 2020-02-04 14:52
empty line :)

**Comment by freddydk** [comment] 2020-02-04 14:55
Your path parameter is wrong (it will display something when adding fonts) - open a command prompt and look in c:\windows\fonts - I don't think there are subfolders.
You can also add all fonts by removing the path parameter - but it takes time.

**Comment by worldofthenavcraft** [comment] 2020-02-04 15:09
It -s working. Thanks!

`Add-FontsToNavContainer -containerName $ContainerName -path "C:\Windows\Fonts\segoeui.ttf" -verbose`

Solution described in issue #515 by @AbhishekPrajapati is not correct:
use can use the "Add-FontsToNavContainer" from NavContainerhelper for example like this
Add-FontsToNavContainer -containerName $ContainerName -path "c:\windows\fonts\Arial\arial.ttf" -verbose

I suggsest to improve documentation at https://github.com/microsoft/navcontainerhelper/blob/master/NavContainerHelper.md

**Closed** 2020-04-08 06:43 UTC
Labels: Fix Ready, question
