### ISSUE TITLE
Error in CI - Publish/Sign-App: "application" instead of Dependencies 

### ISSUE THREAD

**Issue by aptMattKoe** [microsoft/navcontainerhelper#996] opened 2020-05-20 08:01 UTC
**Describe the issue**
After some changes for other processes there appears an error in the build:
![image](https://user-images.githubusercontent.com/57363453/82420481-0cd50580-9a80-11ea-89c7-cc01798bc73f.png)

But the signing step was successfull:
![image](https://user-images.githubusercontent.com/57363453/82420527-1fe7d580-9a80-11ea-9e90-8015c2a735d7.png)

**Additional context**
I have also have the reason (like in the title announced). I have changed the manuall dependencies to the "application" property:
From:
![image](https://user-images.githubusercontent.com/57363453/82427037-dc459980-9a88-11ea-9bd3-ba984ab5381a.png)

To:
![image](https://user-images.githubusercontent.com/57363453/82420677-5887af00-9a80-11ea-9b00-b304939d163a.png)

Docs to that: 
![image](https://user-images.githubusercontent.com/57363453/82420710-62a9ad80-9a80-11ea-83e3-f69c040a15ca.png)
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files

After step back to manual dependecies all works fine again.

Could you reproduce that? Or did I get something wrong?

Kind regards,
Matthias

**Comment by freddydk** [comment] 2020-05-20 08:42
My app.json looks like this

https://dev.azure.com/businesscentralapps/_git/BingMaps?path=%2Fapp%2Fapp.json

and works fine - not sure what could be the cause of this.

**Comment by aptMattKoe** [comment] 2020-05-20 08:59
mh, I'll try that in another project later!
I could reproduce it in that one.
I've more than this dependency. Could it be that?

**Comment by freddydk** [comment] 2020-05-20 09:01
That is very normal - I think the not-normal thing is to have none.
I will wait to see if other people have experienced the same.

**Comment by freddydk** [comment] 2020-05-24 05:14
Did you resolve the issue?

**Comment by aptMattKoe** [comment] 2020-05-25 06:05
Currently I could not check another repo :/ sorry.
I will do this this week! :)

**Comment by aptMattKoe** [comment] 2020-05-29 06:41
I wanted to do it this week. But the week was a bit stressful so I couldn't test it.
Sorry for that. I think it will be a problem with my repo :/ 
If you want, I could close it.

**Comment by rvanbekkum** [comment] 2020-06-11 19:30
This was an issue with the "application" property: if your app uses the "application" property, then BC will complain about the app not being signed even though it is. This bug is present in the 16.0 version of Business Central and is resolved with 16.1 and up.

(See also this yammer topic for further info: https://www.yammer.com/dynamicsnavdev/threads/598313698058240)

**Comment by aptMattKoe** [comment] 2020-06-12 06:00
wow, thanks for your help! :)
good to know!

**Closed** 2020-06-24 11:28 UTC
Labels: Cannot repro
