### ISSUE TITLE
Cannot index into a null array.

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#2095] opened 2021-09-28 10:56 UTC
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Error when trying to create a  clean 2016 image.

**Scripts used to create container and cause the issue**
$containerName = 'basic16-1'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2016' -cu '1' -country 'dk'
$licenseFile = 'd:\nav\infar\udvikling\nav2016.flf'
New-BcContainer -shortcuts DesktopFolder `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -updateHosts

**Full output of scripts**
PS C:\WINDOWS\system32> $containerName = 'basic16-1'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2016' -cu '1' -country 'dk'
$licenseFile = 'd:\nav\infar\udvikling\nav2016.flf'
New-BcContainer -shortcuts DesktopFolder `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -updateHosts
Default parameter Isolation = Process
BcContainerHelper is version 2.0.15
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 21H1
Docker Client Version is 20.10.7
Docker Server Version is 20.10.7
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1 images are not yet available, use 2004 as these are found to work better than 20H2 on 21H1
Using image mcr.microsoft.com/businesscentral:10.0.19041.1237
Creating Container basic16-1
Version: 9.0.43402.0-dk
Style: onprem
Multitenant: No
Platform: 9.0.43402.0
Generic Tag: 1.0.1.7
Container OS Version: 10.0.19041.1237 (2004)
Host OS Version: 10.0.19043.1237 (21H1)
Using Process isolation
Using locale da-DK
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file d:\nav\infar\udvikling\nav2016.flf
Files in D:\BcContainerHelper\Extensions\basic16-1\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container basic16-1 from image mcr.microsoft.com/businesscentral:10.0.19041.1237
58bdb308b0a47edf85e60027761c177253f65ac829032156ea7992dcc68ff45f
Waiting for container basic16-1 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/9.0.43402.0/dk
Using installer from C:\Run\90
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Using artifactUrl https://bcartifacts.azureedge.net/onprem/9.0.43402.0/dk
Using installer from 
Unexpected restart during artifact copy, retrying...
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copying Installers
Copying TestToolKit
Copying UpgradeToolKit
Installing NAV
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Initializing...
Setting host.docker.internal to 192.168.2.200 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.2.200 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.25.112.1 in container hosts file
Starting Container
Hostname is basic16-1
PublicDnsName is basic16-1
Using NavUserPassword Authentication
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Cannot index into a null array.
at <ScriptBlock>, C:\Run\navstart.ps1: line 109
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/onprem/9.0.43402.0/dk
Using installer from C:\Run\90
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Using artifactUrl https://bcartifacts.azureedge.net/onprem/9.0.43402.0/dk
Using installer from 
Unexpected restart during artifact copy, retrying...
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copying Installers
Copying TestToolKit
Copying UpgradeToolKit
Installing NAV
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Initializing...
Setting host.docker.internal to 192.168.2.200 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.2.200 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.25.112.1 in container hosts file
Starting Container
Hostname is basic16-1
PublicDnsName is basic16-1
Using NavUserPassword Authentication
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Cannot index into a null array.
at <ScriptBlock>, C:\Run\navstart.ps1: line 109
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1
Initialization of container basic16-1 failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.15\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...asic16-1 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container basic16-1 failed

**Additional context**
- does it happen all the time? Yes. Also tried creating a bc18 image, however that fails with a different error.
$containerName = 'bc18-1'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '18.1' -country 'dk'
$licenseFile = 'd:\nav\infar\udvikling\bc18.flf'
New-BcContainer -shortcuts DesktopFolder `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -updateHosts
    
**BC18 script end**
  WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 99F575EF7B0D5677A1938C32E55FBA08480AA89C
Modifying Service Tier Config File with Instance Specific Settings
Service Tier doesn't exist / is not installed
at <ScriptBlock>, C:\Run\navstart.ps1: line 153
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1
Initialization of container bc18-1 failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.15\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r bc18-1 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bc18-1 failed

**Comment by freddydk** [comment] 2021-09-29 04:54
This is another case of #2086 
I can see that it starts the initializing step again in the middle of copying files - for some reason, the container restarts...
Will close this and continue the thread on the other - this one just proves that this isn't caused by Docker 4.0.1 - it is caused by Windows update (which I also have - but I don't have the problem???)

**Closed** 2021-09-29 04:54 UTC
Labels: duplicate
