### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by larswestman** [microsoft/navcontainerhelper#861] opened 2020-02-20 21:12 UTC
After the February Windows update I reverted back to hyper-v. It almost works. My host has the timezone "Västeuropa, normaltid" and when the container starts I get this warning:

WARNING: Container starts with TimeZone = VÃ¤steuropa, normaltid, which is not recognized in the list of TimeZones.

This gives an error later on when I include the test toolkit and use Run-TestsInBCContainer

Here's the output from a container creation without the test toolkit (otherwise it's all the same):

$containerName  = 'timezone'
$licenseFile = "C:\license\dev.flf"
$password = ConvertTo-SecureString -String "P@ssword" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "admin", $password
docker login "bcinsider.azurecr.io" -u "The User" -p "The password"

New-NavContainer `
    -Credential $credential `
    -accept_eula `
    -accept_outdated `
    -containerName $containerName `
    -auth NAVUserPassword `
    -imageName $image `
    -updateHosts `
    -licenseFile $licenseFile `
    -alwaysPull `
    -doNotCheckHealth `
    -EnableTaskScheduler:$false

Login Succeeded
NavContainerHelper is version 0.6.4.26
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1909
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Pulling image bcinsider.azurecr.io/bcsandbox:se-ltsc2019
se-ltsc2019: Pulling from bcsandbox
Digest: sha256:704e59f0a668bd3c8e299f521709358245a6415032624077294ddecb534c5e34
Using image bcinsider.azurecr.io/bcsandbox:se-ltsc2019
Disabling Health Check (always report healthy)
Removing container timezone
Removing timezone from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\timezone
Creating Container timezone
Version: 15.4.40911.0-se
Style: sandbox
Platform: 15.0.40882.0
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.18363.657 (1909)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale sv-SE
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\license\dev.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\timezone\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1

Creating container timezone from image bcinsider.azurecr.io/bcsandbox:se-ltsc2019
2dd50ec1ba85d32e4a062e84a564f22fc7aef9ea35d8acf3fc5fa1c385902b38
Waiting for container timezone to be ready
Initializing...
Setting host.docker.internal to 192.168.1.188 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.188 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.20.240.1 in container hosts file
Starting Container
Hostname is timezone
PublicDnsName is timezone
WARNING: Container starts with TimeZone = VÃ¤steuropa, normaltid, which is not recognized in the list of TimeZones.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint D1729721DD3DB323291697C454FA13C635A0D150
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to False
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.20.251.179
Container Hostname  : timezone
Container Dns Name  : timezone
Web Client          : http://timezone/BC/
Dev. Server         : http://timezone
Dev. ServerInstance : BC
Setting timezone to 172.20.251.179 in host hosts file

Files:
http://timezone:8080/al-4.0.235372.vsix

Initialization took 57 seconds
Ready for connections!
Reading CustomSettings.config from timezone
Creating Desktop Shortcuts for timezone
Container timezone successfully created

**Comment by freddydk** [comment] 2020-02-20 22:01
Do you know how I can create a VM on Azure, which repros this?
I have tried to create various machines, but failed to repro this issue:-(

**Comment by larswestman** [comment] 2020-02-20 22:11
Hi,

Unfortunately not.

I guess you would have to use a Swedish locale to get the “ä” in the time zone name. It seems as the issue is the Swedish character in the time zone name.

I’ve tried various ways to set the timezone. Using the timezone switch for new-navcontainer gives the same error and using docker exec $containerName powershell "tzutil /s 'UTC'" or docker exec $containerName powershell "Set-TimeZone 'UTC'" gives permission errors


/Lars

Från: Freddy Kristiansen <notifications@github.com>
Skickat: den 20 februari 2020 23:02
Till: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Kopia: Lars Westman <lars@goprowe.se>; Author <author@noreply.github.com>
Ämne: Re: [microsoft/navcontainerhelper] Timezone error (#861)


Do you know how I can create a VM on Azure, which repros this?
I have tried to create various machines, but failed to repro this issue:-(

**Comment by freddydk** [comment] 2020-02-21 10:04
Just to confirm, the only problem you have with this warning - is that that you cannot run tests in the container, right?

**Comment by freddydk** [comment] 2020-02-21 10:11
I haven't removed the warning, but I have fixed Get/Run-Tests here https://github.com/microsoft/navcontainerhelper/commit/c49d0b669825f126c0e3816976cbabc17fc931ed

**Comment by freddydk** [comment] 2020-02-21 10:11
Duplicate of #858

**Closed by freddydk** 2020-02-21 10:11 UTC
Labels: duplicate
