### ISSUE TITLE
Get-AppSourceProduct returns 404 Not Found

### ISSUE THREAD

**Issue by catadumitru** [microsoft/navcontainerhelper#3151] opened 2023-08-10 13:31 UTC
**Describe the issue**
I'm getting an error when trying to get all AppSource product offers to then create a new submission based on offer name.

I could go around this at the moment by hardcoding the productID.
Get-AppSourceProduct -authContext $authcontext -productId $productId -includeAll

It was working fine last week.

**Scripts used to create container and cause the issue**
```
$authcontext = New-BcAuthContext `
    -clientID $PartnerCenterAppAPIClientId `
    -clientSecret $PartnerCenterAppAPIClientSecret `
    -tenantID $ENV:tenantId `
    -scopes "https://api.partner.microsoft.com/.default"
    
$products = Get-AppSourceProduct -authContext $authcontext -silent
$productId = ($products | Where-Object { $_.name -eq $productName }).id 
```

**Full output of scripts**
```
$authcontext = New-BcAuthContext `
    -clientID $PartnerCenterAppAPIClientId `
    -clientSecret $PartnerCenterAppAPIClientSecret `
    -tenantID $ENV:tenantId `
    -scopes "https://api.partner.microsoft.com/.default"
Attempting authentication to https://api.partner.microsoft.com/.default using clientCredentials...
Authenticated as app 1234e5b6-e959-4341-bfdc-1e1505c3256a
$products = Get-AppSourceProduct -authContext $authcontext
Attempting authentication to https://api.partner.microsoft.com/.default using clientCredentials...
Authenticated as app 1234e5b6-e959-4341-bfdc-1e1505c3256a
GET https://api.partner.microsoft.com/v1.0/ingestion/products
GET https://api.partner.microsoft.com/v1.0/ingestion/products?$skipToken=eyJMYXN0SWQiOiJbe1widG9rZW5cIjpudWxsLFwicmFuZ2VcIjp7XCJtaW5cIjpcIjA1QzFDOUNENjczMzkwXCIsXCJtYXhcIjpcIk
ZGXCJ9fV0iLCJTb3VyY2UiOiJEb2NXXXXX
GET https://api.partner.microsoft.com/v1.0/ingestion/products?$skipToken=eyJMYXN0SWQiOiJbe1widG9rZW5cIjpudWxsLFwicmFuZ2VcIjp7XCJtaW5cIjpcIjA1QzFEMzk5Q0Q2NzJDXCIsXCJtYXhcIjpcIj
A1QzFEOUNENjczMzkwXCJ9fV0iLCJTb3VyY2UiOiJEb2NXXXXX
GET https://api.partner.microsoft.com/v1.0/ingestion/products?$skipToken=eyJMYXN0SWQiOiJbe1widG9rZW5cIjpudWxsLFwicmFuZ2VcIjp7XCJtaW5cIjpcIjA1QzFFMzk5Q0Q2NzJDXCIsXCJtYXhcIjpcIk
ZGXCJ9fV0iLCJTb3VyY2UiOiJEb2NXXXXX
GET https://api.partner.microsoft.com/v1.0/ingestion/products?$skipToken=eyJMYXN0SWQiOiJbe1widG9rZW5cIjpudWxsLFwicmFuZ2VcIjp7XCJtaW5cIjpcIjA1QzFFOUNENjczMzkwXCIsXCJtYXhcIjpcIk
ZGXCJ9fV0iLCJTb3VyY2UiOiJEb2NXXXXX
Get-AppSourceProduct Telemetry Correlation Id: 0a4782b2-19d6-4804-aa1a-a6ca82cddd5e
The remote server returned an error: (404) Not Found.
Not Found
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.14\AppSource\Invoke-IngestionAPI.ps1:69 char:17
+                 throw (GetExtendedErrorMessage $_)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The remote serv...d.
Not Found
:String) [], RuntimeException
    + FullyQualifiedErrorId : The remote server returned an error: (404) Not Found.
Not Found
```

**Comment by freddydk** [comment] 2023-08-11 04:03
so, you are saying that this works:
`Get-AppSourceProduct -authContext $authcontext -productId $productId -includeAll
`and this doesn't:
`Get-AppSourceProduct -authContext $authcontext`
???

**Comment by freddydk** [comment] 2023-08-11 04:08
You are running BcContainerHelper version 4.0.14 - please upgrade to the latest version and check there.
Just tested here and I get all our 198 products with that command.

**Comment by catadumitru** [comment] 2023-08-11 06:52
> so, you are saying that this works: `Get-AppSourceProduct -authContext $authcontext -productId $productId -includeAll ` and this doesn't: `Get-AppSourceProduct -authContext $authcontext` ???

Yes, it's very strange.
We have 4 offers, 1 published, 2 drafts and 1 Not available in Marketplace. - but this hasn't changed in weeks/months.

Just tried now with version 5.0.5, got the same error.
Get-AppSourceProduct Telemetry Correlation Id: a669b830-fcd7-4b83-b05d-3398fff5bea7

**Comment by freddydk** [comment] 2023-08-11 09:22
@lktraser  - did you try to specify a productId and see if it works then?

**Comment by freddydk** [comment] 2023-08-11 09:23
I cannot repro the problem - I might need to get clientID + secret from somebody to be able to repro and see what is happening.

**Comment by lktraser** [comment] 2023-08-11 09:24
> @lktraser - did you try to specify a productId and see if it works then?

It works if I use the productID. But I'm using this script to generically get the productID. I guess I would replace it by using a pipeline variable instead.

**Comment by freddydk** [comment] 2023-08-11 09:37
It might be that the ingestion API team has published a new version, but I cannot repro the problem myself.
I cannot repro with my own creds - if I am to investigate, I will need to borrow secrets from one of you?

**Comment by catadumitru** [comment] 2023-08-11 10:52
Sent credentials by mail :)

**Comment by mishof** [comment] 2023-08-11 12:51
We have been experiencing the same issue. We use azure devops to publish to the appstore. Last week it was working fine for all of our products, but since the beginning of this week it has stopped working:

2023-08-11T06:46:16.0311845Z BcContainerHelper version 5.0.5
2023-08-11T06:46:16.5296220Z BC.HelperFunctions emits usage statistics telemetry to Microsoft
2023-08-11T06:46:22.9335843Z Attempting authentication to https://api.partner.microsoft.com/.default using clientCredentials...
2023-08-11T06:46:23.1049406Z Authenticated as app b50ef91f-00e1-42c8-812e-11bb13027777
2023-08-11T06:46:26.4816322Z Get-AppSourceProduct Telemetry Correlation Id: 75262fc6-9116-433b-a792-19d450e1a676
2023-08-11T06:46:26.5581611Z The remote server returned an error: (404) Not Found.
2023-08-11T06:46:26.5581826Z Not Found
2023-08-11T06:46:26.5583227Z At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.5\AppSource\Invoke-IngestionAPI.ps1:69 char:17
2023-08-11T06:46:26.5583555Z +                 throw (GetExtendedErrorMessage $_)
2023-08-11T06:46:26.5583720Z +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-08-11T06:46:26.5584109Z     + CategoryInfo          : OperationStopped: (The remote serv...d.
2023-08-11T06:46:26.5584486Z Not Found
2023-08-11T06:46:26.5585320Z :String) [], RuntimeException
2023-08-11T06:46:26.5585525Z     + FullyQualifiedErrorId : The remote server returned an error: (404) Not Found.
2023-08-11T06:46:26.5585968Z Not Found

**Comment by PeterDurrer** [comment] 2023-08-11 14:54
We have the same problem, I am analyzing the code and I got nextlink on the last response of the Invoke-IngestionApiGetCollection function in the while loop, but I have all the products. We have a lib app that is not included in the responses result set. So can it be that the API provides a nextlink for the lib app, but the lib app cannot or is not allowed to be read?

Or is other bug in api answer with a too much nextlink.

**Comment by freddydk** [comment] 2023-08-12 05:05
I think this is a bug in the API - it returns an invalid nextlink (it returns offers, not apps)
I have a repro from a partner (Thanks), I can see that the products are returned 1 and 1 and 1 and 1 = 4 - only one product per call - @PeterDurrer  is that the same you see?
When I use my own ClientId and Secret - I get 23,25,28,14,19,25,18,16,10,20 = 198 - seems totally random (although consistently random).
But... if there is one thing I learned from working with computers, things should not be random`ish

I will make a patch for this error in the ContainerHelper - basically if I get a nextlink, which returns 404, I assume that this was the end of the collection.

It will be available in a preview as soon as this PR is merged https://github.com/microsoft/navcontainerhelper/pull/3155

You can see the fix here: https://github.com/freddydk/navcontainerhelper/blob/master/AppSource/Invoke-IngestionAPI.ps1

**Comment by freddydk** [comment] 2023-08-12 07:04
Fix should be available in latest preview now.

**Comment by PeterDurrer** [comment] 2023-08-12 10:44
> 
Hello @freddydk thank you for temporary fixing i have write a litte Test for the API you can show in the Attachment.
[APITest.txt](https://github.com/microsoft/navcontainerhelper/files/12327170/APITest.txt)

The Answer of this script look like this
![image](https://github.com/microsoft/navcontainerhelper/assets/116004093/5cdd392a-b2d8-401a-a7aa-af134e03b9ea)

so i get  Answer packages 2+1+3+2+2+2=12
we have 12 products available in AppSource and 1 Library App.

I think the last call of the API should not contain a nextlink, but it does.

**Comment by freddydk** [comment] 2023-08-13 21:40
When you say you have a library app - then that is uploaded as a library app to one or more of the marketplace offers right?
In partner center - you have 12 marketplace offers - right?
These offers are what is returned by the function.

**Comment by mishof** [comment] 2023-08-14 07:01
Good Morning Freddy,

Thanks for helping us!
I set up the preview but there seems to be a bug in it:

2023-08-14T06:49:04.3948487Z BcContainerHelper version 5.0.6-preview1063
2023-08-14T06:49:05.0216755Z BC.HelperFunctions emits usage statistics telemetry to Microsoft
2023-08-14T06:49:14.4533416Z Attempting authentication to https://api.partner.microsoft.com/.default using clientCredentials...
2023-08-14T06:49:14.7051850Z Authenticated as app b50ef91f-00e1-42c8-812e-11bb13027777
2023-08-14T06:49:17.5876522Z WARNING: Ingestion API returned an invalid nextlink, ignoring...
2023-08-14T06:49:18.0355751Z @{resourceType=AzureDynamics365BusinessCentral; name=Exsion for Dynamics Business Central; externalIDs=System.Object[]; isModularPublishing=True; id=7f47c5a6-fa55-4885-8627-9f5befb3f09f} @{resourceType=AzureDynamics365BusinessCentral; name=hbconstructionsupply-bc; externalIDs=System.Object[]; isModularPublishing=True; id=acf935f3-127d-4499-9c8c-6ff8fb55ce25} @{resourceType=AzureDynamics365BusinessCentral; name=smarttrade-bc; externalIDs=System.Object[]; isModularPublishing=True; id=2dc264f7-8e25-45de-9f65-12f6ffa1b630} @{resourceType=AzureDynamics365BusinessCentral; name=hbrealestate-bc; externalIDs=System.Object[]; isModularPublishing=True; id=fe6892a3-86cd-4396-935c-b71a75096f92} @{resourceType=AzureDynamics365BusinessCentral; name=hbrealestate-bc-nl; externalIDs=System.Object[]; isModularPublishing=True; id=43544403-780b-4577-a5c8-1251dab7db42}
2023-08-14T06:49:18.0363497Z C:\azagent\A1\_work\r9\a\_SmartTrade Base\drop\HB Software_SmartTrade_20.0.1.360.app
2023-08-14T06:49:18.0372223Z C:\azagent\A1\_work\r9\a\_HB Library\drop\HB Software_HB Software Core_20.0.0.181.app
2023-08-14T06:49:18.0657573Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630
2023-08-14T06:49:18.3542615Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/setup
2023-08-14T06:49:18.7030965Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/branches/getByModule(module=Availability)
2023-08-14T06:49:20.1305578Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/productavailabilities/getByInstanceID(instanceID=2152924500010335141)
2023-08-14T06:49:20.6173275Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/featureavailabilities/getByInstanceID(instanceID=2152924500010335141)
2023-08-14T06:49:21.3232075Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/branches/getByModule(module=Property)
2023-08-14T06:49:21.7841614Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/properties/getByInstanceID(instanceID=b0bc8bdf-3126-a15a-a173-7be9a352d32c)
2023-08-14T06:49:22.1413111Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/branches/getByModule(module=Listing)
2023-08-14T06:49:22.4671234Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/listings/getByInstanceID(instanceID=498899c9-1e39-68a4-0ba9-3a8a873b2009)
2023-08-14T06:49:22.8361884Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/listings/4d9b0149-831e-04fc-ca73-a6b04ab2a902/assets
2023-08-14T06:49:23.2392236Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/listings/4d9b0149-831e-04fc-ca73-a6b04ab2a902/images
2023-08-14T06:49:23.6224222Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/listings/4d9b0149-831e-04fc-ca73-a6b04ab2a902/videos
2023-08-14T06:49:24.1684005Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/branches/getByModule(module=Package)
2023-08-14T06:49:25.0492463Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/packageconfigurations/getByInstanceID(instanceID=e2c818de-861b-45e6-906e-51a693273d12)
2023-08-14T06:49:25.4812323Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/packages/1aa7e0e2-0775-4e56-95b2-33d6447237b2
2023-08-14T06:49:26.9562194Z GET https://api.partner.microsoft.com/v1.0/ingestion/products/2dc264f7-8e25-45de-9f65-12f6ffa1b630/packages/32f1a795-f55f-4b91-9269-025043a6ca88
2023-08-14T06:49:30.1341421Z Extracting C:\azagent\A1\_work\r9\a\_SmartTrade Base\drop\HB Software_SmartTrade_20.0.1.360.app
2023-08-14T06:49:52.2512085Z WARNING: Upcoming breaking changes in the cmdlet 'New-AzStorageContext' :
2023-08-14T06:49:52.2512449Z 
2023-08-14T06:49:52.2512886Z - The parameter : 'SasToken' is changing.
2023-08-14T06:49:52.2513077Z 
2023-08-14T06:49:52.2513627Z - Change description : The SAS token in created Storage context properties 'ConnectionString' and 
2023-08-14T06:49:52.2514319Z 'StorageAccount.Credentials' won't have the leading question mark '?' in a future release. 
2023-08-14T06:49:52.2514519Z 
2023-08-14T06:49:52.2514982Z - The change is expected to take effect from Az version : '11.0.0'
2023-08-14T06:49:52.2515197Z 
2023-08-14T06:49:52.2515637Z - The change is expected to take effect from version : '6.0.0'
2023-08-14T06:49:52.2515796Z 
2023-08-14T06:49:52.2516389Z Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other 
2023-08-14T06:49:52.2516794Z information on breaking changes in Azure PowerShell.
2023-08-14T06:51:55.3834349Z New-AppSourceSubmission Telemetry Correlation Id: 951912c9-fd53-4fb2-87ee-bc14fb4a406b
2023-08-14T06:51:55.4840562Z Invoke-IngestionApiRestMethod : The term 'elseif' is not recognized as the name of a cmdlet, function, script file, or 
2023-08-14T06:51:55.4842252Z operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try ag
2023-08-14T06:51:55.4842476Z ain.
2023-08-14T06:51:55.4842932Z At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.6\AppSource\Invoke-IngestionAPI.ps1:315 char:5
2023-08-14T06:51:55.4843452Z +     Invoke-IngestionApiRestMethod -authContext $authContext -method P ...
2023-08-14T06:51:55.4843677Z +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-08-14T06:51:55.4844091Z     + CategoryInfo          : ObjectNotFound: (elseif:String) [Invoke-IngestionApiRestMethod], CommandNotFoundExceptio 
2023-08-14T06:51:55.4844291Z    n
2023-08-14T06:51:55.4844607Z     + FullyQualifiedErrorId : CommandNotFoundException,Invoke-IngestionApiRestMethod
2023-08-14T06:51:55.4844779Z  
2023-08-14T06:51:55.6108720Z ##[error]PowerShell exited with code '1'.
2023-08-14T06:51:55.6561111Z ##[section]Finishing: PowerShell Script

**Comment by freddydk** [comment] 2023-08-16 04:52
Have submitted a fix for this - should be in preview a little later today

**Comment by PeterDurrer** [comment] 2023-08-16 07:09
> When you say you have a library app - then that is uploaded as a library app to one or more of the marketplace offers right? In partner center - you have 12 marketplace offers - right? These offers are what is returned by the function.

Hy Freddy yes we have 12 that can be installed direct by AppSource marketplace and 1 library that automatical installed by the marketplace offers. The library we uploaded allways with the parammeter -libraryAppFiles from the cmd New-AppSourceSubmission.

**Comment by freddydk** [comment] 2023-08-16 07:55
The API returns marketplace offers - not apps.
Several offers have multiple library apps, so yes - this is by design.

**Comment by mishof** [comment] 2023-08-16 12:04
Hi Freddy,

Thanks for fixing the preview.
It is working fine now.

**Closed** 2024-02-02 08:19 UTC
Labels: bug, Fix Ready, Ships in a future version, Unrelated to BcContainerHelper
