### ISSUE TITLE
Container Fails with missing folder

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/navcontainerhelper#2139] opened 2021-10-18 11:51 UTC
**Describe the issue**
The BC18 containers fail consistently because of this error:
> Cannot find path 'C:\dl\onprem\18.6.30510.0\platform\WindowsPowerShellScripts\Cloud\' because it does not exist.
This might be related to https://github.com/microsoft/navcontainerhelper/issues/2086

**Scripts used to create container and cause the issue**
```
new-BCcontainer -accept_eula 
  -containerName $ContainerName 
  -artifactUrl $ArtifactUrl 
  -memory $Memory 
  -licenseFile $LicenseFilePath 
  -auth NavUserPassword 
  -accept_outdated 
  -updateHosts 
  -alwaysPull 
```
**Full output of scripts**
```
BcContainerHelper is version 2.0.15
BcContainerHelper is not running as administrator
Host is Microsoft Windows 11 Pro - Unknown/Insider build
Docker Client Version is 20.10.7
Docker Server Version is 20.10.8
Removing container SKM186
Removing SKM186 from container hosts file
Removing SKM186-* from container hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\SKM186
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.20348.288
10.0.20348.288: Pulling from businesscentral
Digest: sha256:b9cdc5a4ece3317892d5bac3479c650f1d61548ee803aff30fcd887f69360548
Using image mcr.microsoft.com/businesscentral:10.0.20348.288
Creating Container SKM186
Version: 18.6.30510.0-de
Style: onprem
Multitenant: No
Platform: 18.0.30479.0
Generic Tag: 1.0.1.8
Container OS Version: 10.0.20348.288 (unknown)
Host OS Version: 10.0.22000.194 (Unknown/Insider build)
WARNING: Host OS and Base Image Container OS doesn't match, defaulting to hyperv. If you do not have Hyper-V installed or you encounter issues, you could try to specify -isolation process
Using hyperv isolation
Using locale de-DE
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Users\tillmannj\SHB Business Solutions GmbH\SHB Business Solutions GmbH - General\Lizenzen\NAV & BC\BC 18\20210913_4805364-BC18_150User.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\SKM186\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container SKM186 from image mcr.microsoft.com/businesscentral:10.0.20348.288
c32578e52638244de3a2827650fa4b8569d519072579723b82d10d8e12aeb5d4
Waiting for container SKM186 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/18.6.30510.0/de
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\18.6.30510.0\platform\ServiceTier\Program Files
c:\dl\onprem\18.6.30510.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\18.6.30510.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
Cannot find path 'C:\dl\onprem\18.6.30510.0\platform\WindowsPowerShellScripts\Cloud\' because it does not exist.
at RoboCopyFiles, C:\Run\HelperFunctions.ps1: line 868
at <ScriptBlock>, C:\Run\navinstall.ps1: line 77
at <ScriptBlock>, C:\Run\start.ps1: line 225
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/onprem/18.6.30510.0/de
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\18.6.30510.0\platform\ServiceTier\Program Files
c:\dl\onprem\18.6.30510.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\18.6.30510.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
Cannot find path 'C:\dl\onprem\18.6.30510.0\platform\WindowsPowerShellScripts\Cloud\' because it does not exist.
at RoboCopyFiles, C:\Run\HelperFunctions.ps1: line 868
at <ScriptBlock>, C:\Run\navinstall.ps1: line 77
at <ScriptBlock>, C:\Run\start.ps1: line 225
at <ScriptBlock>, <No file>: line 1
Initialization of container SKM186 failed
In C:\Users\tillmannj\Documents\WindowsPowerShell\Modules\BcContainerHelper\2.0.15\ContainerHandling\Wait-NavContainerReady.ps1:43 Zeichen:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r SKM186 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container SKM186 failed
```

**Additional context**
This happens with at least the current BC18 containers. BC19 works 
I've already updated to Windows 11 and used the prerelease version of bccontainerhelper 2.0.16
We tried -isolation 'hyperv' and stopped the antivirus software.

**Comment by JulianTillmann** [comment] 2021-10-18 13:59
I've tried about 25 times today already including update to windows 11, isolation parameters, and I updated to the prerelease of BCContainterHelper 2.0.16.

**Comment by GeWuNAV** [comment] 2021-11-02 12:46
Prerelease version of bccontainerhelper 2.0.17-preview505 and the issue still exists. Do I have to open a new issue for this or will there be further investigation? No offense, just for my understanding. :)
Thank you for your support in advance.

**Comment by christianbraeunlich** [comment] 2021-11-04 17:20
Hi @GeWuNAV, as far as I can tell there are already a few very similar (if not equal) issues open already (https://github.com/microsoft/navcontainerhelper/issues/2152, https://github.com/microsoft/navcontainerhelper/issues/2086).

Please have a look at the follwing "workaround-solution": https://github.com/microsoft/navcontainerhelper/issues/2086#issuecomment-932182694. But please don't forget to https://github.com/microsoft/navcontainerhelper/issues/2086#issuecomment-932192541.

And if you read through all the issues they will ultimately tell you that updating to windows11 is the best option (as reported here https://github.com/microsoft/navcontainerhelper/issues/2159#issuecomment-959129445)

**Comment by freddydk** [comment] 2021-11-10 05:29
Exactly - this pattern:
```
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Initializing...
Setting host.docker.internal to 192.168.0.108 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.108 in container hosts file (copy from host hosts file)
```
Means that the container restarts and points to a duplicate of #2086

**Closed by freddydk** 2021-11-10 05:29 UTC
Labels: duplicate
