### ISSUE TITLE
BC 24.3.21374.22132 Creation with external DB Failed - Service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'.

### ISSUE THREAD

**Issue by Regatoni** [microsoft/navcontainerhelper#3602] opened 2024-07-23 13:03 UTC
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
While trying to Create a Docker Container with BC 24.3.21374.22132 with a DB on another Docker, it failed with the following Error Message:

> Service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'.

When running the same command but omitting the database parameters, it works

**Scripts used to create container and cause the issue**
```
New-BCContainer `
    -accept_eula `
    -accept_outdated `
    -isolation process `
    -artifactUrl "https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.3.21374.22132/ch" `
    -assignPremiumPlan `
    -containerName SGV-dev-test `
    -auth NAVUserPassword `
    -Credential $BCLogin `
    -alwaysPull `
    -shortcuts DesktopFolder `
    -databaseName SGV-dev-test `
    -databaseCredential $dbLogin `
    -databaseServer DevSQL
```

**Full output of scripts**
```
BcContainerHelper is version 6.0.19
BcContainerHelper is running as administrator
HyperV is Enabled
Host is Microsoft Windows 11 Enterprise - 10.0.22631.3527
UsePsSession is True
UsePwshForBc24 is True
UseWinRmSession is never
UseSslForWinRmSession is True
Docker Client Version is 26.1.1
Docker Server Version is 26.1.1
Removing Session SGV-dev-test
Removing container SGV-dev-test
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\SGV-dev-test
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:ltsc2022
ltsc2022: Pulling from businesscentral
Digest: sha256:4f18913f58dafe2af1e083627559ed74aabaf919b7b28d10e148cdbaf2ec49c0
Status: Image is up to date for mcr.microsoft.com/businesscentral:ltsc2022
mcr.microsoft.com/businesscentral:ltsc2022
Using image mcr.microsoft.com/businesscentral:ltsc2022
Creating Container SGV-dev-test
Style: sandbox
Multitenant: No
Version: 24.3.21374.22132
Platform: 24.0.22118.0
Generic Tag: 1.0.2.39
Container OS Version: 10.0.20348.2582 (ltsc2022)
Host OS Version: 10.0.22631.3527 (23H2)
Using process isolation
Using locale de-CH
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\SGV-dev-test\my:
- AdditionalOutput.ps1
- HelperFunctions.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container SGV-dev-test from image mcr.microsoft.com/businesscentral:ltsc2022
Using Shared Encryption Key file
db7d34f10dc156bcc936683fc2695bd8c38d746fc283756cb58d581d5969e5b5
Waiting for container SGV-dev-test to be ready
Using artifactUrl https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.3.21374.22132/ch
Using installer from C:\Run\240
Installing Business Central: multitenant=False, installOnly=False, filesOnly=False, includeTestToolkit=False, includeTestLibrariesOnly=False, includeTestFrameworkOnly=False, includePerformanceToolkit=False, appArtifactPath=c:\dl\
sandbox\24.3.21374.22132\ch, platformArtifactPath=c:\dl\sandbox\24.3.21374.22132\platform, databasePath=, licenseFilePath=c:\dl\sandbox\24.3.21374.22132\ch\Cronus.bclicense, rebootContainer=True
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\24.3.21374.22132\platform\ServiceTier\Program Files
c:\dl\sandbox\24.3.21374.22132\platform\ServiceTier\System64Folder
Copying Web Client Files
c:\dl\sandbox\24.3.21374.22132\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\24.3.21374.22132\platform
c:\dl\sandbox\24.3.21374.22132\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\24.3.21374.22132\ch\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\24.3.21374.22132\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\24.3.21374.22132\ch\Extensions
Copying Applications
C:\dl\sandbox\24.3.21374.22132\platform\Applications
Copying Applications.CH
C:\dl\sandbox\24.3.21374.22132\ch\Applications.CH
Copying dependencies
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 8 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.20.192.1 in container hosts file
Starting Container
Hostname is SGV-dev-test
PublicDnsName is SGV-dev-test
Using NavUserPassword Authentication
Import Encryption Key
Stopping local SQL Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 986ADE6C21D28A8DCB479C700A10889DC321215A
DNS identity SGV-dev-test
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 175
at <ScriptBlock>, C:\Run\start.ps1: line 390
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.3.21374.22132/ch
Using installer from C:\Run\240
Installing Business Central: multitenant=False, installOnly=False, filesOnly=False, includeTestToolkit=False, includeTestLibrariesOnly=False, includeTestFrameworkOnly=False, includePerformanceToolkit=False, appArtifactPath=c:\dl\
sandbox\24.3.21374.22132\ch, platformArtifactPath=c:\dl\sandbox\24.3.21374.22132\platform, databasePath=, licenseFilePath=c:\dl\sandbox\24.3.21374.22132\ch\Cronus.bclicense, rebootContainer=True
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\24.3.21374.22132\platform\ServiceTier\Program Files
c:\dl\sandbox\24.3.21374.22132\platform\ServiceTier\System64Folder
Copying Web Client Files
c:\dl\sandbox\24.3.21374.22132\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\24.3.21374.22132\platform
c:\dl\sandbox\24.3.21374.22132\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\24.3.21374.22132\ch\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\24.3.21374.22132\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\24.3.21374.22132\ch\Extensions
Copying Applications
C:\dl\sandbox\24.3.21374.22132\platform\Applications
Copying Applications.CH
C:\dl\sandbox\24.3.21374.22132\ch\Applications.CH
Copying dependencies
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 8 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.20.192.1 in container hosts file
Starting Container
Hostname is SGV-dev-test
PublicDnsName is SGV-dev-test
Using NavUserPassword Authentication
Import Encryption Key
Stopping local SQL Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 986ADE6C21D28A8DCB479C700A10889DC321215A
DNS identity SGV-dev-test
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 175
at <ScriptBlock>, C:\Run\start.ps1: line 390
at <ScriptBlock>, <No file>: line 1
New-BCContainer Telemetry Correlation Id: 11964156-1454-4cde-8dd1-da84b7f0261f
Initialization of container SGV-dev-test failed
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.19\ContainerHandling\Wait-NavContainerReady.ps1:42 Zeichen:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...dev-test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container SGV-dev-test failed
...
```

**Additional context**
- The error appears when trying to connect the BC-Container to a SQL-Docker. When using the SQL-Server on the BC-Container, the Creation works
- tried it with BC24.2, there it worked

**Comment by freddydk** [comment] 2024-07-23 13:11
What does the event log say?

**Comment by Regatoni** [comment] 2024-07-23 13:20
[Eventlog_Docker_SGV.zip](https://github.com/user-attachments/files/16349389/Eventlog_Docker_SGV.zip)
Here is the entire EventLog.

**Comment by freddydk** [comment] 2024-07-23 13:34
Duplicate of #3601

**Closed by freddydk** 2024-07-23 13:34 UTC
