### ISSUE TITLE
Export-NavContainerObjects - ImageName not defined

### ISSUE THREAD

**Issue by epernst** [Microsoft/navcontainerhelper#423] opened 2019-04-12 06:35 UTC
In the latest version 0.6.0.2 running the Export-NavContainerObjects failes with:

_The variable '$imageName' cannot be retrieved because it has not been set._

The problem is in line 50: 
$navversion = Get-NavContainerNavversion -containerOrImageName $imageName

Can be fixed by changing the line to:
$navversion = Get-NavContainerNavversion -containerOrImageName (Get-NavContainerImageName -containerName $ContainerName)

**Comment by epernst** [comment] 2019-04-12 07:17
Same issue in Convert-Txt2AL, Line 38:

    $navversion = Get-NavContainerNavversion -containerOrImageName $imageName

Change to:
    $navversion = Get-NavContainerNavversion -containerOrImageName (Get-NavContainerImageName -containerName $ContainerName)

**Comment by freddydk** [comment] 2019-04-12 07:26
actually
$navversion = Get-NavContainerNavversion -containerOrImageName $containerName 
is the right fix, will publish a new version. 
The problem is that I typically have a global variable called Imagename - which caused my tests not to fail...:-(
The Export function was fixed in 0.6.0.3
Fixed in 0.6.0.6 - will need to run tests in Azure DevOps and not on my machine

**Closed** 2019-04-15 03:44 UTC
Labels: Fix Ready
