### ISSUE TITLE
Use path to folder for the  -installApps parameter in the Run-AlPipeline function.

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/navcontainerhelper#1467] opened 2020-11-20 08:39 UTC
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Is it possible to use the -installApps parameter with the folder path to the app? For example “dependency/dbas/output/app/”. This is the folder path to the app file which is downloaded from the pipeline. The full value for the local agent folder is “D:\a\1\s\dependency\dbas\output\app/xxxx.app”). Our app is depending on this app.

**Scripts used to create container and cause the issue**
```
Run-AlPipeline @params `
    -pipelinename $pipelineName `
    -containerName $containerName `
    -imageName $imageName `
    -artifact $artifact.replace('{INSIDERSASTOKEN}', $insiderSasToken) `
    -memoryLimit $memoryLimit `
    -baseFolder $baseFolder `
    -licenseFile $LicenseFile `
    -installApps $installApps `
```

**Full output of scripts**
```

...
```

**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by freddydk** [comment] 2020-11-20 10:15
As it is now, all paths in Run-AlPipeline is relative to the current directory of the runner, which is useless.
I will change this to have all relative paths being relative to the basefolder.
but...
the mechanism I typically use is to have installapps be a url and then the pipeline will download and install the app(s)
If the url points to a .zip file, the apps inside the .zip file will be sorted by dependencies and installed.

**Comment by JonFjolnirAlbertsson** [comment] 2020-11-20 11:02
I'm using this by downloading first a dependancy file directly from a branch in the pipeline and then using this parameter to point to the folder. It works now by defining the path and full filename. But it would be easer if I can only point to the folder where I downloaded the app/s without specifing the full filename with version number included.

**Comment by freddydk** [comment] 2020-11-21 17:09
I will take my words back - current behavior is as explained above, but it is not useless.

Just tested this.

If you use:
```
Set-Location $baseFolder
Run-AlPipeline ... -installApps @('mydep\app.app') ...
```

Then app.app will be taken from $basefolder\mydep\app.app

If you set the workingDirectory parameter in the Azure DevOps PowerShell task, then relative paths will be relative to this.

I think that is the expected behavior and I don't think I can change the location inside run-alpipeline if people are already doing this, their pipelines will break.

Will close this as won't fix, as the current behavior is intended.

**Closed** 2020-11-21 17:14 UTC
Labels: wontfix
