### ISSUE TITLE
Issue with Run-AlPipeline (after Step Determining Database Collation)

### ISSUE THREAD

**Issue by NeverAskWhy** [microsoft/navcontainerhelper#2116] opened 2021-10-05 14:07 UTC
Code:

Param(
    [Parameter(Mandatory=$false)]
    [string] $version = "ci",
    [string] $containerName = "elaflex",
    [switch] $reUseContainer,
    [string] $sharedFolder = ""
)

Set-Location (Join-Path $PSScriptRoot "..")

$containerNameParam = $containerName
$baseFolder = (Get-Item (Join-Path $PSScriptRoot "..")).FullName
. (Join-Path $PSScriptRoot "Read-Settings.ps1") -environment 'Local' -version $version
. (Join-Path $PSScriptRoot "Install-BcContainerHelper.ps1") -bcContainerHelperVersion $bcContainerHelperVersion -genericImageName $genericImageName
if ($containerNameParam) { $containerName = $containerNameParam }

Write-Host "Creating Container $containerName"

$licenseFile = "F:\OneDriveSync\OneDrive\Dokumente\Dokumente_OneDrive\Lizenzen\x.flf"
$insiderSasToken = ''
$credential = New-Object System.Management.Automation.PSCredential -argumentList "elaflex", (ConvertTo-SecureString -String "elaflex" -AsPlainText -Force)

$allTestResults = "testresults*.xml"
$testResultsFile = Join-Path $baseFolder "TestResults.xml"
$testResultsFiles = Join-Path $baseFolder $allTestResults
if (Test-Path $testResultsFiles) {
    Remove-Item $testResultsFiles -Force
}

. (Join-Path $PSScriptRoot "Download-AzureFeed.ps1") `
    -organization "https://dev.azure.com/xxx/" `
    -feeds "xxx" `
    -feedApps "xxx,yyy" `
    -appsPath "C:\temp\DevEnv\xxxapps"

Run-AlPipeline `
    -pipelineName $pipelineName `
    -containerName $containerName `
    -imageName $imageName `
    -artifact $artifact.replace('{INSIDERSASTOKEN}',$insiderSasToken) `
    -memoryLimit $memoryLimit `
    -baseFolder $baseFolder `
    -sharedFolder $sharedFolder `
    -licenseFile $licenseFile `
    -installApps $installApps `
    -installTestApps $installTestApps `
    -appFolders $appFolders `
    -testFolders $testFolders `
    -testResultsFile $testResultsFile `
    -testResultsFormat 'JUnit' `
    -installTestRunner:$installTestRunner `
    -installTestFramework:$installTestFramework `
    -installTestLibraries:$installTestLibraries `
    -installPerformanceToolkit:$installPerformanceToolkit `
    -credential $credential `
    -doNotRunTests `
    -useDevEndpoint `
    -updateLaunchJson "Local Sandbox" `
    -keepContainer `
    -reUseContainer:$reUseContainer

Output:
BcContainerHelper is version 2.0.16
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 20H2
Docker Client Version is 20.10.8
Docker Server Version is 20.10.8
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Building image bcimage:onprem-18.3.27240.27480-de based on mcr.microsoft.com/businesscentral:10.0.19042.1237 with https://bcartifacts.azureedge.net/onprem/18.3.27240.27480/de
Pulling latest image mcr.microsoft.com/businesscentral:10.0.19042.1237
10.0.19042.1237: Pulling from businesscentral
Digest: sha256:4242c01b2ba14cfc718623de33338f4796a70c58f60fec59d0651561e2ce3951
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.19042.1237
mcr.microsoft.com/businesscentral:10.0.19042.1237
Generic Tag: 1.0.1.7
Container OS Version: 10.0.19042.1237 (20H2)
Host OS Version: 10.0.19042.1237 (20H2)
Using process isolation
Using license file F:\OneDriveSync\OneDrive\Dokumente\Dokumente_OneDrive\Lizenzen\2021-10-05__BC18.flf
Files in c:\bcartifacts.cache\iq4oqshb.ie4\my:
Copying Platform Artifacts
Copying Database
Copying Licensefile
Copying ConfigurationPackages
Copying Applications
c:\bcartifacts.cache\iq4oqshb.ie4
Sending build context to Docker daemon  1.563GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.19042.1237
 ---> ee8829be27ed
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onprem/18.3.27240.27480/de filesOnly=False
 ---> Using cache
 ---> ad4df5aae157
Step 3/6 : COPY my /run/
 ---> Using cache
 ---> 9cb88636e755
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 79b7fb2dbc19
Step 5/6 : RUN \Run\start.ps1 -installOnly
 ---> Running in 2be7b9f78cad
Using installer from C:\Run\150-new
Installing Business Central
Installing from DVD
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
C:\NAVDVD\ServiceTier\Program Files
C:\NAVDVD\ServiceTier\System64Folder
Copying PowerShell Scripts
C:\NAVDVD\WindowsPowerShellScripts\Cloud\NAVAdministration
C:\NAVDVD\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation
Docker Build failed with exit code -1
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\New-NavImage.ps1:590 Zeichen:25
+ ...              throw "Docker Build failed with exit code $LastExitCode"
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Docker Build failed with exit code -1:String) [], RuntimeException
    + FullyQualifiedErrorId : Docker Build failed with exit code -1

sorry, I don't know how to format the code correctly :-/

**Comment by freddydk** [comment] 2021-10-05 14:46
This is a duplicate of #2086

**Closed** 2021-10-19 07:29 UTC
Labels: duplicate
