### ISSUE TITLE
Error when installing new BC Docker Image

### ISSUE THREAD

**Issue by nicward** [microsoft/navcontainerhelper#2722] opened 2022-10-04 17:09 UTC
Getting an error when trying to install a new BC Docker Image.  The script runs fine and then I get this error:

"Installing Permissions Mock
Sorry, we can't proceed with the operation for app 'Permissions Mock' by 'Microsoft' for tenant 'default' because the app  doesnâ€™t meet our Universal Code requirement."

**Scripts used to create container and cause the issue**

$containerName = 'bcserver-GB'
$credential = Get-Credential -Message 'Using UserPassword authentication. Please enter credentials for the container.'
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'gb' -select 'Latest'
$licenseFile = 'd:\bc\bc_gb.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'mybc' `
    -multitenant:$false `
    -includeTestToolkit `
    -includePerformanceToolkit `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -vsixFile (Get-LatestAlLanguageExtensionUrl) `
    -updateHosts

**Full output of scripts**

PS C:\WINDOWS\system32> D:\BC\bcserver-gb.ps1
BcContainerHelper is version 4.0.1
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Pro - 21H2
Docker Client Version is 20.10.17
Docker Server Version is 20.10.17
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
WARNING: Unable to find matching generic image for your host OS. Using mcr.microsoft.com/businesscentral:10.0.19041.1415
Building image mybc:sandbox-21.0.46256.47310-gb based on mcr.microsoft.com/businesscentral:10.0.19041.1415 with https://bcartifacts.azureedge.net/sandbox/21.0.46256.47310/gb
Pulling latest image mcr.microsoft.com/businesscentral:10.0.19041.1415
10.0.19041.1415: Pulling from businesscentral
Digest: sha256:8f994521bb757c5c09687dd7484c8696b015ee4dde430fb141b1e560162bb6b0
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.19041.1415
mcr.microsoft.com/businesscentral:10.0.19041.1415
Generic Tag: 1.0.2.13
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19044.2006 (21H2)
WARNING: Host OS is 21H2 and Container OS is 2004, defaulting to process isolation. If you experience problems, add -isolation hyperv.
Using process isolation
Using license file d:\bc\bc_gb.flf
Files in c:\bcartifacts.cache\ph2vamyu.b01\my:
Copying Platform Artifacts
c:\bcartifacts.cache\sandbox\21.0.46256.47310\platform
Copying Database
Copying Licensefile
Copying ConfigurationPackages
C:\bcartifacts.cache\sandbox\21.0.46256.47310\gb\ConfigurationPackages
Copying Extensions
C:\bcartifacts.cache\sandbox\21.0.46256.47310\gb\Extensions
Copying Applications.GB
C:\bcartifacts.cache\sandbox\21.0.46256.47310\gb\Applications.GB
c:\bcartifacts.cache\ph2vamyu.b01
Sending build context to Docker daemon   2.13GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.19041.1415
 ---> fb67a71dbb1c
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/21.0.46256.47310/gb filesOnly=False
 ---> Running in b5ccd651ec97
Removing intermediate container b5ccd651ec97
 ---> 807e4f7f7f9e
Step 3/6 : COPY my /run/
 ---> a9058c94ed3f
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> b3681782c632
Step 5/6 : RUN \Run\start.ps1 -installOnly -includeTestToolkit -includePerformanceToolkit
 ---> Running in 886678a78f3e
c:\run\my folder doesn't exist, creating it
Using installer from C:\Run\210-new
Installing Business Central
Installing from DVD
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
C:\NAVDVD\ServiceTier\Program Files
C:\NAVDVD\ServiceTier\System64Folder
Copying PowerShell Scripts
C:\NAVDVD\WindowsPowerShellScripts\Cloud\NAVAdministration
C:\NAVDVD\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
C:\NAVDVD\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
C:\NAVDVD
C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\NAVDVD\ConfigurationPackages
Copying Test Assemblies
C:\NAVDVD\Test Assemblies
Copying Extensions
C:\NAVDVD\Extensions
Copying Applications
C:\NAVDVD\Applications
Copying Applications.GB
C:\NAVDVD\Applications.GB
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing CRONUS license file
Any is already published
Synchronizing Any
Installing Any
Library Assert is already published
Synchronizing Library Assert
Installing Library Assert
Permissions Mock is already published
Synchronizing Permissions Mock
Installing Permissions Mock
Sorry, we can't proceed with the operation for app 'Permissions Mock' by 'Microsoft' for tenant 'default' because the app  doesnâ€™t meet our Universal Code requirement.

You must either upgrade the app to meet the requirement or license the non-Universal Code module that grants an exception to the requirement.

For more information, see https://aka.ms/bcUniversalCode.
[91mInstallation failed
[0m[91mAt C:\Run\start.ps1:393 char:9
[0m[91m+         throw "Installation failed"
[0m[91m+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m[91m    + CategoryInfo          : OperationStopped: (Installation failed:String) [ 
[0m[91m   ], RuntimeException
    + FullyQualifiedErrorId : Installation failed
[0m[91m 
New-Bcimage Telemetry Correlation Id: e52db0de-bbb5-4e83-b152-ea0cb9f2ceae
New-BcContainer Telemetry Correlation Id: 87f22555-0ed4-4580-af21-87dc2df28858
Docker Build failed with exit code -1
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.1\ContainerHandling\New-NavImage.ps1:640 char:25
+ ...              throw "Docker Build failed with exit code $LastExitCode"
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Docker Build failed with exit code -1:String) [], RuntimeException
    + FullyQualifiedErrorId : Docker Build failed with exit code -1

**Screenshots**

**Additional context**

It happens all the time
Yes it used to work until today

**Comment by efortin2021** [comment] 2022-10-05 14:47
**I have the same issue with BC 21.0**

The script work well in BC 20.5 until I upgrade to BC 21.0 yesterday.
I also upgrade my license to support BC 21.0
I used BcContainerHelper 4.0.5 

Here is my log:
Installing Permissions Mock on default
Sorry, we can't proceed with the operation for app 'Permissions Mock' by 'Microsoft' for tenant 'default' because the app  doesn’t meet our Universal Code requirement.

You must either upgrade the app to meet the requirement or license the non-Universal Code module that grants an exception to the requirement.

For more information, see https://aka.ms/bcUniversalCode.

Exception Script Stack Trace:
at <ScriptBlock>, <No file>: line 18

PowerShell Call Stack:
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.2\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 71
at Install-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.2\AppHandling\Install-NavContainerApp.ps1: line 39
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.2\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 209
at Import-TestToolkitToBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.2\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 180
at <ScriptBlock>, C:\temp\InstallBC.ps1: line 23
at <ScriptBlock>, <No file>: line 1

Container Free Physical Memory: 2.9Gb

Services in container sandbox1:
- MicrosoftDynamicsNavServer$BC is Running
- MSSQL$SQLEXPRESS is Running

Sorry, we can't proceed with the operation for app 'Permissions Mock' by 'Microsoft' for tenant 'default' because the
app  doesn’t meet our Universal Code requirement.
You must either upgrade the app to meet the requirement or license the non-Universal Code module that grants an
exception to the requirement.
For more information, see https://aka.ms/bcUniversalCode.
At C:\Program
Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.2\ContainerHandling\Invoke-ScriptInNavContainer.ps1:112 char:13
+             throw $errorMessage
+             ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Sorry, we can't...cUniversalCode.:String) [], RuntimeException
    + FullyQualifiedErrorId : Sorry, we can't proceed with the operation for app 'Permissions Mock' by 'Microsoft' for
    tenant 'default' because the app  doesn’t meet our Universal Code requirement.
    You must either upgrade the app to meet the requirement or license the non-Universal Code module that grants an ex
   ception to the requirement.
For more information, see https://aka.ms/bcUniversalCode.



**I run this script and it's crash during the Mock Installation for the TestToolKit:**
New-BcContainer -accept_eula -containerName $containerName -credential $credential -auth $AuthenticationType -artifactUrl $artifactUrl -updateHosts -licensefile $LicenseFile -shortcuts 'None'
Import-TestToolkitToBcContainer -containerName $ContainerName -includeTestLibrariesOnly
Import-TestToolkitToBcContainer -containerName $ContainerName -includeTestRunnerOnly

**Comment by mtaanquist** [comment] 2022-10-06 10:45
This is related to the issue in #2720.

**Comment by freddydk** [comment] 2022-10-14 06:18
Yes @mtaanquist - the issue has been fixed by the licensing team for now and the infrastructure team is working on ensuring that all apps in all artifacts and in the databses are signed.

**Comment by freddydk** [comment] 2022-10-14 06:19
Duplicate of #2720

**Closed by freddydk** 2022-10-14 06:19 UTC
Labels: Unrelated to BcContainerHelper
