### ISSUE TITLE
Problem with Run-TestsInBCContainer in BC180

### ISSUE THREAD

**Issue by Hmeyer-Simova** [microsoft/navcontainerhelper#1892] opened 2021-04-21 12:32 UTC
Hi, 
we have a problem with 'Run-TestsInBCContainer', our scripts work from 13 to 17 but in version 18 we get a permission error, I hope you can help me.

```
if ($containerVersion -gt 14) {
        $tests = Get-TestsFromBCContainer -containerName $containerName -credential $credential -ignoreGroups -extensionId $ExtId
    }
    else { 
        $tests = Get-TestsFromBCContainer -containerName $containerName -credential $credential -ignoreGroups
    }
    
    $tests | ForEach-Object {
        if(-not (Run-TestsInBCContainer `
            -containerName $containerName `
            -credential $credential `
            -testCodeunit $_.Id `
            -AzureDevOps:'Error' `
            -detailed `
            -returnTrueIfAllPassed)){
                break
            }
    }
```

```
BcContainerHelper version 2.0.6
InvalidCredentialsError
at <ScriptBlock>, C:\ProgramData\BcContainerHelper\Extensions\BC180\PsTestTool\ClientContext.ps1: line 162
ClientSession State is Uninitialized (Wait time 15 seconds)
at AwaitState, C:\ProgramData\BcContainerHelper\Extensions\BC180\PsTestTool\ClientContext.ps1: line 250
at OpenSession, C:\ProgramData\BcContainerHelper\Extensions\BC180\PsTestTool\ClientContext.ps1: line 216
at Initialize, C:\ProgramData\BcContainerHelper\Extensions\BC180\PsTestTool\ClientContext.ps1: line 78
at ClientContext, C:\ProgramData\BcContainerHelper\Extensions\BC180\PsTestTool\ClientContext.ps1: line 45
at New-ClientContext, C:\ProgramData\BcContainerHelper\Extensions\BC180\PsTestTool\PsTestFunctions.ps1: line 40
at <ScriptBlock>, <No file>: line 53
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.6\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at Get-TestsFromBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.6\AppHandling\Get-TestsFromNavContainer.ps1: line 164
at <ScriptBlock>, C:\a\_tasks\Run_Test_5778aa87-9847-4d49-bd90-0e16b400c32a\1.0.16\!RunTests.ps1: line 15
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 22
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 1
##[error]ClientSession State is Uninitialized (Wait time 15 seconds)
Finishing: Run Tests: ALL
```

The error occurs only in v18 and every time

**Comment by freddydk** [comment] 2021-04-21 14:28
InvalidCredentialsError are typically because the credentials are wrong. Are you 100% sure you are using the right credentials?

**Comment by Hmeyer-Simova** [comment] 2021-04-22 06:18
I am sure as our tests run on v17 with the same credentials as on 18. The only difference is in the version. The apps are also published with it and the container is created. the code to generate the credentials is like this:
```

[string] $password = 'your password'
$credential = [PSCredential]::new("CI_" + $containerName, (ConvertTo-SecureString $password -AsPlainText -Force));
```

**Comment by freddydk** [comment] 2021-04-22 06:31
You could try to insert a write-host with the value of credential.username and a conversion of the securestring password to see if some script has mangled with the credentials somewhere else.

There are a ton of pipelines running tests in 18 - so we are looking for a specific problem in your scripts/setup.

If I am to look into this, I would need an email with a link where I can download your full repo (source+scripts)

**Comment by freddydk** [comment] 2021-04-22 06:32
you could also check if this is a duplicate of #1890

**Comment by freddydk** [comment] 2021-05-18 04:58
Please re-open with more info if you need me to look into this.

**Comment by Hmeyer-Simova** [comment] 2021-06-29 14:51
hi freddy, 
i finally had time to deal with the bug, it occurs in our build pipelines. On the normal devops agents they run without problems. However, we run our pipelines on an Azure scaleset. the error occurs only there but always and regardless of the configuration of the scaleset. The SKU is '2019-Datacenter-with-containers-gen2'. 2 apps were imported into the container and then Get-TestsfromBcContainer was executed. after trying around a bit, I noticed that the error does not occur once a certain amount of time has passed after publishing the test app. to me it looks like(New-ClientContext, C:\ProgramData\BcContainerHelper\Extensions\BC180\PsTestTool\PsTestFunctions.ps1: line 40) doesn't manage to initialize fast enough. i solved the error by adding a 'Start-Sleep -seconds 30' before the command 'Get-TestsFromBcContainer'. I hope I could help someone.

The code to recreate the problem:
```
[string] $LicenseFile = 'C:\License\lic.flf'
[string] $BCVersion = '18'
[string] $memorylimit = '6G'
[string] $containerName = "BC180Test"
[string] $ExtId = 'some extension id' 
[string] $appPath = "random.app" 
[string] $appPath2 = "random test.app"
$parameters = @{
    "accept_eula"     = $true;
    "accept_outdated" = $true
}
$additionalParameters = @("--env clickonce=Y ")
[string] $password = 'P@ssword1'
$credential = [PSCredential]::new("CI_" + $containerName, (ConvertTo-SecureString $password -AsPlainText -Force));
$Artifact_URL = Get-BCArtifactUrl -version $BCVersion -type OnPrem
$locale = 'de-DE'

New-BcContainer @parameters `
    -containerName $containerName `
    -artifactUrl $Artifact_URL `
    -auth NAVUserPassword `
    -credential $credential `
    -locale $locale `
    -dns '8.8.8.8' `
    -updateHosts `
    -doNotExportObjectsToText `
    -additionalParameters $additionalParameters `
    -shortcuts None `
    -memoryLimit $memoryLimit `
    -licenseFile $LicenseFile `
    -includeTestToolkit




Publish-BcContainerApp -containerName $containerName -appFile $appPath -skipVerification -sync -install -credential $credential
Publish-BcContainerApp -containerName $containerName -appFile $appPath2 -skipVerification -sync -install -credential $credential
        

Write-Host "getting tests"

#This line causes the error it is fixed with start-sleep -seconds 30
Get-TestsFromBCContainer -containerName $containerName -credential $credential -ignoreGroups -extensionId $ExtId
```

**Comment by mhenricus** [comment] 2021-08-15 09:16
Maybe the following might help someone (and save time).
I got the same error message: InvalidCredentialsError, with the script below. 
It turned out that the dash '-' after the last parameter was the problem. I probably forgot the remove it after trying some other parameters. After removing the dash, the problem was solved. 


$StartTime = $(get-date)
$apps = Get-BcContainerAppInfo -containerName $containerName
foreach ($app in $apps) {
    if (($app.Publisher -eq 'Microsoft') -and ($app.Name -match $testAppsMatch)) { ####
        write-host "$($app.Name)" -ForegroundColor Green
        $xunitResultsFile = "C:\ProgramData\BcContainerHelper\" + $app.Name + ".xml"
        Run-TestsInBCContainer `
            -containerName $containerName `
            -credential $credential `
            -detailed `
            -XUnitResultFileName $xunitResultsFile `
            -extensionId $app.AppId -
    }
}

**Comment by freddydk** [comment] 2021-08-15 19:56
@Hmeyer-Simova, I will add some resilience to the initialization - maybe a longer timeout - or a retry mechanism

**Closed** 2022-05-17 10:42 UTC
Labels: Cannot repro, Need more info

**Comment by mstjernfelt** [comment] 2022-09-29 09:13
FYI, I had the same problem just now, added a sleep before executing the tests and now it works. Not sure what information you need @freddydk to reproduce.
