### ISSUE TITLE
Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition  for Permissions Mock by Microsoft 19.0.0.0.

### ISSUE THREAD

**Issue by dkorinets** [microsoft/navcontainerhelper#1891] opened 2021-04-21 11:21 UTC
Hi, the recently script for new navcontainer creation breaked

the script itself:
`New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -multitenant:$false `
    -includeTestToolkit `
    -includeTestLibrariesOnly `
    -assignPremiumPlan `
    -licenseFile $licenseFileUri `
    -memoryLimit 6G `
    -doNotExportObjectsToText `
    -updateHosts `
    -EnableTaskScheduler:$false`

Error message: 

Synchronizing Test Runner on default
Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for Permissions Mock by Microsoft 19.0.0.0.
at <ScriptBlock>, <No file>: line 21
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at Sync-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\AppHandling\Sync-NavContainerApp.ps1: line 36
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 180
at Import-TestToolkitToBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 153
at New-BcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ContainerHandling\New-NavContainer.ps1: line 1841
at <ScriptBlock>, C:\agent\_work\1\s\Scripts\DevOps\TestSanaOnDailyBCBuild\_NewBcContainer.ps1: line 4
at <ScriptBlock>, C:\agent\_work\_temp\e39e9655-d078-4c7c-85bb-a13263a2b39f.ps1: line 3
at <ScriptBlock>, <No file>: line 1
Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition 
for Permissions Mock by Microsoft 19.0.0.0.
At C:\Program 
Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot synchron...osoft 19.0.0.0.:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot synchronize the extension because no synchronized extension could be found to sat 
   isfy the dependency definition for Permissions Mock by Microsoft 19.0.0.0.

**Comment by freddydk** [comment] 2021-04-21 11:32
Update your BcContainerHelper.
Duplicate of https://github.com/microsoft/navcontainerhelper/issues/1886

**Closed by freddydk** 2021-04-21 11:32 UTC
Labels: duplicate
