### ISSUE TITLE
Sign-NavContainerApp "Cannot locate signtool.exe after installation"

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/navcontainerhelper#930] opened 2020-04-03 22:44 UTC
Related to #846 and #633 

![image](https://user-images.githubusercontent.com/23434319/78410447-32d24380-75c1-11ea-9c64-a8dc90de49ae.png)

Brand new BC v16 container, pulled a new image this morning after updating NavContainerHelper. Version: US Business Central 16.0 (Platform 16.0.11233.11920 + Application 16.0.11240.11946), AL Language 5.0.254558

Let me know what additional information you need.

**Comment by freddydk** [comment] 2020-04-04 03:51
This is a bug in NavContainerHelper, will be fixed right away

**Comment by freddydk** [comment] 2020-04-06 05:26
0.6.5.4 has been released, reverting the change in 0.6.5.3 causing this.

**Comment by freddydk** [comment] 2020-04-06 05:31
Daniel, could you post the full output of the container generation.
Need to see version numbers, isolation modes and more.
(I think this is a February update problem on your setup)

**Comment by TheDenSter** [comment] 2020-04-06 16:44
Here you go:


PS C:\Users\Administrator\Documents\AL\MySandbox> New-BCContainer `
    -accept_eula `
    -containerName $MySettings.DevContainerName `
    -imageName $MySettings.ImageName `
    -licenseFile $MySettings.LicenseFile `
    -auth NavUserPassword `
    -updateHosts `
    -Credential $Credential
NavContainerHelper is version 0.6.5.2
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Using image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
Removing container MySandboxDev
Removing MySandboxDev from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\MySandboxDev
Creating Container MySandboxDev
Version: 16.0.11240.11946-us
Style: sandbox
Platform: 16.0.11233.11920
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.17763.1098 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file .\BC 16 US.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\MySandboxDev\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container MySandboxDev from image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
900f13209f3f1f417e015ba834fe418d6448b3ee7f4235922c38f06677b620a1
Waiting for container MySandboxDev to be ready
Initializing...
Setting host.containerhelper.internal to 172.17.195.65 in container hosts file (copy from host hosts file)
Starting Container
Hostname is MySandboxDev
PublicDnsName is MySandboxDev
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint F8F87A17608E0C0A597640753A0D4E82CD3C8C82
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating tigunia as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.20.134.148
Container Hostname  : MySandboxDev
Container Dns Name  : MySandboxDev
Web Client          : http://MySandboxDev/BC/
Dev. Server         : http://MySandboxDev
Dev. ServerInstance : BC
Setting MySandboxDev to 172.20.134.148 in host hosts file

Files:
http://MySandboxDev:8080/ALLanguage.vsix

Initialization took 104 seconds
Ready for connections!
Reading CustomSettings.config from MySandboxDev
Creating Desktop Shortcuts for MySandboxDev
Container MySandboxDev successfully created
PS C:\Users\Administrator\Documents\AL\MySandbox>

**Comment by freddydk** [comment] 2020-04-06 17:27
That is february update problem (see my blog).
add either -useBestContainerOS or -isolation hyperv

**Comment by TheDenSter** [comment] 2020-04-06 17:36
The plot thickens....

Re-created the container using -isolation hyperv, then ran the sign Cmdlet, and it SAYS it successfully downloaded, installed signtool, and it says it successfully signed the app file:
![image](https://user-images.githubusercontent.com/23434319/78587629-0fdaa600-77f2-11ea-8fff-e5a2993b8041.png)
but when I look at the file properties, it does not have a signature attribute:
![image](https://user-images.githubusercontent.com/23434319/78587754-44e6f880-77f2-11ea-9d79-bb7b6bf2f560.png)

**Comment by TheDenSter** [comment] 2020-04-06 18:17
By the way, I have an email from GitHub with a comment on this issue (which I don't see in here) that navcontainerhelper 0.6.5.4 has been released. 
![image](https://user-images.githubusercontent.com/23434319/78591397-38659e80-77f8-11ea-9c9a-f682256b1f70.png)
Just to make sure, I ran update-module again (I've run it multiple times today already) and when I then run New-BCContainer, it says "NavContainerHelper is version 0.6.5.2".

**Comment by freddydk** [comment] 2020-04-07 04:03
0.6.5.3 contained a problem with Sign-NavContainerApp and since your issue was posted right after the release of 0.6.5.3, I auto-assumed that this was the cause.
Never auto-assume, I read your description and deleted my responses.
Wrt. the file properties, I am not sure that signing the app will change those - I thinhk your issue is resolved.

**Comment by TheDenSter** [comment] 2020-04-07 16:13
Signing the app file adds a digital signature to the file that you can see in the file's properties page. Take explorer.exe for instance, its file properties includes a tab "Digital Signatures" and you can look at the details. On the right is my app file after running it through the Sign-NavContainerApp Cmdlet. As you can see, it does not have a digital signature. About a month ago this did add a digital signature though, so something is different today
![image](https://user-images.githubusercontent.com/23434319/78692861-5c37eb80-78af-11ea-87f7-30de0960d91d.png)

**Comment by freddydk** [comment] 2020-04-07 22:48
Discussion continued in #928 - will close this.

**Closed by freddydk** 2020-04-07 22:48 UTC
Labels: Cannot repro
