### ISSUE TITLE
NextMajor & Running Tests: The identity check failed for the outgoing message

### ISSUE THREAD

**Issue by mitrov** [microsoft/navcontainerhelper#2301] opened 2022-02-08 14:57 UTC
**Describe the issue**
Our build pipeline with NextMajor fails when trying to run tests. 
We use the Swiss (CH) version of BC
I managed to get same error when I manually created a new container with NextMajor. 
After stopping and restarting the container the error disappeared (??)

The actual error is in German unfortunately:
2022-02-08T13:56:41.1754157Z ERROR DIALOG: Fehler bei der Identitätsprüfung für eine ausgehende Nachricht. Die erwartete DNS-Identität des Remoteendpunkts war "", aber der Remoteendpunkt hat den DNS-Anspruch "d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf" bereitgestellt. Wenn es sich hierbei um einen zulässigen Remoteendpunkt handelt, können Sie das Problem beheben, indem Sie ausdrücklich die DNS-Identität "d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf" als Identity-Eigenschaft von EndpointAddress angeben, wenn Sie einen Kanalproxy erstellen. Unter 'net.tcp://localhost:7046/BC/Service' wurde kein Server gefunden. Möglicherweise ist die URL falsch, oder der Server ist zurzeit nicht verfügbar.

**Scripts used to create container and cause the issue**
CreateContainer.ps1:

Param(
    [Parameter(Mandatory=$true)]
    [string] $artifactUrl,  
    [Parameter(Mandatory=$true)]
    [string] $containerName,   
    [string] $imageName = "BC-Image"
)

$credential = [PSCredential]::new("$ENV:Username", (ConvertTo-SecureString -String "$ENV:Password" -AsPlainText -Force))
$licenseFile = "$ENV:LicenseFile"

Write-Host "Create container $containerName from $artifactUrl"

$segments = "$PSScriptRoot".Split('\')
$rootFolder = "$($segments[0])\$($segments[1])"
$additionalParameters = @("--volume ""$($rootFolder):C:\Agent""")
$myscripts = @(@{'MainLoop.ps1' = 'while ($true) { start-sleep -seconds 10 }'})    

$parameters = @{
    "accept_eula"               = $true
    "accept_outdated"           = $true
    "includeTestToolkit"        = $true
    "includeTestLibrariesOnly"  = $true
    "containerName"             = $containerName
    "imageName"                 = $imageName
    "artifactUrl"               = $artifactUrl
    "auth"                      = "NAVUserPassword"
    "Credential"                = $credential
    "updateHosts"               = $true
    "doNotExportObjectsToText"  = $true
    "doNotCheckHealth"          = $true
    "EnableTaskScheduler"       = $false
    "memoryLimit"               = "30G"
    "licenseFile"               = $licenseFile
    "additionalParameters"      = $additionalParameters
    "myScripts"                 = $myscripts
    "runSandboxAsOnPrem"        = $true # BC v18 and higher only. Improves performance for tests.
}

New-NavContainer @parameters

From RunTests.ps1:

Run-TestsInBcContainer -containerName $containerName -CompanyName "SwissdecSVTests" -XUnitResultFileName $TempTestResultFile -testSuite $testSuite -testCodeunit 3099152 -credential $credential -extensionId '*******' -culture 'de-CH' -AzureDevOps "warning" -detailed

**Full output of scripts**
```
2022-02-08T13:49:27.0238938Z ##[section]Starting: Create Build Container
2022-02-08T13:49:27.0344844Z ==============================================================================
2022-02-08T13:49:27.0345159Z Task         : PowerShell
2022-02-08T13:49:27.0345440Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2022-02-08T13:49:27.0345700Z Version      : 2.198.0
2022-02-08T13:49:27.0345938Z Author       : Microsoft Corporation
2022-02-08T13:49:27.0346261Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2022-02-08T13:49:27.0346617Z ==============================================================================
2022-02-08T13:49:27.6958234Z Generating script.
2022-02-08T13:49:27.6997303Z Formatted command: . 'C:\devops_agent_1\_work\1\s\scripts\Create-Container.ps1' -***Name "d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf" -artifactUrl "https://bcinsider.azureedge.net/sandbox/20.0.35891.0/ch***" -imageName "BC-Sandbox-NextMajor"
2022-02-08T13:49:27.7248754Z ========================== Starting Command Output ===========================
2022-02-08T13:49:27.7413063Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\devops_agent_1\_work\_temp\f4b3457d-8c00-479e-8ac6-e702ccd3a3c6.ps1'"
2022-02-08T13:49:27.9269001Z Create *** d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf from https://bcinsider.azureedge.net/sandbox/20.0.35891.0/ch***
2022-02-08T13:49:28.1185847Z BcContainerHelper version 3.0.2-preview547
2022-02-08T13:49:28.1266928Z BcContainerHelper emits usage statistics telemetry to Microsoft
2022-02-08T13:49:28.8878696Z WARNING: Container name should not exceed 15 characters
2022-02-08T13:49:30.3647775Z BcContainerHelper is version 3.0.2-preview547
2022-02-08T13:49:30.3655979Z BcContainerHelper is running as administrator
2022-02-08T13:49:30.3672795Z Host is Microsoft Windows Server 2019 Standard - ltsc2019
2022-02-08T13:49:30.4922329Z Docker Client Version is 20.10.7
2022-02-08T13:49:30.4945496Z Docker Server Version is 20.10.7
2022-02-08T13:49:32.3836751Z Fetching all docker images
2022-02-08T13:49:32.5525834Z Fetching all docker volumes
2022-02-08T13:49:32.6680560Z ArtifactUrl and ImageName specified
2022-02-08T13:49:33.4259022Z Image bc-sandbox-nextmajor:sandbox-20.0.35891.0-ch already exists
2022-02-08T13:49:34.5440756Z Using image bc-sandbox-nextmajor:sandbox-20.0.35891.0-ch
2022-02-08T13:49:34.6730937Z Disabling Health Check (always report healthy)
2022-02-08T13:49:34.6833935Z Creating Container d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:49:34.6899786Z Style: sandbox
2022-02-08T13:49:34.6907350Z Multitenant: No
2022-02-08T13:49:34.6917995Z Version: 20.0.35891.0
2022-02-08T13:49:34.6931289Z Platform: 20.0.35749.0
2022-02-08T13:49:34.6938672Z Generic Tag: 1.0.2.1
2022-02-08T13:49:34.6956982Z Container OS Version: 10.0.17763.2300 (ltsc2019)
2022-02-08T13:49:34.6961710Z Host OS Version: 10.0.17763.2300 (ltsc2019)
2022-02-08T13:49:34.7022916Z Using process isolation
2022-02-08T13:49:34.7073759Z Using locale de-CH
2022-02-08T13:49:34.7100386Z Disabling the standard eventlog dump to *** log every 2 seconds (use -dumpEventLog to enable)
2022-02-08T13:49:34.7213843Z Using license file https://***bcpipelines.blob.core.windows.net/***-pipeline-secrets/Entwicklerlizenz.flf
2022-02-08T13:49:34.7342662Z Downloading C:\ProgramData\BcContainerHelper\Extensions\d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf\my\license.flf
2022-02-08T13:49:35.0336250Z Additional Parameters:
2022-02-08T13:49:35.0349852Z --volume "C:\devops_agent_1:C:\Agent"
2022-02-08T13:49:35.0355267Z --env customNavSettings=EnableTaskScheduler=False
2022-02-08T13:49:35.0361249Z Files in C:\ProgramData\BcContainerHelper\Extensions\d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf\my:
2022-02-08T13:49:35.0399701Z - AdditionalOutput.ps1
2022-02-08T13:49:35.0406518Z - license.flf
2022-02-08T13:49:35.0411614Z - MainLoop.ps1
2022-02-08T13:49:35.0417913Z - SetupVariables.ps1
2022-02-08T13:49:35.0423049Z - updatehosts.ps1
2022-02-08T13:49:35.0428857Z Creating *** d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf from image bc-sandbox-nextmajor:sandbox-20.0.35891.0-ch
2022-02-08T13:49:35.2316321Z ccd61836c52580c93a78b1feea1be7dced88327dd8d9fd32571bb37753abc8e5
2022-02-08T13:49:36.4350440Z Waiting for *** d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf to be ready
2022-02-08T13:49:37.5660841Z Adding DSWS-BS1-GSC-A1 to hosts file
2022-02-08T13:49:37.5661231Z Initializing...
2022-02-08T13:49:37.5661882Z Setting host.***helper.internal to 172.30.48.1 in *** hosts file
2022-02-08T13:49:37.5662649Z Starting Container
2022-02-08T13:49:37.5663213Z Hostname is d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:49:38.7387456Z PublicDnsName is d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:49:38.7387893Z Using NavUserPassword Authentication
2022-02-08T13:49:39.8922578Z Starting Local SQL Server
2022-02-08T13:49:41.0230211Z Starting Internet Information Server
2022-02-08T13:49:41.0230641Z Creating Self Signed Certificate
2022-02-08T13:49:41.0230997Z Self Signed Certificate Thumbprint B6197B701EBEC42A6F63C8DEDE85C0B3B0D6A0C5
2022-02-08T13:49:41.0231504Z DNS identity d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:49:41.0231902Z Modifying Service Tier Config File with Instance Specific Settings
2022-02-08T13:49:41.0232290Z Modifying Service Tier Config File with settings from environment variable
2022-02-08T13:49:42.1523824Z Setting EnableTaskScheduler to False
2022-02-08T13:50:06.5976040Z Starting Service Tier
2022-02-08T13:50:06.5976408Z Registering event sources
2022-02-08T13:50:10.0663473Z Creating DotNetCore Web Server Instance
2022-02-08T13:50:10.0664143Z Enabling Financials User Experience
2022-02-08T13:50:10.0664952Z Using license file 'c:\run\my\license.flf'
2022-02-08T13:50:11.2063425Z Import License
2022-02-08T13:50:11.2063807Z Creating http download site
2022-02-08T13:50:11.2064088Z Setting SA Password and enabling SA
2022-02-08T13:50:12.3327028Z Creating *** as SQL User and add to sysadmin
2022-02-08T13:50:14.6001979Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:14.6002809Z Creating SUPER user
2022-02-08T13:50:14.6003400Z WARNING: The password that you entered does not meet the minimum requirements. 
2022-02-08T13:50:14.6003868Z It should be at least 8 characters long and contain at least one uppercase 
2022-02-08T13:50:14.6004245Z letter, one lowercase letter, and one number.
2022-02-08T13:50:15.7581669Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:16.9137658Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:16.9138210Z Container IP Address: 172.30.50.68
2022-02-08T13:50:16.9138660Z Container Hostname  : d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:50:16.9139137Z Container Dns Name  : d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:50:16.9139688Z Web Client          : http://d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf/BC/
2022-02-08T13:50:16.9140168Z Dev. Server         : http://d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:50:16.9140544Z Dev. ServerInstance : BC
2022-02-08T13:50:16.9140942Z Setting d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf to 172.30.50.68 in host hosts file
2022-02-08T13:50:16.9141176Z 
2022-02-08T13:50:16.9141404Z Files:
2022-02-08T13:50:16.9141791Z http://d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf:8080/ALLanguage.vsix
2022-02-08T13:50:16.9142031Z 
2022-02-08T13:50:16.9142339Z WARNING: You are running a *** which is 90 days old.
2022-02-08T13:50:16.9142746Z Microsoft recommends that you always run the latest version of our ***s.
2022-02-08T13:50:16.9142939Z 
2022-02-08T13:50:16.9143207Z Container Total Physical Memory is 63.8Gb
2022-02-08T13:50:16.9144130Z Container Free Physical Memory is 42.6Gb
2022-02-08T13:50:16.9144288Z 
2022-02-08T13:50:16.9144565Z Initialization took 39 seconds
2022-02-08T13:50:16.9144854Z Ready for connections!
2022-02-08T13:50:17.4961008Z Reading CustomSettings.config from d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:50:18.0999755Z Creating Desktop Shortcuts for d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:50:19.3088464Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:19.4017011Z Skipping app 'C:\Applications.CH\Microsoft_Permissions Mock_20.0.35891.0.app' as it is already installed
2022-02-08T13:50:19.4156092Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:19.4243128Z Skipping app 'C:\Applications.CH\Microsoft_Test Runner_20.0.35891.0.app' as it is already installed
2022-02-08T13:50:19.4566072Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:19.4648980Z Skipping app 'C:\Applications.CH\Microsoft_Any_20.0.35891.0.app' as it is already installed
2022-02-08T13:50:19.4785031Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:19.4873673Z Skipping app 'C:\Applications.CH\Microsoft_Library Assert_20.0.35891.0.app' as it is already installed
2022-02-08T13:50:19.5003416Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:19.5092616Z Skipping app 'C:\Applications.CH\Microsoft_Permissions Mock_20.0.35891.0.app' as it is already installed
2022-02-08T13:50:19.5230838Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:19.5383254Z Skipping app 'C:\Applications.CH\Microsoft_Library Variable Storage_20.0.35891.0.app' as it is already installed
2022-02-08T13:50:19.5545639Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:19.5633131Z Skipping app 'C:\Applications.CH\Microsoft_System Application Test Library_20.0.35891.0.app' as it is already installed
2022-02-08T13:50:19.5826899Z WARNING: This license is not compatible with this version of Business Central.
2022-02-08T13:50:19.5909913Z Skipping app 'C:\Applications.CH\Microsoft_Tests-TestLibraries_20.0.35891.0.app' as it is already installed
2022-02-08T13:50:19.5914416Z TestToolkit successfully imported
2022-02-08T13:50:20.1597582Z Container d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf successfully created
2022-02-08T13:50:20.1606363Z 
2022-02-08T13:50:20.1638564Z Use:
2022-02-08T13:50:20.1693129Z Get-BcContainerEventLog -***Name d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf to retrieve a snapshot of the event log from the ***
2022-02-08T13:50:20.1707738Z Get-BcContainerDebugInfo -***Name d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf to get debug information about the ***
2022-02-08T13:50:20.1717419Z Enter-BcContainer -***Name d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf to open a PowerShell prompt inside the ***
2022-02-08T13:50:20.1726840Z Remove-BcContainer -***Name d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf to remove the *** again
2022-02-08T13:50:20.1736326Z docker logs d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf to retrieve information about URL's again
2022-02-08T13:50:20.9771370Z ##[section]Finishing: Create Build Container

2022-02-08T13:54:21.4638714Z ##[section]Starting: Run Tests
2022-02-08T13:54:21.4741500Z ==============================================================================
2022-02-08T13:54:21.4741824Z Task         : PowerShell
2022-02-08T13:54:21.4742120Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2022-02-08T13:54:21.4742403Z Version      : 2.198.0
2022-02-08T13:54:21.4742648Z Author       : Microsoft Corporation
2022-02-08T13:54:21.4742988Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2022-02-08T13:54:21.4743352Z ==============================================================================
2022-02-08T13:54:22.1586190Z Generating script.
2022-02-08T13:54:22.1631950Z Formatted command: . 'C:\devops_agent_1\_work\1\s\scripts\Run-Tests.ps1' -***Name "d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf" -BuildArtifactFolder "C:\devops_agent_1\_work\1\a" -TestResultsFile (Join-Path "C:\devops_agent_1\_work\1\s" "TestResults.xml") -TestSuite "DEFAULT" -TempFolder "C:\devops_agent_1\_work\_temp" -platform "Sandbox" -runCodeCoverage "true"
2022-02-08T13:54:22.1891302Z ========================== Starting Command Output ===========================
2022-02-08T13:54:22.2064015Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\devops_agent_1\_work\_temp\d2fa701e-23d4-48a2-984c-1d541bdba397.ps1'"
2022-02-08T13:54:23.3231766Z Create Companies
2022-02-08T13:55:44.2833769Z Initializing TestSuite on d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:55:56.4256150Z Running BeforeTestrunner with dataset SwissdecSV on d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:56:34.7657430Z Running Swissdec SV tests on d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf
2022-02-08T13:56:34.9298573Z BcContainerHelper version 3.0.2-preview547
2022-02-08T13:56:34.9374216Z BcContainerHelper emits usage statistics telemetry to Microsoft
2022-02-08T13:56:37.7884846Z Connecting to http://localhost:80/BC/cs?tenant=default&company=SwissdecSVTests
2022-02-08T13:56:41.1754157Z ERROR DIALOG: Fehler bei der Identitätsprüfung für eine ausgehende Nachricht. Die erwartete DNS-Identität des Remoteendpunkts war "", aber der Remoteendpunkt hat den DNS-Anspruch "d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf" bereitgestellt. Wenn es sich hierbei um einen zulässigen Remoteendpunkt handelt, können Sie das Problem beheben, indem Sie ausdrücklich die DNS-Identität "d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf" als Identity-Eigenschaft von EndpointAddress angeben, wenn Sie einen Kanalproxy erstellen. Unter 'net.tcp://localhost:7046/BC/Service' wurde kein Server gefunden. Möglicherweise ist die URL falsch, oder der Server ist zurzeit nicht verfügbar.
2022-02-08T13:56:41.4492732Z at Run-Tests, C:\ProgramData\BcContainerHelper\Extensions\d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf\PsTestTool\PsTestFunctions.ps1: line 380
2022-02-08T13:56:41.4495188Z at <ScriptBlock>, <No file>: line 61
2022-02-08T13:56:41.4831891Z Cannot open page 130455. You might need to import the test toolkit to the *** and/or remove the folder C:\ProgramData\BcContainerHelper\Extensions\d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf\PsTestTool and retry. You might also have URL or Company name wrong.
2022-02-08T13:56:41.4848975Z at Run-Tests, C:\ProgramData\BcContainerHelper\Extensions\d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf\PsTestTool\PsTestFunctions.ps1: line 380
2022-02-08T13:56:41.4852223Z at <ScriptBlock>, <No file>: line 61
2022-02-08T13:56:41.4863377Z at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.2\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 43
2022-02-08T13:56:41.4869508Z at Run-TestsInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.2\AppHandling\Run-TestsInNavContainer.ps1: line 360
2022-02-08T13:56:41.4875690Z at <ScriptBlock>, C:\devops_agent_1\_work\1\s\scripts\Run-Tests.ps1: line 108
2022-02-08T13:56:41.4881237Z at <ScriptBlock>, C:\devops_agent_1\_work\_temp\d2fa701e-23d4-48a2-984c-1d541bdba397.ps1: line 3
2022-02-08T13:56:41.4884130Z at <ScriptBlock>, <No file>: line 1
2022-02-08T13:56:43.0826209Z Run-TestsInBcContainer Telemetry Correlation Id: 8ca9d9a3-b375-4c77-b9e3-c5411bc8b2b2
2022-02-08T13:56:43.1965008Z Cannot open page 130455. You might need to import the test toolkit to the *** and/or remove the folder 
2022-02-08T13:56:43.1965886Z C:\ProgramData\BcContainerHelper\Extensions\d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73bcb43513bf\PsTestTool and 
2022-02-08T13:56:43.1966625Z retry. You might also have URL or Company name wrong.
2022-02-08T13:56:43.1967528Z At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.2\AppHandling\Run-TestsInNavContainer.ps1:490 
2022-02-08T13:56:43.1968044Z char:17
2022-02-08T13:56:43.1968427Z +                 throw $_.Exception.Message
2022-02-08T13:56:43.1968789Z +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-02-08T13:56:43.1969424Z     + CategoryInfo          : OperationStopped: (Cannot open pag...any name wrong.:String) [], RuntimeException
2022-02-08T13:56:43.1970056Z     + FullyQualifiedErrorId : Cannot open page 130455. You might need to import the test toolkit to the *** and/ 
2022-02-08T13:56:43.1970640Z    or remove the folder C:\ProgramData\BcContainerHelper\Extensions\d***-bs1-gsc-a1-10685-9716c0e7-77fa-51af-4622-73b  
2022-02-08T13:56:43.1971146Z   cb43513bf\PsTestTool and retry. You might also have URL or Company name wrong.
2022-02-08T13:56:43.1971482Z  
2022-02-08T13:56:43.2640039Z ##[error]PowerShell exited with code '1'.
2022-02-08T13:56:43.2931325Z ##[section]Finishing: Run Tests

...
```

**Screenshots**
This is the eventlog of the same error when I tried to login to the manually created container:
![image](https://user-images.githubusercontent.com/8106202/153012117-1642aa91-1464-430e-8bde-1474bb308fcb.png)
After stopping and starting the docker container this error disappeared.

**Additional context**
- does it happen all the time?
Yes. In pipeline
- did it use to work?
Yes

**Comment by freddydk** [comment] 2022-02-08 22:47
Might be the same problem as #2298 - will investigate

**Comment by mitrov** [comment] 2022-02-09 10:36
https://bcinsider.azureedge.net/sandbox/20.0.35117.0/ch 
is the last version which still works for us.

**Comment by freddydk** [comment] 2022-02-09 10:38
The eventlog you display here is from the Web Client not being able to connect to the Service Tier - this is a symptom.
Prior to that, there is probably an event log entry that the Service Tier has crashed and is no longer running.

**Comment by freddydk** [comment] 2022-02-09 10:40
I cannot seem to repro this problem, but due to 2298 - I do think we have a problem.

**Comment by freddydk** [comment] 2022-02-09 10:41
If you can stop the script right before run-tests and check whether the service tier is running - then we will know whether it is caused by run-tests or whether the real problem is earlier

**Comment by mitrov** [comment] 2022-02-09 10:46
I’ll try. My guess is that the problem is before running tests because I didn’t run tests on the manually created container.

**Comment by freddydk** [comment] 2022-02-10 09:34
We have an upcoming fix for 2298 - I would like to see that before diving deeper into this one.

**Comment by freddydk** [comment] 2022-02-15 06:03
Please retry this with insider build 20.0.36207.0 or later, thanks

**Comment by makuhn** [comment] 2022-02-15 07:56
Just tried with `/sandbox/20.0.36210.0/de`. Unfortunately container does not work. I attached the event log of the container.
[PB365-MK-V20DE 2022-02-15 08.43.44.evtx.zip](https://github.com/microsoft/navcontainerhelper/files/8066914/PB365-MK-V20DE.2022-02-15.08.43.44.evtx.zip)

**Comment by freddydk** [comment] 2022-02-15 08:43
Any chance that anybody can share a repro script (end 2 end), which showcases the problem?
possibly email me a link where I can download apps if they are needed.

**Comment by freddydk** [comment] 2022-02-15 09:45
I do now have a repro of the problem.
Will investigate and get back

**Comment by freddydk** [comment] 2022-02-15 21:36
Strangest bug ever - it only fails when you connect using German language (culture)

**Comment by freddydk** [comment] 2022-02-16 13:24
As a workaround, you should be able to add:

 -additionalParameters @("--env customWebSettings=AuthenticateServer=false")
to the New-BcContainer call, then the problem should go away.

You can also specify this in the BcContainerhelper.config.json for all sessions on that machine:

    "defaultNewContainerParameters":  {
                                          "additionalParameters":  [
                                                                       "--env customWebSettings=AuthenticateServer=false"
                                                                   ]
                                      }
or set the variable for one session:

$bccontainerhelperconfig.defaultNewContainerParameters = @{ "additionalParameters" = @("--env customWebSettings=AuthenticateServer=false") }
All should work.

**Comment by freddydk** [comment] 2022-03-01 09:00
This should be fixed in next major.
Please re-open if the issue persists,

**Closed by freddydk** 2022-03-01 09:00 UTC
Labels: bug, Unrelated to BcContainerHelper
