### ISSUE TITLE
Publish takes 15 minutes for a AL project on only 2 seconds on classic server

### ISSUE THREAD

**Issue by ysoldati** [microsoft/navcontainerhelper#919] opened 2020-03-31 07:04 UTC
Hello,

I have a BC14 CU5 container, here is the script I've used to create it and the output.
A publish of the same project takes 15 minutes on docker and only 2 seconds on a classic server.

Thanks,

$securePassword = ConvertTo-SecureString -String "test" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "admin", $securePassword

New-NAVContainer `
    -containerName 'bc14cu5-varnsi' `
    -ImageName mcr.microsoft.com/businesscentral/onprem:14.6.36463.0-be `
    -licenseFile 'C:\NAV\License\bc15.flf' `
    -updateHosts `
    -auth NavUserPassword `
    -Credential $credential `
    -accept_eula `
    -accept_outdated `
    -doNotExportObjectsToText `
    -doNotCheckHealth `
    -Verbose `
    -enableSymbolLoading `
    -includeCSide 

VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_OperatingSystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
NavContainerHelper is version 0.6.4.9
Host is Microsoft Windows Server 2016 Standard - ltsc2016
Docker Client Version is 18.09.0
Docker Server Version is 18.09.0
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_OperatingSystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
Using image mcr.microsoft.com/businesscentral/onprem:14.6.36463.0-be-ltsc2016
Disabling Health Check (always report healthy)
Creating Container bc14cu5-varnsi
Version: 14.6.36463.0-be
Style: onprem
Platform: 14.0.36457.0
Generic Tag: 0.0.9.95
Container OS Version: 10.0.14393.3204 (ltsc2016)
Host OS Version: 10.0.14393.3443 (ltsc2016)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale nl-BE
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\NAV\License\bc15.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\bc14cu5-varnsi\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- updatehosts.ps1
Creating container bc14cu5-varnsi from image mcr.microsoft.com/businesscentral/onprem:14.6.36463.0-be-ltsc2016
7a809b767f9a20cf732260716a5de8b8df4509e61e2bf318f8fde7f5b0a5b97e
Waiting for container bc14cu5-varnsi to be ready
Initializing...
Starting Container
Hostname is bc14cu5-varnsi
PublicDnsName is bc14cu5-varnsi
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint A5CB88031178FCAFFFC5CAD9BC9C544B348FCE29
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.26.141.167
Container Hostname  : bc14cu5-varnsi
Container Dns Name  : bc14cu5-varnsi
Web Client          : http://bc14cu5-varnsi/NAV/
Dev. Server         : http://bc14cu5-varnsi
Dev. ServerInstance : NAV

Files:
http://bc14cu5-varnsi:8080/al-3.0.172401.vsix

WARNING: You are running a container which is 200 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 212 seconds
Ready for connections!
Reading CustomSettings.config from bc14cu5-varnsi
Creating Desktop Shortcuts for bc14cu5-varnsi
Container bc14cu5-varnsi successfully created

**Comment by NAVspecialist** [comment] 2020-03-31 07:45
Not sure what you mean. You have shown an output of a creation of a container that took 212 seconds which I would say is not fast but probably mainly slow because of: You need to update your Operating System, update your NAVcontainerhelper and perhaps change a few of your startup parameters of the image (depending on the purpose/usage of the image). Besides you only have to create it once.

But after creation of the container what does then take 15 minutes vs. 2 seconds ? And can you tell how-to reproduce that amount of usage of time?

**Comment by ysoldati** [comment] 2020-03-31 07:48
As Freddy asked me by email I've sent the script of the container creation and the output.
Creation of the container is not a problem then problem is when I publish an extension to it. It takes 15 minutes the CPU is going to 100%. If I publish same extension on a non -docker environment the publish takes 2 seconds.

**Comment by NAVspecialist** [comment] 2020-03-31 07:51
Ahh, ok.

**Comment by freddydk** [comment] 2020-03-31 07:55
What extension are you trying to publish?
Why do you have -enablesymbolloading on?

**Comment by ysoldati** [comment] 2020-03-31 07:59
An extension developed by the company I'm working for, NSI IT Software & Services. Some code is modified in C/SIDE so I've enabled symbol loading. But I'm facing the problem also with other extensions with other containers.

**Comment by NAVspecialist** [comment] 2020-03-31 08:45
How long time does it take to publish a "Hello World" Extension?

**Comment by freddydk** [comment] 2020-03-31 10:29
Also, please share the script and the output of your publishing process...

**Comment by ysoldati** [comment] 2020-04-01 08:12
Hello,

I'm doing the publish from VS code.
Package creation is fast.


[2020-04-01 09:08:20.44] Publishing AL application using launch configuration 'Your own server'.
[2020-04-01 09:08:20.94] Targeting server 'http://bc14cu5-varnsi' and server instance 'NAV'.
[2020-04-01 09:08:20.96] Using user name and password authentication. User name used is: 'admin'.
[2020-04-01 09:08:20.97] Sending request to http://bc14cu5-varnsi:7049/NAV/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default

this last step takes 15 minutes

and then
[2020-04-01 09:23:58.66] Success: The package 'NSI IT Software & Services_VARNSI_1.0.0.0.app' has been published to the server

**Comment by ysoldati** [comment] 2020-04-01 08:22
> How long time does it take to publish a "Hello World" Extension?

[2020-04-01 10:22:14.52] Publishing AL application using launch configuration 'Your own server'.
[2020-04-01 10:22:14.78] Targeting server 'http://bc14cu5-varnsi' and server instance 'NAV'.
[2020-04-01 10:22:14.89] Using user name and password authentication. User name used is: 'admin'.
[2020-04-01 10:22:14.91] Sending request to http://bc14cu5-varnsi:7049/NAV/dev/metadata
[2020-04-01 10:22:15.04] Targeting server 'http://bc14cu5-varnsi' and server instance 'NAV'.
[2020-04-01 10:22:15.04] Using user name and password authentication. User name used is: 'admin'.
[2020-04-01 10:22:15.04] Sending request to http://bc14cu5-varnsi:7049/NAV/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default
[2020-04-01 10:22:15.58] Success: The package 'Default publisher_HelloWorld_1.0.0.0.app' has been published to the server.

**Comment by freddydk** [comment] 2020-04-01 08:40
How much memory do you have on the machine?

**Comment by ysoldati** [comment] 2020-04-01 08:42
64GO and memory used by the container when publishing is only 2-3GO but CPU goes to 100%

**Comment by freddydk** [comment] 2020-04-01 08:45
Strange that the container only uses 2-3Gb since you are using process isolation - that should go higher. Try to start the container with -memorylimit 10G
You could also try to start the container with -isolation hyperv

**Comment by ysoldati** [comment] 2020-04-01 08:51
Can I stop the container and start it specifying the memorylimit or isolation? Or do I need to recreate it?

**Comment by freddydk** [comment] 2020-04-01 09:25
recreate

**Comment by NAVspecialist** [comment] 2020-04-01 09:34
I don't know if its a  copy-and-paste issue but you have added th `-sign to one of the lines, which I guess is wrong

-enableSymbolLoading `  <----- HERE
-includeCSide

**Comment by ysoldati** [comment] 2020-04-01 10:10
I will try to change the memorylimit. Hyperv is not possible because not installed on the server. I think it was causing problems because the machine is already a virtual machine.

**Comment by ysoldati** [comment] 2020-04-01 10:34
memorylimit was the problem it takes 7 seconds now. We have 20 containers on the server is there a way to change easily the memorylimit of all of these? Or do I need to backup the database, drop the container, recreate it and restore my database for all my 20 containers?

**Comment by freddydk** [comment] 2020-04-01 10:57
typically, when running process isolation you share the memory of the host with no limit.
maybe you have added a setting to docker to limit the memory of every container?

**Comment by ysoldati** [comment] 2020-04-01 11:27
No I don't have any limit in the settings.
Strangely, I've now also the problem on the 10G memorylimit container.
I've uninstalled, unpublished and republished the same extension.

[2020-04-01 13:11:18.74] Publishing AL application using launch configuration 'Your own server'.
[2020-04-01 13:11:19.12] Targeting server 'http://bc14cu5-varnsi-mem' and server instance 'NAV'.
[2020-04-01 13:11:19.13] Using user name and password authentication. User name used is: 'admin'.
[2020-04-01 13:11:19.15] Sending request to http://bc14cu5-varnsi-mem:7049/NAV/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default
[2020-04-01 13:25:17.48] Success: The package 'NSI IT Software & Services_VARNSI_1.0.0.0.app' has been published to the server.

**Comment by ysoldati** [comment] 2020-04-01 20:51
I will ask one of our system engineer if because it is a VM if we have some impacts on docker

**Comment by marknitek** [comment] 2020-04-03 06:57
20 containers with internal sql server will need morr then 64gb of ram. One container will need aboit 4gb when running for a while so tjats 80gb just for containers!
Use an external sql server or stop containers.
Having slow publish times is always a memory limit issue (had that on my dev machine many times)
Use docker stats to watch resource consumption and have an eye on total memory usage in task scheduler. 
We run about 20 containers on our host but with external database servers that works well.

**Comment by ysoldati** [comment] 2020-04-03 07:10
Hello,
I have 20 containers it is true but not all running at the same time. If I stop all the containers, it still takes the same time.
I already watch the docker stats and there was nothing strange. RAM is at maximum 60%. My container takes maximum 3G of RAM.
Kind regards,

**Comment by freddydk** [comment] 2020-04-03 07:52
The publishing process is very memory consuming. You would need to figure out why docker keeps your containers down to 3G. I have never heard that setting the memorylimit didn't work or running process isolation didn't work.

**Comment by ysoldati** [comment] 2020-04-03 07:54
I've planned to do some tests this weekend.
Reboot of the VM, update of docker and then testing with only one user connected to the server and only one container running and I'll let you know the results

**Comment by freddydk** [comment] 2020-04-03 08:00
If that is an option, then I would recommend running Windows Server 2019 instead of Windows Server 2016.

**Comment by freddydk** [comment] 2020-04-29 06:51
Any news on this issue?

**Comment by freddydk** [comment] 2020-05-04 08:32
Closing the issue, please reopen with more information if the issue persists

**Closed by freddydk** 2020-05-04 08:32 UTC
Labels: Cannot repro
