### ISSUE TITLE
New-bccontainer fails because it cannot download image

### ISSUE THREAD

**Issue by StevenHit** [microsoft/navcontainerhelper#3216] opened 2023-10-23 09:20 UTC
Unfortunately, I can no longer create BC19 containers. It seems like it's trying to download the image, but it always fails. Is this a server issue? Thx

```
PS C:\Windows\system32> New-BcContainer -accept_eula -containerName TEMP -artifactUrl $artifactUrl -Credential $credential -auth UserPassword 

BcContainerHelper is version 5.0.7

BcContainerHelper is running as administrator

HyperV is Enabled

UsePsSession is True

Host is Microsoft Windows Server 2019 Standard - 10.0.17763.4851

Docker Client Version is 19.03.5

Docker Server Version is 19.03.5

Removing Desktop shortcuts

Fetching all docker images

Fetching all docker volumes

Pulling image [mcr.microsoft.com/businesscentral:10.0.17763.4851](https://mcr.microsoft.com/businesscentral:10.0.17763.4851)

10.0.17763.4851: Pulling from businesscentral

c9226d61d3bd: Already exists

179757339e05: Pulling fs layer

249005b622b5: Pulling fs layer

1bd84db35466: Pulling fs layer

8d8fcdb453f6: Pulling fs layer

7426861fddd7: Pulling fs layer

64a00288d334: Pulling fs layer

03f4b10d5733: Pulling fs layer

9e478588984a: Pulling fs layer

73697a92d3fe: Pulling fs layer

f8c7b848feec: Pulling fs layer

a9d51d6fc380: Pulling fs layer

7f40690773c0: Pulling fs layer

fb2049eed2b1: Pulling fs layer

8ad50c5caee1: Pulling fs layer

7426861fddd7: Waiting

64a00288d334: Waiting

03f4b10d5733: Waiting

9e478588984a: Waiting

73697a92d3fe: Waiting

f8c7b848feec: Waiting

a9d51d6fc380: Waiting

7f40690773c0: Waiting

fb2049eed2b1: Waiting

8ad50c5caee1: Waiting

8d8fcdb453f6: Waiting

249005b622b5: Verifying Checksum

249005b622b5: Download complete

8d8fcdb453f6: Verifying Checksum

8d8fcdb453f6: Download complete

7426861fddd7: Verifying Checksum

7426861fddd7: Download complete

64a00288d334: Verifying Checksum

64a00288d334: Download complete

03f4b10d5733: Verifying Checksum

03f4b10d5733: Download complete

1bd84db35466: Retrying in 5 seconds

1bd84db35466: Retrying in 4 seconds

1bd84db35466: Retrying in 3 seconds

1bd84db35466: Retrying in 2 seconds

1bd84db35466: Retrying in 1 second

1bd84db35466: Retrying in 10 seconds

179757339e05: Verifying Checksum

179757339e05: Download complete

9e478588984a: Verifying Checksum

9e478588984a: Download complete

1bd84db35466: Retrying in 9 seconds

73697a92d3fe: Verifying Checksum

73697a92d3fe: Download complete

a9d51d6fc380: Verifying Checksum

a9d51d6fc380: Download complete

1bd84db35466: Retrying in 8 seconds

7f40690773c0: Verifying Checksum

7f40690773c0: Download complete

fb2049eed2b1: Verifying Checksum

fb2049eed2b1: Download complete

1bd84db35466: Retrying in 7 seconds

8ad50c5caee1: Verifying Checksum

8ad50c5caee1: Download complete

1bd84db35466: Retrying in 6 seconds

1bd84db35466: Retrying in 5 seconds

1bd84db35466: Retrying in 4 seconds

1bd84db35466: Retrying in 3 seconds

1bd84db35466: Retrying in 2 seconds

1bd84db35466: Retrying in 1 second

1bd84db35466: Retrying in 15 seconds

1bd84db35466: Retrying in 14 seconds

1bd84db35466: Retrying in 13 seconds

1bd84db35466: Retrying in 12 seconds

1bd84db35466: Retrying in 11 seconds

1bd84db35466: Retrying in 10 seconds

1bd84db35466: Retrying in 9 seconds

1bd84db35466: Retrying in 8 seconds

f8c7b848feec: Verifying Checksum

f8c7b848feec: Download complete

1bd84db35466: Retrying in 7 seconds

1bd84db35466: Retrying in 6 seconds

1bd84db35466: Retrying in 5 seconds

1bd84db35466: Retrying in 4 seconds

1bd84db35466: Retrying in 3 seconds

1bd84db35466: Retrying in 2 seconds

1bd84db35466: Retrying in 1 second

1bd84db35466: Retrying in 20 seconds

1bd84db35466: Retrying in 19 seconds

1bd84db35466: Retrying in 18 seconds

1bd84db35466: Retrying in 17 seconds

1bd84db35466: Retrying in 16 seconds

1bd84db35466: Retrying in 15 seconds

1bd84db35466: Retrying in 14 seconds

1bd84db35466: Retrying in 13 seconds

1bd84db35466: Retrying in 12 seconds

1bd84db35466: Retrying in 11 seconds

1bd84db35466: Retrying in 10 seconds

1bd84db35466: Retrying in 9 seconds

1bd84db35466: Retrying in 8 seconds

1bd84db35466: Retrying in 7 seconds

1bd84db35466: Retrying in 6 seconds

1bd84db35466: Retrying in 5 seconds

1bd84db35466: Retrying in 4 seconds

1bd84db35466: Retrying in 3 seconds

1bd84db35466: Retrying in 2 seconds

1bd84db35466: Retrying in 1 second

New-BcContainer Telemetry Correlation Id: e10f8b50-33db-498b-9036-f910b36fefc6

DockerDo : unexpected EOF

ExitCode: 1

Commandline: docker pull  [mcr.microsoft.com/businesscentral:10.0.17763.4851](https://mcr.microsoft.com/businesscentral:10.0.17763.4851)

At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.7\ContainerHandling\New-NavContainer.ps1:782 char:13

+             DockerDo -command pull -imageName $bestImageName | Out-Nu ...

+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
```

**Comment by StevenHit** [comment] 2023-10-23 14:59
We solved the issue. It was related to the Windows Server 2019 build (10.0.17763.4851). For that specific version, you cannot download a corresponding image. It gives the error which was mentioned. We upgraded our server to the latest build (10.0.17763.4974) and issue was solved.

**Comment by freddydk** [comment] 2023-10-23 16:55
I have seen that on one machine as well with this specific image, but I can easily download it on my Windows 11 machine.
Not sure what the problem is, but unrelated to BcContainerHelper

**Comment by StevenHit** [comment] 2023-10-24 09:38
Thx for your feedback. The docker pull is succeeding Today. Yesterday, it didn't work. We tried from different networks.
Do you know who to contact in the future for issues when pulling docker images?

**Comment by freddydk** [comment] 2023-10-24 16:30
Not really, my experience is that these issues gets resolved within a few days and they happen very very seldomly.
One thing you always can do to mitigate is to set the GenericImageName to the imagename that worked yesterday, then it will use the image which exists and you can remove it later.

**Closed** 2023-10-25 18:32 UTC
Labels: Unrelated to BcContainerHelper
