### ISSUE TITLE
[Request] Add apiBaseUrl as a parameter in Publish-PerTenantExtensionApps

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#2393] opened 2022-04-08 17:25 UTC
Hi Freddy, 

Could you please consider to add apiBaseUrl as a new parameter in Publish-PerTenantExtensionApps?

The function is reading apiBaseUrl from the settings of the BcContianerHelper. I would like to use this function to make automated releases using the free DevOps Agent (that is stateless).
It's a project using LS Central, so the base url is not the default one but "https://lscentral.api.bc.dynamics.com"

I'm using the script from the workshop.

Thank you

**Comment by freddydk** [comment] 2022-04-09 06:16
You are using the "old" CI/CD HOL scripts?
The problem is, that apiBaseUrl is used in a lot of functions (and also the baseUrl), meaning that you would have to change scripts in a lot of places.
in AL-Go for GitHub, you can have BcContainerHelper settings in the normal project settings file.
In the old CI/CD HOL - I would add two lines to Install-BcContainerHelper:

$bcContainerHelperConfig.apiBaseUrl = "your api baseurl"
$bcContainerHelperConfig.baseUrl = "your baseurl"

Then all functions will work with this.

**Comment by freddydk** [comment] 2022-04-09 11:48
The first attempt to add this functionality was to add parameters, but I found that these parameters needed to be transferred to a lot of functions and it all just didn't make sense.
Just add the two lines from my comment before your Publish- command and everything should work.

**Comment by eclipses** [comment] 2022-04-09 13:10
Unfortunately I've already tried what you suggested but receivign the following error message:
"The property 'apiBaseUrl' cannot be found on this object. Verify that the property exists and can be set."

**Comment by freddydk** [comment] 2022-04-09 14:03
Try this:
![image](https://user-images.githubusercontent.com/10775043/162577571-66cecf72-4f55-4bf4-80de-d9acc876aef7.png)

What does your machine say?
Maybe you have an old containerhelper in memory.

**Comment by freddydk** [comment] 2022-04-09 14:04
Remove-Module BcContainerHelper
UnInstall-Module BcContainerHelper -allversions 

should get rid of all old versions

**Comment by eclipses** [comment] 2022-04-09 14:11
My machine works exactly like yours. 
In this specific scenario I'm using the free DevOps Agent (that is stateless), the script is installing the module and then when I try to change the value it fails but I've noted that the variable contains the correct value inside the function for this reason I asked you for a new parameter. 

Remove the module I did not test yet but I do not think will fix the issue.

**Comment by freddydk** [comment] 2022-04-09 14:14
If it is a stateless devops agent, it should work.
You must have a spelling mistake or like - please include script and output including the lines I suggest

**Comment by freddydk** [comment] 2022-04-09 14:22
I think I know what the problem is.

After Install-Module, use Import-Module BcContainerHelper

Import-Module is implicit when you call the first function of BcContainerHelper and initializes the config variable.
Meaning that you cannot access the variable before importing.

If this is true, then including the output of your script would have shown that the messages displayed by Import-Module didn't get displayed.

**Comment by eclipses** [comment] 2022-04-09 19:51
This is the script

![image](https://user-images.githubusercontent.com/3910615/162588734-926413c1-e833-4e73-a881-1d88342085b1.png)

and this is the failure

![image](https://user-images.githubusercontent.com/3910615/162588804-c8a52c6d-12c0-4f6c-ab11-0833d8a71dc7.png)

Now the test using Import-Module BcContainerHelper after Install-Module
![image](https://user-images.githubusercontent.com/3910615/162588886-f6d9e242-f31a-4c1b-b11c-8a215513398f.png)
But the result now shows a new error to fix :-(
![image](https://user-images.githubusercontent.com/3910615/162589295-15448273-7739-41a5-99f2-503346f6b4ea.png)
The issue is that while the url to make the call starts with 
https://lscentral.api.bc.dynamics.com/
The scope must be
https://api.businesscentral.dynamics.com/.default
and this is not configurable in the function.

Please can you consider now to add a parameter to pass the scope?

**Comment by freddydk** [comment] 2022-04-09 21:06
When using clientId and ClientSecret, you need to add -tenantId to Publish-PerTenantExtensionApps or you need to use -bcAuthContext instead of clientId and ClientSecret.

**Comment by freddydk** [comment] 2022-04-09 21:08
ParameterSet CC includes all three parameters
https://github.com/microsoft/navcontainerhelper/blob/2ea2bc6a59a650d30761fd0bed972a822f01fe43/BcSaaS/Publish-PerTenantExtensionApps.ps1#L53

I will add an error message if neither CC or AC parameter sets are specified fully to explain this.

**Comment by freddydk** [comment] 2022-04-09 21:27
You only shared part of the script.
The script is trying to create an authcontext with the clientId, clientSecret, tenantId and apibaseUrl using this:

```
$bcauthContext = New-BcAuthContext `
            -clientID $clientID `
            -clientSecret $clientSecret `
            -tenantID $tenantId `
            -scopes "$($bcContainerHelperConfig.apiBaseUrl.TrimEnd('/'))/.default"
```

That fails.
It looks like the resource/scopes is wrong.
Not sure what the right value for that would be?
#2060 is about the same topic - I asked the guy what he did in order to get an AuthContext.

**Comment by eclipses** [comment] 2022-04-10 07:44
Hi Freddy, 

Here the full script:

`Write-Host "Installing BcContainerHelper"
Install-Module BcContainerHelper -Force -AllowPrerelease
Import-Module BcContainerHelper

#$bcContainerHelperConfig.apiBaseUrl = "https://lscentral.api.bc.dynamics.com"
#$bcContainerHelperConfig.baseUrl = "https://lscentral.bc.dynamics.com"

Write-Host "Publishing to tenant"
Publish-PerTenantExtensionApps -useNewLine 
 -ClientID "$(PublisherAppClientID)" 
 -ClientSecret "$(PublisherAppClientSecret)" 
 -tenantId "$(TenantId)" 
 -environment "$(Environment)" 
 -companyName "$(CompanyName)" 
 -appFiles @(Get-Item "Artifacts/output/Apps/*.app" | % { $_.FullName })`

**Comment by eclipses** [comment] 2022-04-10 08:47
Finally a version of the script working for me, I can confirm that the base url is different of the url in the scope.

`Write-Host "Installing BcContainerHelper"
Install-Module BcContainerHelper -Force -AllowPrerelease
Import-Module BcContainerHelper

$bcContainerHelperConfig.apiBaseUrl = "https://lscentral.api.bc.dynamics.com"

$bcauthContext = New-BcAuthContext 
            -clientID "$(PublisherAppClientID)" 
            -clientSecret "$(PublisherAppClientSecret)" 
            -tenantID "$(TenantId)" 
            -scopes "https://api.businesscentral.dynamics.com/.default"

Write-Host "Publishing to tenant"
Publish-PerTenantExtensionApps -useNewLine 
 -bcauthContext $bcauthContext 
 -environment "$(Environment)" 
 -companyName "$(CompanyName)" 
 -appFiles @(Get-Item "Artifacts/output/Apps/*.app" | % { $_.FullName })`

**Comment by freddydk** [comment] 2022-04-10 08:59
Thanks - this means that the scopes which are auto-applied in Publish-PerTenantExtensionApps is wrong.
Will fix that.

**Comment by eclipses** [comment] 2022-04-10 09:12
Scope is correct for MS environments but it it does not match for other environments. 
You can leave everything as is or add the apiBaseUrl and scope as parameters only in Publish-PerTenantExtensionApps to simplify a bit the script for the releases.

**Comment by freddydk** [comment] 2022-04-10 09:35
Whether I add the parameter or not won't make any difference.
The apiBaseUrl is a setting - and that works fine as you have found out - I am not going to add this parameters to the 10 or so functions that uses the setting and transfer values back and forth - a parameter was tried and found to be a bad implementation.

The code I had in the function used the apiBaseUrl setting as scopes - and in your code that works, you use the BC standard api url as scopes - and the error when running with my code was that the scopes was wrong - so if your code works - scopes needs to be "https://api.businesscentral.dynamics.com/.default" and not "$($bcContainerHelperConfig.apiBaseUrl.TrimEnd('/'))/.default"

**Comment by eclipses** [comment] 2022-04-10 09:49
Agreed, my suggestion was only because we found a bit tricky that after the installation of the module, it was needed to import the module in order to initialize the variables and be able to change the apiBaseUrl.
The issue I had was only with Publish-PerTenantExtensionApps not with any other functions.

**Closed** 2022-05-17 04:04 UTC
Labels: question, Fix Ready
