### ISSUE TITLE
Creating a new AAD-enabled sandbox fails

### ISSUE THREAD

**Issue by tfenster** [Microsoft/navcontainerhelper#165] opened 2018-07-10 09:18 UTC
I am creating an AAD-enabled sandbox using http://aka.ms/bcsandboxext with the following parameters (sensitive stuff replaced with abc):

```
VMNAME bcall
TIMEZONEID Central Europe Standard Time
ACCEPTEULA Yes
REMOTEDESKTOPACCESS *
VMSIZE Standard_D4s_v3
VMADMINUSERNAME navadmin
NAVADMINUSERNAME navadmin
AZURESQLADMINUSERNAME navadmin
ADMINPASSWORD 
NAVDOCKERIMAGE bcinsider.azurecr.io/bcsandbox-master:de
REGISTRYUSERNAME abc
REGISTRYPASSWORD 
LICENSEFILEURI 
ASSIGNPREMIUMPLAN Yes
CREATETESTUSERS Yes
SQLSERVERTYPE SQLExpress
APPBACPACURI 
TENANTBACPACURI 
INCLUDEAPPURIS
MULTITENANT No
OFFICE365USERNAME tobias.fenster@abc
OFFICE365PASSWORD 
CREATEAADUSERS Yes
CERTIFICATEPFXURL 
CERTIFICATEPFXPASSWORD
PUBLICDNSNAME bcall.westeurope.cloudapp.azure.com
FINALSETUPSCRIPTURL
RUNWINDOWSUPDATE No
CONTACTEMAILFORLETSENCRYPT tobias.fenster@axians-infoma.de
AUTOSHUTDOWN Disabled
AUTOSHUTDOWNTIME
```

This results in the following error

```
10:42:52 AM Method 'Codeunit50000.CreateTestUsers(number of arguments: 1), with matching argument types.' not found.
10:39:47 AM Running bcinsider.azurecr.io/bcsandbox-master:de (this will take a few minutes)
10:39:47 AM Locale de-DE
10:39:47 AM Version 13.0.23215.0
10:39:47 AM Country DE
10:39:46 AM Using image bcinsider.azurecr.io/bcsandbox-master:de
10:06:37 AM Pulling bcinsider.azurecr.io/bcsandbox-master:de (this might take ~30 minutes)
10:06:18 AM Creating Aad Apps for Office 365 integration
10:06:15 AM Installing OpenXML 2.5
10:06:11 AM Installing SQL Native Client
10:05:54 AM Installing Visual C++ Redist
10:05:53 AM Logging in to bcinsider.azurecr.io
10:05:52 AM Adding Landing Page to Startup Group
10:05:52 AM Add Import navcontainerhelper to PowerShell profile
10:05:52 AM Disabling Server Manager Open At Logon
10:05:52 AM Show hidden files and file types
10:05:52 AM Enabling Font Download in IE
10:05:52 AM Enabling File Download in IE
10:05:43 AM Enabling Docker API
10:05:42 AM Starting docker
10:05:40 AM SetupVm, User: navadmin
10:03:52 AM Launching SetupVm
10:01:42 AM Installing AzureAD PowerShell package
10:00:26 AM Installing AzureRM.Resources PowerShell package
10:00:05 AM Installing AzureRM.ApiManagement PowerShell package
9:59:58 AM SetupStart, User: bcall$
9:57:46 AM Restarting computer and start Installation tasks
9:56:31 AM Installing Docker
9:54:56 AM Using Lets Encrypt certificate
9:54:56 AM Using Nav Container Helper version 0.3.0.2
9:54:39 AM Installing Latest Nav Container Helper from PowerShell Gallery
9:54:39 AM Downloading C:\DEMO\Install-VS2017Community.ps1
9:54:39 AM Downloading c:\demo\SetupStart.ps1
9:54:39 AM Downloading c:\demo\SetupVm.ps1
9:54:39 AM Downloading c:\demo\SetupAAD.ps1
9:54:39 AM Downloading c:\demo\SetupNavContainer.ps1
9:54:38 AM Downloading c:\demo\SetupDesktop.ps1
9:54:38 AM Turning off IE Enhanced Security Configuration
9:54:38 AM Creating Connect.rdp
9:54:38 AM Downloading C:\inetpub\wwwroot\web.config
9:54:38 AM Downloading C:\inetpub\wwwroot\Microsoft.png
9:54:38 AM Downloading C:\inetpub\wwwroot\line.png
9:54:38 AM Downloading C:\inetpub\wwwroot\status.aspx
9:54:37 AM Downloading C:\inetpub\wwwroot\default.aspx
9:51:46 AM Installing Internet Information Server (this might take a few minutes)
9:51:40 AM Installing NuGet Package Provider
9:50:56 AM TemplateLink: https://raw.githubusercontent.com/Microsoft/nav-arm-templates/master/navdeveloperpreviewext.json
9:50:56 AM Initialize, user: bcall$
9:50:56 AM Running Windows Server 2016 Datacenter
9:50:56 AM Starting initialization
```

I'll retry with CREATETESTUSERS = No as the error message seems to point in that direction but this setup should be possible or am I missing something?

**Comment by freddydk** [comment] 2018-07-10 10:12
This is the CreateTestUsers - not sure why it fails but I will try it out.

**Comment by tfenster** [comment] 2018-07-10 10:18
With `CREATETESTUSERS No` I get a bit further but still get an error

```
12:08:58 PM The specified authentication email address 'tobias.fenster@abc' is already being used by another user. You must specify a unique email address.
12:08:38 PM Creating Aad Users
12:05:53 PM Running bcinsider.azurecr.io/bcsandbox-master:de (this will take a few minutes)
12:05:53 PM Locale de-DE
12:05:53 PM Version 13.0.23215.0
12:05:53 PM Country DE
12:05:53 PM Using image bcinsider.azurecr.io/bcsandbox-master:de
11:34:22 AM Pulling bcinsider.azurecr.io/bcsandbox-master:de (this might take ~30 minutes)
11:34:03 AM Creating Aad Apps for Office 365 integration
11:33:59 AM Installing OpenXML 2.5
11:33:56 AM Installing SQL Native Client
11:33:45 AM Installing Visual C++ Redist
11:33:44 AM Logging in to bcinsider.azurecr.io
11:33:43 AM Adding Landing Page to Startup Group
11:33:43 AM Add Import navcontainerhelper to PowerShell profile
11:33:43 AM Disabling Server Manager Open At Logon
11:33:43 AM Show hidden files and file types
11:33:43 AM Enabling Font Download in IE
11:33:43 AM Enabling File Download in IE
11:33:40 AM Enabling Docker API
11:33:39 AM Starting docker
11:33:37 AM SetupVm, User: navadmin
11:33:18 AM Launching SetupVm
11:33:02 AM Installing AzureAD PowerShell package
11:32:47 AM Installing AzureRM.Resources PowerShell package
11:32:27 AM Installing AzureRM.ApiManagement PowerShell package
11:32:20 AM SetupStart, User: cronusall$
11:30:49 AM Restarting computer and start Installation tasks
11:29:49 AM Installing Docker
11:28:15 AM Using Lets Encrypt certificate
11:28:15 AM Using Nav Container Helper version 0.3.0.2
11:27:59 AM Installing Latest Nav Container Helper from PowerShell Gallery
11:27:59 AM Downloading C:\DEMO\Install-VS2017Community.ps1
11:27:59 AM Downloading c:\demo\SetupStart.ps1
11:27:58 AM Downloading c:\demo\SetupVm.ps1
11:27:58 AM Downloading c:\demo\SetupAAD.ps1
11:27:58 AM Downloading c:\demo\SetupNavContainer.ps1
11:27:58 AM Downloading c:\demo\SetupDesktop.ps1
11:27:58 AM Turning off IE Enhanced Security Configuration
11:27:58 AM Creating Connect.rdp
11:27:57 AM Downloading C:\inetpub\wwwroot\web.config
11:27:57 AM Downloading C:\inetpub\wwwroot\Microsoft.png
11:27:57 AM Downloading C:\inetpub\wwwroot\line.png
11:27:56 AM Downloading C:\inetpub\wwwroot\status.aspx
11:27:56 AM Downloading C:\inetpub\wwwroot\default.aspx
11:25:47 AM Installing Internet Information Server (this might take a few minutes)
11:25:36 AM Installing NuGet Package Provider
11:24:36 AM TemplateLink: https://raw.githubusercontent.com/Microsoft/nav-arm-templates/master/navdeveloperpreviewext.json
11:24:36 AM Initialize, user: cronusall$
11:24:36 AM Running Windows Server 2016 Datacenter
11:24:36 AM Starting initialization
```

I'll retry with `CREATEAADUSERS No`

**Comment by tfenster** [comment] 2018-07-10 12:09
With both set to NO it goes through all steps to the end

**Comment by freddydk** [comment] 2018-07-10 12:58
I will test and try to find out why, thanks

**Comment by tfenster** [comment] 2018-07-10 13:43
The Excel AddIn (for "edit in Excel") also gets an error about not being able to update the server config. But I'll wait and see if maybe you find a fix and try again

**Comment by tfenster** [comment] 2018-07-11 12:07
Ok, using vmadmin / admin / sqladmin for the different admins still results in
```
1:24:25 PM Method 'Codeunit50000.CreateTestUsers(number of arguments: 1), with matching argument types.' not found.
```
I'll send you the connection via email

**Comment by tfenster** [comment] 2018-07-11 15:56
Even if I am using vmadmin / admin / sqladmin for the different admins but I still also get the following error if I set CREATEAADUSERS Yes
```
3:06:13 PM The specified authentication email address 'tobias.fenster@abc' is already being used by another user. You must specify a unique email address.
```
What would be a working configuration? Do I need to set tobias.fenster as admin username?

**Comment by freddydk** [comment] 2018-07-11 16:00
use http://aka.ms/bcsandboxext2 - then you get a dev branch of navcontainerhelper
I have also added a proposed fix for the testusers in the dev branch - I think it is a timing problem.

**Comment by tfenster** [comment] 2018-07-11 19:17
bcsandboxext2 does work with `CREATEAADUSERS Yes`, thanks. However, Excel export says 'The Excel Add-in is currently not available in sandbox environments.' if I run microsoft/bcsandbox:us

**Comment by freddydk** [comment] 2018-09-01 06:43
This is caused by some changes to the app, which should prevent Edit In Excel from working in Online Sandbox environments. Containers also had the sandbox flag set.
Not sure if this has been changed again, but the check is in codeunit 6710, you can probably easily find a workaround if you need this before it gets fixed in the app.

**Closed** 2018-09-22 14:02 UTC
Labels: Unrelated to navcontainerhelper
